### ISSUE TITLE
Switching CSS paths between development and live environment

### ISSUE THREAD

**Issue by albi** [bdkjones/CodeKit-1-Old#100]
It would be nice to see a setting in codekit where I can switch the development (local) to live (server) paths for easy deployment. 

For example my images are located "../img" during local development. Switching to a live server with Wordpress running the paths look like "/wp-content/themes/THEMENAME".

Using compass it is no problem, switching the http_path variable in config.rb.

For more information have a look at…
http://compass-style.org/reference/compass/helpers/urls/
http://compass-style.org/help/tutorials/configuration-reference/

**Comment by bdkjones** [comment]
Hi Albi,

Compass support is coming in the next day or two. Hang in there and this won't be an issue.
