### ISSUE TITLE
JS Check syntax with nothing doesn't work...

### ISSUE THREAD

**Issue by leny** [bdkjones/CodeKit-1-Old#101]
Hi,

(sorry for my approximate english, it's not my natural language)

I've created a javascript file with a "//@codekit-prepend jquery.js" statement. The file "jquery.js" is in a framework project.
The include is done perfectly and it works.

But JSHint said that there is errors in jQuery. 
The point is that when I set the "Check syntax with" selectbox to "Nothing", when i save my javascript file, JSHint still checking the syntax of jQuery, (and still find errors, actually).
I've setted the "When processing, First" in preferencies to "do not check syntax", trying to restart codekit, the bug still here.

Or it's not a bug and I'm doing something wrong ?

Thanks,

**Comment by justinwalsh** [comment]
I am having the same problem. Seems like you can't turn off syntax checking in library files.

**Comment by shshaw** [comment]
Same issue here.

**Comment by shshaw** [comment]
Looks like it's an issue with the global setting not overriding an individual file's setting. When I change "When processing files, First..." in Preferences, it still tries to compile & check syntax with JSHint even if you change over to "Check syntax with JSLint" or "Do not check syntax".

However, if you go into the main CodeKit window on the Files tab, select the .js file giving you trouble and change the "Check Syntax With" to Nothing there, it will work as expected.

It seems like the global option should be the default for all files you haven't explicitly overridden, but that's currently not the case.

**Comment by sciascia** [comment]
Similar issue for me, Codekit is finding problems with the un-minified version of jQuery. I have check syntax off in both the main prefs and on the file itself.

Friggin' awesome app though!

**Comment by bokkagroup** [comment]
Same for me. I've turned off syntax checking on the main prefs and on the file itself. Makes no difference.

I'm importing an un-minned version of Nivo Slider and Superfish from a framework and JSHint throws so many errors it just stops and never finishes compiling.

At this point, I can't even use CodeKit because of it.

**Comment by bdkjones** [comment]
This is fixed in build 4993. I'm wrapping up a completely new workflow for JSHint and JSLint. New beta should be out in a few days. 

It is deliciously awesome.

**Comment by shshaw** [comment]
I can't wait to taste it!
