### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by davidlegendmc** [bdkjones/CodeKit-1-Old#102]
I get this error parsing my LESS file.

The previous edits were around removing "lighten(@light-blue, 30)" rules and replacing them with a single declaration of the variable @very-light-blue

LESS file:

/\* Colours */
@dark-grey: #333;
@grey: rgb(100, 100, 106);
@light-grey:lighten(@grey, 40);
@verylight-grey:lighten(@grey, 55);
@blue: rgb(35, 125, 184);
@light-blue: rgb(51, 194, 229);
@very-light-blue: @very-light-blue;

/\* Grid - 7 columns */
@col: 14.2857142857143%;

@import "../bootstrap-less/bootstrap";

@import "feedback"; 

/\* Mixins */
@import "css3/_main";

/\* Reset */
ul, ol, menu {list-style: none;}

.screen_reader {
    text-indent: -9999px;
}

/\* Layout
-------------------------------------------------------------------------------*/
@import "grid";

body {
  padding-top: 60px;
}
p {
  line-height: 1.4em;
}
.map>ol {
  margin: 2rem 0;
  clear: both;
}
.unmapped {
  overflow: hidden;
}
.unmapped>fieldset, .map>ol {
  padding: 2rem 5% 2rem 4%;
}
.unmapped>fieldset {
  margin-right: 3%;
  float: left;
}
footer {
  clear: both;
  margin-top: 2rem;
  padding-left: 52px;
  padding-top: 22px;
  height: 50px;
  background:  url('../../i/logo-small-t.png') no-repeat left top;
}
footer small, footer nav, footer ol, footer li {
  display: inline-block; 
}
footer li {
  margin-left: 12px;
}
footer li:after {
  content: "|";
  margin-left: 12px;
}
footer li:last-child:after {
  content: "";
}
.palette {
    header, footer {
        padding: 2rem;
        background-color: @very-light-blue;
        clear: both;
    }
    section {
    width: 5 \* @col;
    margin-left: @col;
    }
    section>form>ol {
        list-style: none;
    }
    section>form>ol>li {
        border-bottom: 1px solid @very-light-blue;
        margin-bottom: 1rem;
        padding-bottom: 1rem;
    }  
}
.form-stacked label {
    padding-top: 0.6rem;
}
.topbar .brand {
  padding: 0;
  background:  url('../../i/logo-nav.png') no-repeat 7px -3px;
  .screen_reader;
  width: 140px;
  height: 40px;
}
.home .container-fluid > .content {
    margin-left: 332px;
    padding-top: 54px;
}
.container-fluid > .sidebar {
    width: 320px;
  }

/\* Field mapping
-------------------------------------------------------------------------------_/
.map h1 span {
  color: lighten(@grey, 30%);
}
.map>ol {
  border: 4px solid @very-light-blue;
  @include border-radius(12px);
}
.mapping, .unmapped {
    position: relative;
    clear: both;
//  width: 82%;
//  margin: 0.4rem 6% 0;
//  display: -webkit-box;
//  -webkit-box-orient: horizontal;
//  -webkit-box-pack: center;
//  -webkit-box-align: center;
//  display: -moz-box;
//  -moz-box-orient: horizontal;
//  -moz-box-pack: center;
//  -moz-box-align: center;
//  display: box;
//  box-orient: horizontal;
//  box-pack: center;
//  box-align: center;
}
//.unmapped {
//  -webkit-box-align: stretch;
//  -moz-box-align: stretch;
//  box-align: stretch;
//}
.input_fields, .output_fields {
    display: block;
    position: relative;
    float: left;
    width: 50%;
//  -webkit-box-flex: 1;
//  -moz-box-flex: 1;
//  box-flex: 1;
    margin: 0;
}
.connector {
  display: block;
    position: absolute;
    left: 50%;
    width: 70px;
    margin-left: -35px;
    padding: 0 1rem;
    /_background: url('../../i/connector.png') repeat-x left center;_/
    z-index: -100;
    .screen_reader;
}
.mapping a.connector {
    height: 70px;
    padding: 0;
    background-color: #fff;
    background-position: center center;
    background-repeat: no-repeat;
    border: 1px solid @grey;
    -webkit-border-radius: 44px;
    -moz-border-radius: 44px;
    border-radius: 44px;
    z-index:400;
}
.mapping>a:hover {
  background-color: @very-light-blue;
    box-shadow: 0 0 3px 2px @very-light-blue;
}
.add>a {
  background-image: url(../../i/icon-add.png);
}
.join>a {
  background-image: url(../../i/icon-join.png);
}
.split>a {
  background-image: url(../../i/icon-split.png);
}
.field {
  height: 30px;
    padding: 15px 0;
    margin: 0;
    display: block;
    position: relative;
    background: url('../../i/connector.png') repeat-x left center;
}
.group.input_fields .field {
  background: url('../../i/connector-middle-left.png') no-repeat right center;
}
.group.input_fields .field:first-child {
  background: url('../../i/connector-top-left.png') no-repeat right center;
}
.group.input_fields .field:last-child {
  background: url('../../i/connector-bottom-left.png') no-repeat right center;
}
.group.output_fields .field {
  background: url('../../i/connector-middle-right.png') no-repeat left center;
}
.group.output_fields .field:first-child {
  background: url('../../i/connector-top-right.png') no-repeat left center;
}
.group.output_fields .field:last-child {
  background: url('../../i/connector-bottom-right.png') no-repeat left center;
}
.input_fields .field {
    padding-right: 180px;
    z-index: 5;
}
.output_fields .field {
    padding-left: 180px;
}
html .selected label {
    border: 4px solid @very-light-blue;
    border-bottom-width: 0;
    padding: 1px 8px 4px 5px;
}
.field label {
    border: 4px solid transparent;
    border-bottom-width: 0;
    background-color: @grey;
    color: #fff;
    padding: 1px 18px 4px 5px;
    position: absolute;
    top: -12px;
    left: 0.6rem;
    text-align: left;
    font-size: 0.8rem;
    -webkit-border-top-left-radius: 4px;
    -webkit-border-top-right-radius: 4px;
    -moz-border-radius-topleft: 4px;
    -moz-border-radius-topright: 4px;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    .text-shadow(darken(@grey, 30%), 0, -1px, 1px);
    z-index: 200;
    width:  auto;
}
.field.error .help-inline, .field.warning .help-inline, .field.success .help-inline {
  position: absolute;
}
.output_fields label {
    left: 194px;
}
.field input, .field textarea {
  padding: 2px 20px 2px 2px;
    display: block;
    color: lighten(@grey, 30%);
    font-size: 0.9rem;
    height: 1.2rem;
    resize: none;
    border: 1px solid @grey;
    width:  100%;
}
.field input:focus, .field textarea:focus {
    outline: none;
    resize: both;
}
.field textarea:hover {
    resize: both;
}
.field[draggable="true"] label {
    background-image: url(../../i/texture-draggable.png);
    background-repeat: repeat-y;
    background-position: right top;
    cursor: move;
}
.selected textarea {
    box-shadow: 0 0 3px 4px @very-light-blue;
}
.field a {
    background-position: center -30px;
    background-repeat: no-repeat;
    height: 1.2rem;
    width: 1.2rem;
    color: #fff;
    position: absolute;
    border-radius: 3px;
    .screen_reader;
}
.field a.conversion, .field a.validation {
  display: block;
  top: 18px;
}
.field a.conversion {
  right: 159px;
}
.field a.validation {
  right: -22px;
}
.input_fields .field a.conversion {
    background-image: url(../../i/icon-config.png);
}
.output_fields .field a.validation {
    background-image: url(../../i/icon-validate.png);
}
.field a:hover {
    background-position: center 0px;
}
.field a.conversion:hover, .field a.validation:hover {
    background-color: @very-light-blue;
}
a.delete {
    display: block;
    width: 60%;
    bottom: 19px;
    background-image: url(../../i/icon-delete.png);
}
.add a.delete {
    width: 150px;  
}
.input_fields  a.delete {
    left:  70%;
    right: auto;
}
.output_fields  a.delete {
    right: 70%;
    left: auto;
}
.group .input_fields  a.delete {
    right: 16px;
    left: auto;
}
.group .output_fields  a.delete {
    left: 28px;
    right: auto;
}
/_ Not used
.group-selection {
    border: 3px dashed lighten(@light-blue,30);
    -moz-border-radius-topright: 12px;
    -moz-border-radius-topleft: 12px;
    -moz-border-radius-bottomleft: 12px;
    -webkit-border-radius: 12px 12px 0 12px;
    border-radius: 12px 12px 0 12px;
    margin-top: 0.4rem;
    padding-top: 0;
    padding-bottom: 6px;
    padding-right: 2%;
    position: relative;
    left: 48.5%;
    width: 32.5%;

```
.mapping {
position: relative;
left: -150%;
width: 247%;
}
```

}
*/
.group-validation {
    position: absolute;
    left: 110%;
    top: 6px;
    display: block;
    border: 3px solid @very-light-blue;
    box-shadow: 0 0 3px 4px @very-light-blue;
    border-radius: 12px;
    background: #fff;
    height: 36px;
    width: 36px;
    .screen_reader;

```
span {
    display: block;
    height: 22px;
    width: 22px;
    margin: 7px;
    background: url(../../i/icon-validate.png) no-repeat center -28px @grey;
    border-radius: 6px;
}
span:hover {
    background-position: center 2px;
}
```

}
.config {
  position: absolute;
  padding: 1rem;
  width: 200%;
  z-index: 200;
}
.unmapped>fieldset {
  border: 4px solid @very-light-blue;
  @include border-radius(12px);
  margin: 0 5px;
}
.unmapped>fieldset.input_fields {
  margin-right: 10%;
}
.unmapped>fieldset.output_fields {
}
.unmapped .field {
    background: none;
    padding: 0;
    margin-top: 9px;
    height: 28px;
    width: 94%;
}
.unmapped label {
    position: static;
    border-radius: 6px;
    display: inline-block;
    height: 16px;
}
.unmapped .output_fields label {
  background: #fff;
  color: @grey;
  border: 1px solid @grey;
  text-shadow: none;
  padding: 5px 12px 4px 9px;
}
.unmapped .field textarea {
  left: -15px;
  margin: 0 0 0 15px;
  padding-left: 20px;
  position: relative;
  width: 60%;
  z-index: -5;
}
.unmapped .field a {
  opacity: 0;
}
fieldset legend, table caption, .details .mapping h1 {
  color: @light-blue;
  margin: 0 1rem;
  padding: 0 0.5rem;
  font-size: 1.2rem;
}

/\* Alert styles */
# help {

  position: relative;
}
html a.close {
  position: absolute;
  top: 0;
  right: 0.5rem;
  text-decoration: none;
  opacity: 0.5;
  .transition ();
}
html a.close:hover {
  opacity: 1;
}
# help h2 {

  font-size: 3rem;
  padding-top: 2rem;
  text-shadow: none;
  color: #fff;
  padding-top: 2rem;
  padding-bottom: 300px;
  margin-bottom: -280px;
  background: url('../../i/logo-bg.png') no-repeat right top;
}
.home #help {
  height: 263px;
  padding-left: 370px;
}
.alert-message.info {
  overflow: hidden;
  line-height: 2em;
}
.alert-message.info a {
  color: #fff;
}
.alert-message a {
  text-decoration: underline;
}
.alert-message a.btn {
  text-decoration: none;
}
.empty.alert-message p {
  margin-bottom: 9px;
}
.alert-message .btn {
  margin-bottom: 18px;
}
.home .title p {
  font-size: 1.2rem;
}
.btn.add {
}
.btn.add b {
  background: url('../../i/icon-btn-add.png') no-repeat right center;
  display: block;
  padding-right: 30px;
  font-weight: normal;
}
.well {
  padding: 0.35rem;
  margin: 0 18px 18px 18px;
  overflow: hidden;
  display: block;
  position: relative;
}
.well h2 {
  line-height: 1rem;
  color: @grey;
  font-size: 1rem;
  padding-top: 0.3rem;
}
.well .btn {
  position: absolute;
  top: 0.35rem;
  right:  0.35rem;
  margin: 0;
  opacity: 0;
  -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    -o-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}
html .well:hover {
  text-decoration: none;
  background: @light-grey;
}
.well:hover .btn {
  opacity: 1;
}
.btn.v-small {
    font-size: 11px;
    padding: 3px 6px;
}
.btn.selected {
  background: #fff;
  border: 1px solid @grey;
  color: #000;
  cursor: default;
}
form.search {
  display: block;
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px solid @very-light-blue;
}
video {
  position: absolute;
  left: 0;
  top: 19px;
  display: block;
  width: 320px;
  height: 240px;
  margin: 0 1rem;
  background: #000;
}
//Empty styles
.empty {
  background-color: #f5f5f5;
  background-repeat: repeat-x;
  background-image: -khtml-gradient(linear, left top, left bottom, from(#f9f9f9), to(#f5f5f5));
  background-image: -moz-linear-gradient(#f9f9f9, #f5f5f5);
  background-image: -ms-linear-gradient(#f9f9f9, #f5f5f5);
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f9f9f9), color-stop(100%, #f5f5f5));
  background-image: -webkit-linear-gradient(#f9f9f9, #f5f5f5);
  background-image: -o-linear-gradient(#f9f9f9, #f5f5f5);
  -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#f9f9f9', endColorstr='#f5f5f5', GradientType=0)";
  background-image: linear-gradient(#f9f9f9, #f5f5f5);
  border-top: 1px solid #fff;
  border-bottom: 1px solid #eee;
  border-left: none;
  border-right: none;
  overflow: visible;
  padding: 2rem 40px 2rem 110px;
  clear: both;
}
.empty p.standfirst {
  font-size: 1.2rem;
}
.home .empty {
  padding: 4rem 40px 3rem 110px;
}
.home .empty .pointer {
  position: absolute;
  left: -120px;
  top: 2.9rem;
  height: 40px;
  width: 200px;
  background: url('../../i/pointer.png') no-repeat left center, url('../../i/connector.png') repeat-x left bottom, url('../../i/connector.png') repeat-x left top lighten(@light-blue, 40%);
  box-shadow: 0 0 3px rgba(255, 255, 255, 1);
  border: none;
  margin: 0;
  padding: 0;
  border-radius: 4px;
}
.home .empty .pointer b {
  display: block;
  margin: 12px 4px 4px 24px;
  font-size: 1rem;
  line-height: 1rem;
}
//Details
.nav-link {
  display: block;
}
.details fieldset, .details table, .details .mapping div {
  border: 4px solid @very-light-blue;
  .border-radius(12px);
  margin: 0 2% 20px 20%;
  position: relative;
  width: 78%;
}
.details fieldset {
  top: -8px;
}
menu.well {
  margin-left: 0;
}
.details fieldset li {
  border-bottom: 1px solid lighten(@grey, 50%);
  border-top: 1px solid #fff;
}
.details fieldset li:last-child {
  border-bottom: none;
}
.details fieldset li:first-child {
  border-top: none;
}
.details input:disabled, .details select:disabled {
  border: 1px solid transparent;
  background:  none repeat scroll 0 0 transparent;
  cursor: default;
  color: @grey;
  box-shadow: none;
  -webkit-appearance: none;
  -moz-appearance: none;
  width: auto;
}
.details select {
  margin: 0 12px;
  font-size: 1.2rem;
}
.details select:first-child {
  margin-left: 0;
}
.details ol {
  width: 40%;
  float: right;
  margin-right: 12px;
  background: #f9f9f9;
  padding: 0;
}
.details .schemas {
  display: inline-block;
  background: lighten(@light-blue, 40%);
  padding: 0.2rem;
  margin-left: 12px;
  margin-bottom: 1rem;
  .border-radius(6px);
}
.details fieldset .btn {
  position: absolute;
  bottom: 12px;
  left: 12px;
}
.details fieldset h2 {
  display: inline-block;
  padding: 0 12px;
  font-size: 1.4rem;
}
.details fieldset menu {
  position: absolute;
  left: 24px;
  bottom: 12px;
  padding: 0;
  margin: 0;
}
.details fieldset menu a {
  display: block;
  margin-top: 0.4rem;
}
.converts-to {
  display: inline-block;
  height: 15px;
  width: 36px;
  background: url(../../i/icon-converts-to.png) no-repeat center center;
  .screen_reader;
}
.icon {
  display: block;
  height: 24px;
  width: 24px;
  .screen_reader;
}
.reprocess {
  background: url(../../i/icon-reprocess.png) no-repeat center center;
  float: right;
  .icon;
}
.reprocess:hover {
  background-position: center 2px;
}
table caption {
  text-align: left;
  margin-bottom: 0.5rem;
}
.details table .error {
  color: #B94A48;
  display: block;
  padding-left: 24px;
  background: url(../../i/icon-validate.png) no-repeat left center;
}
.details table .fail{
  background: none;
  padding: 0;
}
.details table .fail:before {
  content: "×";
  margin: 0 0.5rem 0 0.1rem;
  font-size: 1.2rem;
  font-weight: bold;
}
.details table .no-errors {
  background: url(../../i/icon-validate.png) no-repeat left center;
  .icon;
}
.details .mapping h1 {
  font-weight: normal;
  margin: 0 2% 0 20%;
  padding-left: 1.5rem;
}
.details .mapping p {
  padding: 1.4rem 12px 0.6rem;
}
.details .mapping b, .details .mapping em {
  background: @light-blue;
  color: #fff;
  .border-radius (40px);
  font-size: 1.4rem;
  padding: 0.3rem 0.7rem;
}
.details .mapping em {
  background: @grey;
  font-style: normal;
}
.details .mapping a.btn {
  position: absolute;
  right: 1rem;
  top: 1rem;
}

/\* Print styles!
-------------------------------------------------------------------------------*/
@media print {

}

/\* Media queries!
-------------------------------------------------------------------------------*/

@media screen and (max-device-width: 480px) {

}

@media all and (orientation: portrait) {

}

@media all and (orientation: landscape) {

}

/\* Import css */

@import "sign-in";

**Comment by bdkjones** [comment]
You've defined a variable and set its value to the variable:

@very-light-blue: @very-light-blue;

This is an infinite loop and, hence, the call stack fills up. The error is in your code, not my app.
