### ISSUE TITLE
Feature request: dismiss window with Escape key

### ISSUE THREAD

**Issue by Jonic** [bdkjones/CodeKit-1-Old#104]
Self explanatory - since the window takes focus when it pops up to indicate any parse errors, it would be insanely handy to be able to quickly close it again with the Escape key.

**Comment by bdkjones** [comment]
This is not good citizenship for OS X apps.

The escape key is meant to be used within the context of the app, not to close the window. That would be a pretty big violation of the HIG. There is an option to stop CodeKit from coming to the front on errors in the preferences window.
