### ISSUE TITLE
Feature request: Toggle window focus steal setting

### ISSUE THREAD

**Issue by Jonic** [bdkjones/CodeKit-1-Old#105]
It would be useful to have a setting to tell Codekit to popup in the background if it has to show itself, rather than jumping to the top of the window stack and removing focus from the current window.

That way I can leave it on screen somewhere, visible but behind my other windows, so I can see it update on error, but not stop me from continuing to code so I can fix whatever it flagged without interruption.

**Comment by bdkjones** [comment]
See the preferences window. This exists.
