### ISSUE TITLE
No way to get out of full screen mode in Lion

### ISSUE THREAD

**Issue by Jonic** [bdkjones/CodeKit-1-Old#106]
The only way to come out of full screen mode is to quit the app.. I imagine few people will ever activate it, but I thought I'd still mention it..

**Comment by steveabraham** [comment]
I can get out of full screen in Lion without any problem just using the normal blue button in the menu bar...

**Comment by bdkjones** [comment]
There's two ways to exit fullscreen:

1) The blue button in the menu bar.
2) The "Exit Fullscreen" command in the View menu. 

This is the standard approach for all Lion apps.

**Comment by Jonic** [comment]
I wasn't seeing the menu bar when moving my mouse to the top of the window.. I couldn't get to the blue button or the view menu, so I figured it was something that could be fixed..

**Comment by bdkjones** [comment]
The menubar animates out when you go into fullscreen. If you move your cursor to the top of the window, it drops back in. This is standard behavior on Lion.

**Comment by Jonic** [comment]
I don't get the menu bar at all, even if CodeKit has focus: http://cl.ly/CDkN

When entering full screen mode, moving my mouse cursor to the top of the screen does nothing, presumably because there isn't a menu to display, so I guess this is something else?

**Comment by bdkjones** [comment]
Ahhh, I think I know what's happening. You're running the app as a status bar icon rather than from the dock, correct?

**Comment by Jonic** [comment]
Yep - I have it running all day and like to keep my doc to as few items as possible..

Just tested with it in the dock instead, and sure enough the menu's present and fullscreen mode behaves as expected.. Looks like you've found the culprit!

**Comment by bdkjones** [comment]
Fixed in 4132.
