### ISSUE TITLE
Issues compiling LESS

### ISSUE THREAD

**Issue by steveabraham** [bdkjones/CodeKit-1-Old#107]
I'm sure it will turn out to be something specific to my computer and not a bug (since no one else seems to be mentioning it)...

I can't compile any LESS files at all.

If I save a blank .less file, it will compile and create the .css file no problem; however any content in the file at all, even just a single comment, results in a compile error.

All it reports is syntax error on line 1, regardless of what's in the file.

Any pointers would be appreciated!
Cheers,
Steve.

**Comment by bdkjones** [comment]
Hi Steve, 

Please email me a LESS file that is not compiling on your machine. Also, you're sure the file is UTF-8 encoded, correct?

**Comment by steveabraham** [comment]
Hi Bryan,

I've emailed that through to you.

Cheers,
Steve.

**Comment by bdkjones** [comment]
Resolved. Example file was corrupt. Creating a new file from scratch with the same code fixed the issue.
