### ISSUE TITLE
Case Sensitive naming not kept

### ISSUE THREAD

**Issue by Fyb3roptik** [bdkjones/CodeKit-1-Old#109]
I have an image file named FileOne.png and after optimizing it gets renamed to fileone.png

I also noticed this on the compressing of the sass file to css. It does not take into consideration the case sensitive name.

**Comment by bdkjones** [comment]
Hmm,

I cannot replicate this issue on my end. Optimizing a PNG file produces a new file with the exact same name, including original case. SASS output is the same.

Have you changed your filesystem from HFS+ Mac OS Extended (Journaled)? Are you working on a thumb drive that's formatted with a different file system (FAT, FAT32, NTFS, etc)?

**Comment by bdkjones** [comment]
I've tested this over and over and found that case sensitivity is preserved. I'm going to assume this is an issue with your system and will need more details to diagnose.

**Comment by Fyb3roptik** [comment]
I will retest and post my findings.
