### ISSUE TITLE
deleting JS files while codekit is running

### ISSUE THREAD

**Issue by lstebner** [bdkjones/CodeKit-1-Old#11]
I deleted a file (via command line) while CodeKit was running and then I went in to see if it would notice, it hadn't yet so I just did a refresh and it hung up for a second then gave me the error message "Multiple validation errors occurred" a few times in a row. I quit and restarted and it did not display any scripts files.

I had to remove and re-add my project to get the scripts to show back up. Simply restoring the files did not fix the issue.

**Comment by lstebner** [comment]
Actually, upon further investigation, using the right click menu from the project and selecting 'clear missing files' also fixed the issue.

**Comment by bdkjones** [comment]
What's the exact command you used to remove the file?

-Bryan

**Comment by bdkjones** [comment]
Also, can you duplicate this issue with any other file or is just the one JavaScript file that is causing it?

-Bryan

**Comment by lstebner** [comment]
I get it to happen with every JS file I remove via command line (I'm simply using 'rm file.js'). If I delete from finder, CodeKit seems to notice immediately that the file has been removed. And it doesn't happen with my less files, only javascript.

**Comment by bdkjones** [comment]
Fixed as of build 2858.
