### ISSUE TITLE
Allow renaming of projects

### ISSUE THREAD

**Issue by danethomas** [bdkjones/CodeKit-1-Old#111]
I have a number of large projects which, due to my development folder structure, all share an assets directory where all my images, js, less, etc are stored. 

I prefer to drag these asset folders to Codekit to keep the amount of refreshing and file scanning down rather than dragging the whole project tree. 

The problem is that I have 6 or 7 'assets' folders in the project list in Codekit. Would be great if we could specify a name for a project while still keeping the path.

Cheers.

**Comment by bdkjones** [comment]
double-click the project name in CodeKit. Wish granted.
