### ISSUE TITLE
Toggle Browser Refresh

### ISSUE THREAD

**Issue by derrickpelletier** [bdkjones/CodeKit-1-Old#112]
Sometimes I think it would be convenient to be able to quickly disable browser reloading.
Like when I'm watching my hockey pool stats while working.
If there was just a toggle in the app beside the search bar or something like that, I imagine it would get a lot of use.

Not that it's unbelievably difficult to toggle manually, just a lot of clicking for something I would like to do a lot.

**Comment by bdkjones** [comment]
eh, I don't want to clutter my UI with stuff like this. 

The reload logic allows you to specify which addresses get reloaded (I've even added a custom one to the latest build), so the app should never reload a sports page that's showing hockey scores.

Toggling auto-reload will involve a trip to the preferences window. Maybe I'll add a keyboard shortcut, though.
