### ISSUE TITLE
No Error With Double Operator

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit-1-Old#113]
When a double operator is present in an included file, no error occurs and the imported file styles are not imported.

To reproduce.
- Create 2 less files, importing one into the other
- in the less file being imported, add "foo {padding: 1*/2px;}"
- When compiling no error occurs and the less file that is importing the other file does not include any of the styles from that imported file.

Let me know if it needs clarified further.  Biggest problem with this bug was tracking down why the styles were not importing into the parent less file since there was no error.

**Comment by bdkjones** [comment]
Is that valid syntax? Doesn't seem like it to me.

**Comment by ghost** [comment]
Just thought of this.  I'm not certain if this is a LESS issue or a CodeKit issue.  Please let me know so I can make sure this is logged in the appropriate place.

Thanks!

**Comment by ghost** [comment]
bdkjones:  No it is not, that is my point, it should throw an error but it doesn't.  It also doesn't include any other styles from that child LESS file being imported.  So without a warning it can be a pain to find what the issue is.

I guess I could have directly compiled the child LESS file (which does throw an error), but only thought of that after a few rounds of testing.

**Comment by bdkjones** [comment]
It's a LESS issue.

**Comment by ghost** [comment]
bdkjones:  Even thought CodeKit throws a syntax error when the file is directly compiled?
