### ISSUE TITLE
Feature Request: per project configuration

### ISSUE THREAD

**Issue by kilianc** [bdkjones/CodeKit-1-Old#117]
One of the best things that codekit could provide is a consistent team coding style.
It's foundamental to have a smart configuration in shared projects over multiple machines.

**Comment by patrickarlt** [comment]
+1

This is one the features that would make CodeKit killer for teams right now its a pain in the ass to manage all out build scripts for various sites moving everything to CodeKit and being able to share the configuration files in the Guthub repos would solve alot of headaches. Plus you can make more money by selling it to every member of a team. :)

**Comment by smallhadroncollider** [comment]
Auto-reload strings on a per project basis would be great too. I don't use the standard localhost as I have lots of test sites. They do all generally have a .local extension, so it's generally fine, but I do occasionally test straight on the production site (probably shouldn't, but often quicker for a quick bug fix on a small site), and being able to set the browser to auto-refresh for those would be useful.

**Comment by darcyclarke** [comment]
Any word on this? I think this is a vital feature to efficiently use Codekit in projects going forward.

**Comment by jrschumacher** [comment]
Looking forward to this feature.

**Comment by bdkjones** [comment]
Stay tuned later this week....
