### ISSUE TITLE
Crashing on jshint fatal error

### ISSUE THREAD

**Issue by firsara** [bdkjones/CodeKit-1-Old#118]
I've also postet this to the actual jshint-project on github (issue #380):

The following line breaks the jshint parser:

var text = 'test';
text = text.replace(/====/g, '==='); // kills jshint

Sure, one could avoid it, writing 'new RegExp('====', 'g', '===');'!

Not sure if it is possible, but maybe you are able to catch such kind of errors and keep codekit alive, I was wondering all the time why my script broke the parser until i figured out the apporpriate line!

**Comment by bdkjones** [comment]
This should no longer be an issue as of build 4993. 

I've insulated the JavascriptCore process that runs JSHint and JSLint, so if it fails (which is already highly unlikely) it will no longer kill the app. Thanks!
