### ISSUE TITLE
Feature Request: Custom URL watching

### ISSUE THREAD

**Issue by simonhamp** [bdkjones/CodeKit-1-Old#120]
We often don't use simple `localhost` URLs for our projects. I know we can use the foremost tab in the browser, but I rarely have the foremost tab as the one I want to keep refreshing... flicking back and forth between browser tabs and windows like I don't know what.

This might be best on a per-project basis, but if we could define the URL pattern to watch for in the browser this would be amazing.

Even as a global setting that lets us define a suffix to watch out for, e.g. *.dev would be good

**Comment by bdkjones** [comment]
Done in 4095.
