### ISSUE TITLE
Indent issue on "Begin Script" comments when importing coffeescript

### ISSUE THREAD

**Issue by medovob** [bdkjones/CodeKit-1-Old#121]
In some scenarios when importing coffeescript files, compilation fails due to the single space indentation of the injected comments

For example if I import a coffeescript that looks something like this

``` coffeescript
(()->
  doSomething()
)()
```

This compiles ok on its own (http://goo.gl/cEBCy)

If there is another imported file after this, codekit injects a comment block like so

``` coffeescript
(()->
  doSomething()
)()

 ### -------------------------------------------- 
     Begin Script2.coffee 
 -------------------------------------------- ### 

doSomethingElse()
```

The injected comment block causes compilation to fail due to the single space indent (http://goo.gl/2vGJQ)

**Comment by bdkjones** [comment]
Noted. 

I've removed the indent in build 4096, which should hopefully solve this issue. Nice catch!
