### ISSUE TITLE
haml includes

### ISSUE THREAD

**Issue by ericgibb** [bdkjones/CodeKit-1-Old#123]
It would be awesome if we could have haml includes/partials in the app. It's so great to create DRY css with less, but when developing sites, I find myself repeating a lot of markup. Any chance we could have some sort of ruby-esque partials to have cleaner/DRYer markup? I know ruby partials let you pass in variables, and that might be too much, but even just including static content might be enough.

**Comment by bdkjones** [comment]
This is something that would need to be added to the HAML language itself. I don't want to lure people into writing a bunch of code that becomes completely useless unless they use CodeKit, which is exactly what would happen if I added support for this to the app but the underlying tools (the HAML executables) didn't recognize it. 

When HAML supports this, CodeKit will support it!
