### ISSUE TITLE
Feature Request: Allow Output to Multiple Files

### ISSUE THREAD

**Issue by patrickarlt** [bdkjones/CodeKit-1-Old#126]
Just like it sounds. It would be great to be able to output both a minified and a expanded version of a file to make debugging and development easier.

Same for javascript.

**Comment by bdkjones** [comment]
Hmm...

I've thought about this for 24 hours and I don't like the multi-file approach. Too complex, too unwieldy. I think a better approach might be to provide an option that lets you have CodeKit skip minification if it finds errors.
