### ISSUE TITLE
Crashes after moving project folder

### ISSUE THREAD

**Issue by ge-org** [bdkjones/CodeKit-1-Old#128]
Hi,

the app crashes when launching after I've moved a project folder to a different location on the disk.

Here's what it says:

```
objc[62791]: garbage collection is OFF
*** Terminating app due to uncaught exception
'NSInternalInconsistencyException',
reason: 'Failed to find a project in the -didFinish...Refreshing handler for path:######
```

**Comment by bdkjones** [comment]
Where did you move the project? And you moved it while CodeKit was NOT running?

**Comment by bdkjones** [comment]
Any additional details on this? I can't replicate it, so I'm going to have to assume it was a weird one-time thing. No one else has reported it.
