### ISSUE TITLE
Occasionally have to re-create projects and frameworks on app launch

### ISSUE THREAD

**Issue by sciascia** [bdkjones/CodeKit-1-Old#131]
I couldn't see this in the bug list so sorry if this has already been mentioned.

A couple of times over the past few days I've opened code kit and have had to re-create all my projects and add all the frameworks - the app is blank as if it's the first time.

Haven't quite pinned down when this happens but once I accidentally closed the main window, couldn't see a way of getting it back so restarted the app - then got a blank window.

Cheers

**Comment by bdkjones** [comment]
Is this issue still going on and can you reliably reproduce it?

**Comment by sciascia** [comment]
I'll be back working on this project tomorrow so will fire up Codekit and see how I go - will report back any issues or a way to replicate the issue.

Cheers

Ben

**Comment by bdkjones** [comment]
Dunno if this is still going on. If so, quit the app and restart it while holding down shift. This will delete the existing data file and allow you to start fresh.
