### ISSUE TITLE
using @import for framework css gives 404?

### ISSUE THREAD

**Issue by rikki-iki** [bdkjones/CodeKit-1-Old#133]
Hi, I hope this isn't a stupid error of mine, but I can't figure it out.

I have: 

@import "base.less"; 

in my projects _all.less_ file, which compiles the _all.css_ with the content of my frameworks _base.less_ correctly.
Though in the browser I'm just getting a 404 error for _css/base.less_

base.less is in a framework, so I'm not sure why the browser is looking for it in the project css folder. Neither project or framework css is being used by the browser.

Thanks,
Rikki

**Comment by bdkjones** [comment]
Hi Rikki,

I'm afraid I can't make heads or tails of your explanation. Can you re-write with more detailed, thorough explanations of what's going on here? Thanks.

**Comment by rikki-iki** [comment]
Ohh sorry. I'm testing it as a write and then the page gets refreshed and I loose what I've written! My apologise if I don't make sense.

I've created a project which works perfectly - has one .less file called project.less (or all.less in my 1st msg)
I then followed the video to create a framework. It also has one .less file called framework.less (base.less in my 1st msg)

When I add @import "framework.less";  into my project.less file, two things happen:
1. The compiled project.css file is full of the css from framework.less - so I'm assuming the import is working fine.
2. In the browser I get the following errors:

Failed to load resource: the server responded with a status of 404 (Not Found) - /css/framework.less
Uncaught Error: Couldn't load http://.../css/framework.less (404) - less-1.0.21.min.js line 9

The javascript error means no css is being rendered at all.
CodeKit's log shows no errors.

I can't see what I've done wrong. It makes no difference where I place the @import , if project.less has anything other then the @import or if the framework.less file has 1 simple rule or 40 complex ones.

Thanks,
Rikki

**Comment by bdkjones** [comment]
What we have here is a complete misunderstanding of how to use CodeKit properly.

When you use CodeKit, you DO NOT use Less.js. CodeKit handles all of the compiling and you simply stick a rel link in the head section of your HTML files to the compiled CSS files. 

Again, you do NOT include Less.js in your HTML, as CodeKit has already compiled the LESS code for you. Remove all references to Less.js from your HTML pages and simply include rel links to the compiled CSS files.

**Comment by rikki-iki** [comment]
Ohh I see!! My apologies for the misunderstanding - and confusion! I read about your application as part of a post about how to use less.js so I thought they were part in parcel.
