### ISSUE TITLE
Less Compile Error

### ISSUE THREAD

**Issue by bigredjoe** [bdkjones/CodeKit-1-Old#134]
I encountered a strange error where the following media query get's cut out of the css file when compiled with CodeKit, but compiles correctly if I use less.js 1.1.6 in the browser:

```@media only screen and (min-resolution: 240dpi)  {
    //CSS Styles
}

```

If I removed the "dpi" from the "240dpi", the media query appears in the compiled css file otherwise it would cut it out when using CodeKit.

I downloaded CodeKit several times to no avail. Hope you figure out what causes this strange bug.

***By the way, CodeKit is awesome! Great work!***
```

**Comment by bdkjones** [comment]
Can you confirm that the file compiles correctly using less.js from the command line or in the browser?

Note: please check that the CSS is generated correctly, not just that the script runs without throwing an error at you.

**Comment by bigredjoe** [comment]
I does appear to generate the css correctly in the browser. But I did find the LESS work around with the ~"my code" to just output the CSS code directly.
