### ISSUE TITLE
Mootools Core/More builder

### ISSUE THREAD

**Issue by kilianc** [bdkjones/CodeKit-1-Old#136]
@bdkjones i think you should really considerate to set up a plug-in environment, basically what codekit does is watch for a file and pass it to a chain of tools, i think this will make things easier to implement.

**Comment by bdkjones** [comment]
Plugins aren't possible.

**Comment by kilianc** [comment]
@bdkjones thanks for the comprehensive reply.

**Comment by bdkjones** [comment]
Sorry. There's another issue on here where someone asked for the same thing and I wrote several paragraphs explaining why plugins aren't possible.
