### ISSUE TITLE
CodeKit fails to compile LESS files encoded in UTF-8 with BOM or UTF-16

### ISSUE THREAD

**Issue by jakepetroules** [bdkjones/CodeKit-1-Old#137]
LESS files that are encoded in UTF-8 with BOM or UTF-16 will always fail to compile. Changing the file encoding to UTF-8 without BOM or ASCII works fine.

**Comment by bdkjones** [comment]
UTF-8 is backwards-compatible with ASCII.

UTF-16 and byte order marks are not supported. The reasoning is fairly simple: 

1) It's mostly Windows programs that throw a BOM on UTF-8 files. CodeKit is a Mac app.
2) UTF-8 is virtually a standard for web markup; other formats are rare.
3) Many of the components that CodeKit uses (such as individual compilers) _expect_ UTF-8 encoding.

And, most importantly:

4) Supporting UTF-16 and BOM would be a crap-ton of work.

It's a good thing to point out, though. I'll add it to the docs and possibly the error messages.

**Comment by jakepetroules** [comment]
Sounds good - perhaps the app could pop up an error message "Files with this encoding are not supported" when it sees them? Amazing app by the way, definitely buying it as soon as it's on the app store.
