### ISSUE TITLE
Stylus - No @extend Support

### ISSUE THREAD

**Issue by bluestrike2** [bdkjones/CodeKit-1-Old#138]
Stylus recently added the @extends functionality to the core a couple days ago. Wanted to open an issue for Codekit support. It's beyond awesome :).

**Comment by bdkjones** [comment]
Beta 7 updates Stylus to 0.22.4. 

Issue fixed with extreme prejudice.

**Comment by bluestrike2** [comment]
You Rock

Cheers,
Tom Stoecklein
