### ISSUE TITLE
Compass compile error

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit-1-Old#141]
I am getting a compass compile error on a "clean" compass project. I created a new compass project using "compass create" with nothing else added. When I make a change to the screen.scss file Codekit gives me the below error. NOTE: When I run "compass watch" on the project compass watch does not report any errors.

I am using Compass 0.11.7 and SASS 3.1.12

Compass was unable to compile one or more files in the project: 

/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- addressable/version (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../addressable/lib/addressable/uri.rb:19
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/tree/rule_node.rb:2
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/engine.rb:7
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass.rb:71
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/version.rb:3
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass.rb:9
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass/dependencies.rb:6
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4:in`each'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:22:in`fallback_load_path'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:33

**Comment by dantz** [comment]
Same Problem with Compass 0.11.5 and SASS 3.1.7. Updating to the latest Versions didn't help either.

Env:
RubyGems Environment:
- RUBYGEMS VERSION: 1.8.11
- RUBY VERSION: 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]
- INSTALLATION DIRECTORY: /Library/Ruby/Gems/1.8
- RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
- EXECUTABLE DIRECTORY: /usr/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - universal-darwin-11
- GEM PATHS:
  - /Library/Ruby/Gems/1.8
  - /Users/Andreas/.gem/ruby/1.8
  - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

Backtrace:
Compass was unable to compile one or more files in the project: 

/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- addressable/version (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../addressable/lib/addressable/uri.rb:19
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/tree/rule_node.rb:2
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/engine.rb:7
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass.rb:71
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/version.rb:3
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass.rb:9
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass/dependencies.rb:6
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4:in`each'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:22:in`fallback_load_path'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:33

**Comment by bdkjones** [comment]
Okay, I know next to nothing about Ruby, but the pattern I'm seeing with people reporting this issue is the "custom_require.rb" line. 

Can you please give me a list of ALL the gems installed on your system? I believe something here is conflicting with Compass components in the CodeKit app bundle.

**Comment by areus** [comment]
Getting a similar error

Compass was unable to compile one or more files in the project: 

/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- addressable/version (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../addressable/lib/addressable/uri.rb:19
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/tree/rule_node.rb:2
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/engine.rb:7
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass.rb:71
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/version.rb:3
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass.rb:9
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass/dependencies.rb:6
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4:in`each'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:22:in`fallback_load_path'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:33

**Comment by bdkjones** [comment]
Hi fellas,

Please send me an email so I can send out a custom build of CodeKit to see if a change resolves this issue. Thanks!

**Comment by edwardsdesign** [comment]
Sure thing. Also, here are the gems I have installed:

chunky_png-1.2.5
compass-0.11.7
fssm-0.2.8.1
rb-fsevent-0.4.3.1
rubygems-update1.8.15
sass-3.1.12

**Comment by bdkjones** [comment]
Issue was a require path in the Addressable gem (a Compass dependency.) 

I do not like Ruby.
