### ISSUE TITLE
Cannot create new folder in webserver documents root using create new compass project

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit-1-Old#142]
When i try to create a compass project directly from Codekit into \Library\WebServer\Documents the create new folder button is disabled. I am assuming this is because of a permissions issue and CK needs to allow me to authenticate so it can continue and create the new dir.

PS: That new linen drawer looks awesome.

**Comment by bdkjones** [comment]
Yep, this is absolutely a permissions issue. Only the superuser account is authorized to write to /Library.

You have two options:

1) Change the permissions on /Library/Webserver/Documents to allow your user account to read/write there.
2) Create a folder in the Finder before attempting to create a new project in Compass.

Unfortunately, App Store guidelines currently disallow any apps that require administrative privileges.
