### ISSUE TITLE
Error creating a Compass project

### ISSUE THREAD

**Issue by oskarrough** [bdkjones/CodeKit-1-Old#143]
Getting the following error when trying to create a Compass project with default settings: http://s.rough.dk/DI8G

My Compass works fine from Terminal without CodeKit, so assuming it's not somehting with my Ruby install but I'm afraid I don't know.

`/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- addressable/version (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../addressable/lib/addressable/uri.rb:19
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/tree/rule_node.rb:2
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass/engine.rb:7
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/../sass.rb:71
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass/version.rb:3
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../../scss/lib/sass/../sass.rb:9
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass/dependencies.rb:6
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:5
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4:in `each'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:4
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34:in `require'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:34
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:22:in `fallback_load_path'
    from /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/compass:33`

**Comment by bdkjones** [comment]
Okay, I know next to nothing about Ruby, but the pattern I'm seeing with people reporting this issue is the "custom_require.rb" line. 

Can you please give me a list of ALL the gems installed on your system? I believe something here is conflicting with Compass components in the CodeKit app bundle.

**Comment by bdkjones** [comment]
Issue resolved in 4742. 

I've updated the website with the new build. Grab a copy and you'll be good to go. The problem was with a require statement in a Compass dependency gem.

**Comment by oskarrough** [comment]
Working perfectly now. Appreciate it.
