### ISSUE TITLE
The CodeKit application is damaged.

### ISSUE THREAD

**Issue by chrisobs13** [bdkjones/CodeKit-1-Old#146]
I just installed CodeKit and get this error when I attempt to compile a .less file:

"The LESS compiler or Node.js is missing. As a result, the app will not function correctly. Please delete the app and re-downlaod it from the App Store."

I installed CodeKit on my work computer last week and it was working fine. I've tried deleting all the files and re-downloading but still get the error. Not sure what do to next. Thanks!

**Comment by bdkjones** [comment]
Huh. That's pretty weird.

For starters, find CodeKit in the Finder, right-click on it and choose "show package contents." Then, find the folder "engines." In that folder should be another folder called "node" and in that folder should be an executable called "node." Verify that it exists. 

Next, find the folder "less" in the engines folder, then look in the subfolder "bin" and verify that there is a file called "lessc" in that folder. 

If both of those exist, this could be a permissions issue on your system. What hardware and OS version are you running? Are you running as an admin or standard user? What other apps/extensions are installed on your system? Are you running anything that's not standard?

**Comment by chrisobs13** [comment]
Sorry, I should have done more due diligence - I closed all programs, restarted my computer and now it works fine.

I seriously look forward to this being available in the MAS so I can send you some money. this program is super, super useful and is well worth at least $20.

**Comment by bdkjones** [comment]
Cool. Issues that fix themselves are my favorite kind.
