### ISSUE TITLE
Cannot call method 'charAt' of undefined

### ISSUE THREAD

**Issue by chadclark** [bdkjones/CodeKit-1-Old#147]
After updating to the latest beta, Version 1.0 (4742), I get the following error when trying to compile a LESS file. Before the update, I did not receive this error.

TypeError: Cannot call method 'charAt' of undefined
    at getLocation (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:204:34)
    at new LessError (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:213:19)
    at Object.toCSS (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:384:69)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/bin/lessc:103:28
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:428:40
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:94:48
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/index.js:113:15
    at Object.parse (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:430:17)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/index.js:112:14
    at [object Object].<anonymous> (fs.js:107:5)

Any ideas? Something up with parser.js?

**Comment by bdkjones** [comment]
Hi Chad,

```
Please send me the Less file that produces this error along with any dependencies I need to compile that file.
```

**Comment by chadclark** [comment]
Thanks for taking a look. The file in question is site-layout.less.

Thanks!

**Comment by bdkjones** [comment]
... where should I find site-layout.less?

**Comment by chadclark** [comment]
Oops. I guess the files would help, huh? Sorry about that:

http://dl.dropbox.com/u/45641/less.zip

**Comment by joehoyle** [comment]
Getting the same error, let me know if you want the LESS files

**Comment by bdkjones** [comment]
Yes please.

**Comment by bdkjones** [comment]
Hi guys, 

This is an issue with Less.js, not CodeKit. The latest version of Less appears to have some bugs in handling certain variable parameters. Things to look for are pixel-ratio definitions in media queries.

I've notified Alexis and he's looking into it.

**Comment by chadclark** [comment]
Ah, good to know. Thank you for looking into it.

**Comment by bentographics** [comment]
Same issue here (TypeError: Cannot call method 'charAt' of undefined)
Is there any fix for this yet? Was thinking of upgrading to the paid Codekit version...
