### ISSUE TITLE
Auto upload of processed files

### ISSUE THREAD

**Issue by richardp-au** [bdkjones/CodeKit-1-Old#151]
It would be nice to be able to have processed files automatically uploaded via FTP. I have my code files automatically uploaded to a development web server upon saving, but this obviously doesn't apply to files generated by CodeKit so I now have to manually upload those files. Having CodeKit automatically upload these files after processing would save a lot of time in the long run.

**Comment by bdkjones** [comment]
This would involve writing a whole FTP client, which is just something I can't take on right now.

Have you thought about working directly on the remote server using CodeKit and Transmit 4's "mount as disk" feature?

**Comment by richardp-au** [comment]
Sounds good. I'll look into it. Thanks.

**Comment by gr33my** [comment]
Late comment but came across this thread today and thought this might be useful for any other latecomers.

Another slick option is mounting your 'remote' via the command line with SSH and SSHFS. This article should get you started. http://stuff-things.net/2015/05/20/fuse-and-sshfs-on-os-x/
