### ISSUE TITLE
Preserve Folder structure on compile

### ISSUE THREAD

**Issue by colabnc** [bdkjones/CodeKit-1-Old#155]
This qualifies more as a feature request than a bug, but it's a pretty sizable one for our workflow:

We'll usually set up our folder structure on the server like:
assets/
-js/
--templates/
-css/
--templates/

Currently, it's a giant pain to have to manually update each file in less/templates to point to the 2nd level folder. 

Is there a way to set a root Less folder and have the folder structure there get compiled as-is to CSS (and likewise for JS files)?

**Comment by bdkjones** [comment]
This ability has been added and will be in Beta 9. 

You'll want to look at the "advanced" tab of the preferences window once it goes live.
