### ISSUE TITLE
Feature Request: Synchronized Custom Output Paths

### ISSUE THREAD

**Issue by johngilesyoder** [bdkjones/CodeKit-1-Old#157]
Huge need for Codekit is the ability to sync file specific custom output paths with other members of a project.  I think really there just needs to be a way for Codekit to recognize an output path command at the top of a file - similarly to how Codekit automatically recognizes import calls from the file.
That way, the custom output path will follow the commit/sync and be recognized by Codekit on the other end. Currently, this is a serious communication liability for a project with many members.

**Comment by bdkjones** [comment]
Yea... the trouble here is the same as in #149. 

CodeKit "locks" the output path of a file until you manually change it in the app. So if you could change it simply by altering a line at the top of a LESS file, then CodeKit would change the output path in the app and you might forget to change the referencing tags in your HTML head elements... etc.

See #149 for a discussion.

**Comment by oneGregWiley** [comment]
I think the benefit here is team or enterprise level management of a given project. Perhaps the plist file, this setting can be changed by a user and only be implemented by another user if the change is accepted.

**Comment by bdkjones** [comment]
What _IS_ on my list is "project settings." So you can select a given project and change the default output paths for all files in that project. 

I also intend to provide a "apply these settings now" feature, which will go in and change all files in a project to the settings you provide. Right now, when you change the settings, they only apply to future projects that you add to the app.

These "project settings" will be saved as (probably) a simple JSON file in the project's root folder. Then, when someone else adds that folder to CodeKit, the app will look for that project settings file and, if it finds it, will use the settings from that file for the project.
