### ISSUE TITLE
This file is not in the project folder

### ISSUE THREAD

**Issue by jonathanpglick** [bdkjones/CodeKit-1-Old#159]
I just installed the new beta (1.0 4742) and can't get it to compile my less.  I drag my css folder into there and it recognizes the less file fine.  Then when I save in my editor it doesn't compile and when I go back to CodeKit the file is grayed out (see screenshot).  The file compiles fine with Less.app.

If I remove the project and drag the folder in again, it recognizes it fine but then the same things happens.

![screenshot](https://img.skitch.com/20120125-je6e1hq9ebs4pg43n9hjgiymff.jpg)

**Comment by bdkjones** [comment]
Interesting. 

What is the full path to the project folder "css"? Is this on your local disk, or are you adding the folder from an external or network drive?

**Comment by jonathanpglick** [comment]
Nope, just a local file `/Users/jonglick/ombu/nike/hpcms/repo/web_root/css`.

**Comment by bdkjones** [comment]
Are you using BBEdit?

If not, what editor are you using?

**Comment by jonathanpglick** [comment]
Tried it with both BBEdit and MacVim.

**Comment by bdkjones** [comment]
Which version of BBEdit?

**Comment by jonathanpglick** [comment]
BBEdit 10.1.1 (3140)

**Comment by bdkjones** [comment]
Try changing BBEdit's settings to use "safe-saves" (atomic saves.) 

This should resolve the issue.

**Comment by bdkjones** [comment]
I believe that has to be done with a terminal command, sine the option is not in the GUI preferences for BBEdit 10.
