### ISSUE TITLE
CSS border-radius compile issue

### ISSUE THREAD

**Issue by honustudios** [bdkjones/CodeKit-1-Old#160]
When a border radius has two sets of values, one set for the horizontal radii and one set for the vertical radii. The presence of the '/' between the values throws it off. 

So when you have: 
border-radius: 0px 0px 120px 120px / 0px 0px 6px 6px; in a LESS file the CSS output is 

border-radius: 0px 0px 120px Infinitypx 0px 6px 6px; rather than the intended code.

**Comment by kilianc** [comment]
You should submit this bug here: https://github.com/cloudhead/less.js

**Comment by honustudios** [comment]
I will thank you. You know after i submitted it i tested it in another compiler and the same thing happened. That's when i figured it wasn't CodeKit. Thank you for the heads up.

**Comment by kilianc** [comment]
You're welcome ;)

P.S. What A Bug!
