### ISSUE TITLE
Support 3rd party Compass extensions

### ISSUE THREAD

**Issue by JohnAlbin** [bdkjones/CodeKit-1-Old#161]
Over in https://github.com/bdkjones/CodeKit/issues/145, bdkjones states that CodeKit doesn't support 3rd party Compass extensions because

> Compass is overhauling the way it installs and manages plugins to make it much simpler, and I plan to code for that setup rather than waste development time on the current (old) way.

I searched https://github.com/chriseppstein/compass/issues but couldn't find a discussion about this proposal to revamp Compass extensions. Can someone point me to this proposal?

Anyway, without 3rd party Compass extensions, the utility of CodeKit for Sass/Compass users is severely hampered.

The workaround is to edit your project's config.rb (I'm a PHP dev, but have a config.rb just to configure Compass) and change

> require 'zen-grids';

to show the full path to the Gem file on your system. Which for me is:

> require '/Library/Ruby/Gems/1.8/gems/zen-grids-1.0.beta.1/lib/zen-grids.rb'

Gem doesn't make it obvious where the actual files are installed on your system, so its kind of a PITA to figure this out. And, of course, any time you update the Compass extension, the path is going to change. :-p

**Comment by bdkjones** [comment]
Unless you're using Ruby Enterprise, it's always going to be /Library/Ruby/Gems/1.8/gems/... Which is not tough.

I talked to Chris Eppstein about Compass before I added it to CodeKit. He's confirmed that they are working on a new plugin system and they expect to launch it "sometime." (The Compass website also makes several references to upcoming changes.) I don't know if there's a formal issue open for it, but I have it on "good authority" that it's on the way. ;)

There's absolutely no point in wasting a bunch of time coding for the current plugin system if it's going to change.

**Comment by JohnAlbin** [comment]
> There's absolutely no point in wasting a bunch of time coding for the current plugin system if it's going to change.

Agreed.

But, I saw those "references to upcoming changes" on the Compass website when I first started using Compass a year ago. ;-) So either we need to help Chris get the changes completed or… well… I'd hate to see CodeKit not support an essential Compass feature.

Can we leave this issue open until the "new way" is implemented in CodeKit? (It took me a bit of searching to find #145 and its suggested workaround.)

**Comment by bdkjones** [comment]
I'll add the workaround info to the website. I agree it needs to be more obvious.

**Comment by pyronaur** [comment]
Totally +1 from here. Would be great to be able to use Sass and Compass extensions.

**Comment by JohnAlbin** [comment]
Note that the work-around (of specifying the full path in config.rb) is currently broken. See #291

**Comment by bdkjones** [comment]
Support for this is coming in the next release. To use third-party plugins, you simply install Compass at the command line and then tell CodeKit to use THAT Compass installation rather than the one that's built in to the app.

Doing this means you'll no longer need to specify full paths in config files and all your plugins should simply work.
