### ISSUE TITLE
chained prepend is appending instead

### ISSUE THREAD

**Issue by fynyky** [bdkjones/CodeKit-1-Old#162]
I'm seeing a bug with coffeescript prepends results in appends instead. 

This happens when the main file imports multiple files, and one of them is itself importing another

For example I have main.coffee, branch1.coffee, branch1branch.coffee, and branch2.coffee

branch1.coffee prepends branch1branch.coffee
and main.coffee prepends branch1.coffe and branch2.coffee

The file output for main.js is

/\* -------------------------------------------- 
##      Begin main.coffee 

*/

/\* -------------------------------------------- 
##      Begin branch1branch.coffee 

*/

/\* -------------------------------------------- 
##      Begin branch1.coffee 

*/

(function() {

}).call(this);

where you can see that the branch1branch and branch1 is appended instead of prepended

**Comment by bdkjones** [comment]
Thanks for the report! I discovered this issue in the latest version. It's a regression. 

I've already fixed it and the next beta, which will likely go out tomorrow, will resolve it.
