### ISSUE TITLE
Image Optimization - Beta 8

### ISSUE THREAD

**Issue by TuckerWhitehouse** [bdkjones/CodeKit-1-Old#164]
Just downloaded the new Beta 8, and when I try to optimize an image, the program crashes.
Running Mac OS X 10.7.2, no issues until this, and no other issues.

**Comment by bdkjones** [comment]
Yep. Wish I had tried to optimize an image before releasing beta 8. It does indeed crash.

The good news is... it's fixed. I've put up another build for download that resolves the issue. You'll want to clear your browser's cache and then go download it. Build 5157.

**Comment by TuckerWhitehouse** [comment]
Haha that was quick :) Thanx.

**Comment by bdkjones** [comment]
When I wake up and see 53 emails in my inbox, I immediately know I fucked something up. Generally, I like to fix it as soon as possible. In this case, it was one line of code.
