### ISSUE TITLE
v.5158 Causing crash on folder import

### ISSUE THREAD

**Issue by unr** [bdkjones/CodeKit-1-Old#169]
Every time I try to import files, after upgrading to the latest beta, the app will crash.

I have yet to get any files / folders imported properly.

I tried serveral times, resulting in an immediate crash in each. Here's a console dump of a few attempts: http://unr.im/2k1x1w2q173H3F1O1S2y
## 

Rebooted. Removed all preference files from CodeKit. Reinstalled versions 5157.

Still crashed on attempting to import a project folder, was given a crash report.

Crash Report: http://unr.im/2P1l0Z171c1U0q1p1o0o

**Comment by bdkjones** [comment]
Quit the app, then restart it while holding down the shift key.

**Comment by unr** [comment]
Perfect, that worked for me!

Any insight as to why this worked? Or more specifically, what holding shift does?

**Comment by bdkjones** [comment]
Holding shift while starting the app forces CodeKit to delete its existing data file (the thing in the crash log called a "persistent store"). 

It appears that the data file was corrupted somehow.
