### ISSUE TITLE
Stops checking for changes after refresh

### ISSUE THREAD

**Issue by johnkernke** [bdkjones/CodeKit-1-Old#170]
As of the latest update (after Janurary 20th), CodeKit seems to stop checking for changes in files after it checks for new/removed files for the project. The refresh doesn't have to be automatic, it can also happen after a manual refresh.

The only way to fix it is to re-add the project into CodeKit.

**Comment by bdkjones** [comment]
Well, I've tested this all over the place and cannot duplicate.

What type of file is demonstrating the issue? What build of the app are you running? What editor are you saving the file in?

**Comment by johnkernke** [comment]
Just testing this issue and again and it appears to have gone away...

Closing issue
