### ISSUE TITLE
CodeKit specific global vars

### ISSUE THREAD

**Issue by slackero** [bdkjones/CodeKit-1-Old#172]
Implement CodeKit specific global vars like Date, JavaScript etc. – maybe in a way like @Date(Format), @JavaScript("eval this")

**Comment by bdkjones** [comment]
Oy. 

The problem with this is that it makes your code REQUIRE CodeKit. How do you see this stuff being used? In Javascript files?

**Comment by slackero** [comment]
I missed such option while compiling LESS files. But you are right, it would require CodeKit.

**Comment by Fresheyeball** [comment]
Can't you just make a file like: globals.js, or globals.less and include it via CodeKit? What is the advantage of having CodeKit manage that for you?
