### ISSUE TITLE
Feature Request: Compile JS to minified and unminified at once

### ISSUE THREAD

**Issue by firsara** [bdkjones/CodeKit-1-Old#173]
Javascripts should have compile options:
  a) Concatenate
  b) Concatenate, then minify
  c) Concatenate + Concatenate, then miniy

This gets interesting when writing Javascript Libraries, split up over several files, where you can specify a compiled output JS, plus a minified version!

**Comment by greystate** [comment]
I actually just do this with "wrapper" files - e.g., having the source files neatly separated and then two separate "wrapper" files for building the final output files - one has magnification "off", the other "on".

**Comment by bdkjones** [comment]
Yep. I like greystate's solution. Keeps the UI and the app simpler.
