### ISSUE TITLE
Syntax errors when @import url() statements include commas

### ISSUE THREAD

**Issue by mannieschumpert** [bdkjones/CodeKit-1-Old#182]
CodeKit is throwing syntax errors when @import statements are used that include commas in the url. 

Specifically, a statement calling Google fonts such as "@import url(http://fonts.googleapis.com/css?family=Inika:400,700);" will throw an error based on the comma between the font weights.

**Comment by bdkjones** [comment]
This is not an issue with CodeKit, it's an issue with whichever underlying tool you're using.

If I recall, there are several threads open over on the Less.js gitHub page that deal with this. There was also a workaround if I remember right.

**Comment by mannieschumpert** [comment]
Ok, thanks! I'm just starting with Less so I hadn't seen that issue outside the context of CodeKit.
