### ISSUE TITLE
Make framework assignable to projects.

### ISSUE THREAD

**Issue by jaggli** [bdkjones/CodeKit-1-Old#184]
Frameworks should not be visible for all projects by default, because of multiple versions of the same framework. It would be nice, if it was possible to assign frameworks to projects.

**Comment by bdkjones** [comment]
Frameworks are, by definition, "global" repositories of files. They are meant to be used across multiple projects. If you have two different versions of the same framework, you should provide different names.

If you need to assign a framework to a project, you should just demote those files to the project itself.

**Comment by jaggli** [comment]
Imagine this (Corporate Framework, files are not touchable):
Framework 1.0 is used in Project A and B
Framework 2.0 is used in every further Project and isn't fully backwards compatible

Because it's the same Framework, there are some identical filenames the same in both versions. Codekit doesn't allow this and thats bad.
