### ISSUE TITLE
Compass project, unable to select config.rb

### ISSUE THREAD

**Issue by flyingeek** [bdkjones/CodeKit-1-Old#185]
I have the following structure:

```
+ root
   config.rb
   + static
      + css
      +sass
      +images
```

If I choose root as the project to add, config.rb is recognized and compass is used

If I choose static as the project to add, when setting project as a compass project, I am asked to select my config.rb but then nothing happens, config.rb seems not recognized, project stays as a non compass project

**Comment by bdkjones** [comment]
That's correct. You need to add the root folder of the Compass project. 

CodeKit does not allow you to use a Compass configuration file that is not within the project's folder.

**Comment by flyingeek** [comment]
This is not nice, I have hundreds of files I do not want codekit to process in vendor directories for example...

**Comment by bdkjones** [comment]
Then you would add the vendor directories to the "skipped items" list in the preferences window. Or, alternately, add the project, then select the files you don't want to process and choose "hide" from the contextual menu that pops up when you right click them.

**Comment by flyingeek** [comment]
Ok that's fine then...I was looking for that function but by using right click on the project...
