### ISSUE TITLE
Feature Request - turn off JS minification from preferences

### ISSUE THREAD

**Issue by chrsr** [bdkjones/CodeKit-1-Old#186]
If I want to use CodeKit just for linting my JavaScript it would be great to turn off concatenating and minification from the preferences. The option could be in the Then: drop down list. I.e. Check Syntax With: JSHint Then "Do nothing".

You can ignore minification and concatenation by checking the "do not compile directly" option within the project window, but having this option in the preferences would make setting this a lot easier.

**Comment by bdkjones** [comment]
This option used to exist, but I removed it because it is logically unnecessary.

If you want to use CodeKit just for linting Javascript, then you can simply choose the "concatenate" option. Since your Javascript files don't import any others, CodeKit will only lint it.

Does that make sense?

**Comment by chrsr** [comment]
Yes that makes sense but I still think it would be nice to have a "do nothing" option so it is obvious that Javascript processing is off.

Even so CodeKit is awesome!
