### ISSUE TITLE
project "root folder" should be project folder || add variable for project folder

### ISSUE THREAD

**Issue by briznad** [bdkjones/CodeKit-1-Old#188]
First off, CodeKit is brilliant. Thank You!!

Currently the project "root folder" is the root of the volume. This makes it difficult to create consistent rules for where compiled files should be placed. Setting the path relative to the root folder doesn't work unless all projects are placing files in the same folder outside of the project folder, which doesn't seem very logical. Setting the path relative to the file doesn't work if you have files from different folders - e.g. CSS & SASS -  that you want compiled to the same folder.

Either the root folder should optionally be the project folder OR the project folder should be assignable via a variable.

![screenshot](https://img.skitch.com/20120209-fc85m9beec19y8692kqdakr4gb.png)

**Comment by bdkjones** [comment]
"Root folder" in this context does not mean the volume root (e.g. / ). Instead, it means: "The folder you added to CodeKit as a project."

That said, output path options have been completely redone for Beta 9. I believe the changes will solve your issue.

**Comment by briznad** [comment]
Cool. Looking forward to it!

On Wed, Feb 8, 2012 at 5:21 PM, bdkjones <
reply@reply.github.com
