### ISSUE TITLE
Feature Request - Ability to turn on and off projects

### ISSUE THREAD

**Issue by mapk** [bdkjones/CodeKit-1-Old#189]
I'd love to be able to turn off a project.  I'm not always connected to the same IP and virtual box, so when I start CodeKit, it lags while trying to connect to certain servers.  Then after some time, the whole program freezes causing me to have to restart it again.  If a project could be turned off, it would spare me from this.

**Comment by paulyoung** [comment]
Commenting so I can get the updates on this one.

**Comment by bdkjones** [comment]
Added in 5417.
