### ISSUE TITLE
CodeKit / BBedit issue

### ISSUE THREAD

**Issue by skyshab** [bdkjones/CodeKit-1-Old#192]
Whenever CodeKit is running, any folders in my BBedit project that contain LESS files exhibit a strange behavior. When I select a particular file in BBedit, it starts flickering in the sidebar. Specifically, it's the icon for closing the file, and also the file status indicator (indicates whether the file has been edited since last save.) Strangely, if I close and re-open the containing folder in BBedit, the phenomena stops, only to start again as soon as I select another file.

What does this have to do with CodeKit, you might ask? Well, it only happens if CodeKit is running. Also, I thought I could ignore it, and concentrate on not having a seizure from the flickering... However, after 5 minutes of this, CodeKit crashed. I set "Refresh Projects" in CodeKit to "never" and still have the issue, FWIW.

I know you don't use BBedit, but I do. Therefore, you should take this seriously. Because CodeKit rocks and I don't want to go back to Less.app.

**Comment by skyshab** [comment]
crap. latest BBedit update seems to fix this. 

so, disregard.

**Comment by bdkjones** [comment]
From the BBEdit team:

> Although BBEdit 9.x performed safe-saves by default, BBEdit 10 does not. Thus, I suspect these errors are the result of BBEdit trying to save over a file that's essentially open (due to how kqueue interacts with the server volume--this might be worth putting into Radar :).
> 
> You can configure BBEdit 10 to perform safe-saves by issuing the following Terminal command:
> 
> defaults write com.barebones.bbedit SafeSavesDisabled -bool NO
> 
> and I believe that should avoid the problem.

**Comment by skyshab** [comment]
Thanks man. BBedit 10.1.1 fixed it right up. I should be flogged for not checking for an update before posting this as an issue.

**Comment by bdkjones** [comment]
Cool. Glad they got it fixed.
