### ISSUE TITLE
Feature Requests: Disable Monitoring & Auto-Upload

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit-1-Old#193]
Two features I'd LOVE to see implemented, but understand if they aren't an immediate priority. :-)
1. **Enable/Disable Project Folder Monitoring**
   Some of my files & projects are located on a network server. When I'm not on that network, CodeKit freezes & I get prompts every minute or two that the server could not be found. The first few times it happens, I can't close CodeKit out to stop this because it keeps freezing. This could also be useful if you have many projects but only want to worry about 1 being monitored but want to retain your project settings.
2. **Automatically Upload Compiled Files**
   With Espresso, I can have the edited file automatically uploaded to my server whenever I save changes. However, when testing stylesheet & script changes that need to be compiled with CodeKit, I have to edit, save, wait for compile confirmation then manually upload the compiled file. For my workflow during the "testing" phase, having those compiled files upload automatically would save me a large amount of time!

See my amazing mockup for an example of how this might look/work per project/file: http://f.cl.ly/items/0x273d2Q2J2P1g2h171Z/CodeKit%20Features.jpg

Thanks for developing CodeKit! This incredible app has changed my workflow so much for the better.

**Comment by shshaw** [comment]
Oops, didn't see (Issue #189)[https://github.com/bdkjones/CodeKit/issues/189]! Sorry for the extra post.

**Comment by thomasflad** [comment]
I would love to see **Automatically Upload Compiled Files**, too. Have the same Workflow as shshaw ...

**Comment by bdkjones** [comment]
Yea... I get a few requests for the upload thing every now and then.

The trouble is that I don't want to write another FTP client. There are already tons of them out there and I can't do a better job than Transmit 4. Why are you testing on a remote server rather than running a local one, such as MAMP?

Adding FTP support to CodeKit would be a crapton of work for a very low payout --- most folks simply don't use the app that way. 

As for the other request: I'm working on it. Closing the issue because it duplicates #189.

**Comment by shshaw** [comment]
For me, the Remote Server is easier to test without having to make a lot of changes to the final code. I just use a "hidden" test directory on the live server to avoid Javascript & file linking issues versus setting up MAMP to run. A remote server also allows me to test on mobile devices & other computers without any fuss.

It appears that Transmit's sync feature may be the answer (I've been meaning to buy it for Amazon S3 management anyway), but now I'm running Espresso for editing, CodeKit for compiling, and Transmit for syncing. Not a deal breaker, but I just have to buy more software & run more apps to accomplish the same goal.

Keep up the good work!

**Comment by ProLoser** [comment]
I wrote my own shell script that rsync's files. It can work for any server I have SSH access to.

I opened another task asking if CodeKit can add support for running a custom command from shell after compile. This would essentially allow me to fire my rsync.
