### ISSUE TITLE
doesn't  work with new growl (1.3.3) 

### ISSUE THREAD

**Issue by bob-van-der-bibs** [bdkjones/CodeKit-1-Old#194]
hi 

i'm not seeing any growl notifications anymore since we upgraded to Growl 1.3.3
Using codekit 1.0 build (5158)

Rdg

**Comment by bdkjones** [comment]
I haven't updated the app to support Growl 1.3+ yet.

**Comment by bdkjones** [comment]
Beta 9 brings the Growl 1.3 framework. Issue should be fixed in build 5369, available now at http://incident57.com/codekit
