### ISSUE TITLE
CHMOD

### ISSUE THREAD

**Issue by marcelhadorn** [bdkjones/CodeKit-1-Old#195]
Sometimes CodeKit decides by itself to just set permissions to 600, even if the source files all do have 755. This is very annoying if after each save the permissions have to be changed. In my envioriment I use A Code-Editor on local stored JS or LESS files which are concatenated to one JS or CSS file with an output folder directly on the server (mounted as disk with panics Transmit).

to 97% this works really fine and is a blessing, but once the files are output as chmod 600, there's no other way than to rename it and include the new file, which outputs a newly named file. I'm running out of possible names now :) Shouldn't the output file always have the same CHMOD as the source file?

**Comment by bdkjones** [comment]
You'll need to be much more specific.

CodeKit rarely creates files itself. It's usually the individual compilers that do that job. What language are you working in? What editor are you using?

**Comment by marcelhadorn** [comment]
No offense, I really love CodeKit, it simplifies the work so much, my bug-report might have sounded a bit harsh.
The editor is Coda, it happens either on Javascript files, but like i said, my output path is directly on the server using Transmit to mount the server as a disk.

Regards, Marcel

**Comment by bdkjones** [comment]
Does the issue manifest when you're NOT working directly on the server? Can you test and see?

The reason I ask is that the issue may not be CodeKit's fault -- it's possible that something is getting mucked up when Transmit goes to put the new file on the remote server.

**Comment by marcelhadorn** [comment]
I never tried it yet, since I develop online mostly. Since it works well up to 97%, I would have to use CodeKit on a project "offline" for a while to really be able to tell. Other than that, I can tell that I never have Permission Issues while uploading files with Transmit, although it might still be the problem, in combination of one of the compilers of CodeKit. If nobody else experiences this issue, then I might have just to continue renaming the file if it happens again, since I have somewhat of an extraordinary developing process, doing everything online :) I started doing this while I had a pretty fast connection, while I might reconsider to develop on a local envoirement  since I'm an much slower connection now. If this happens, and I experience the problem also offline, I most likely will let you know. Until ten, I guess you have way more important things to do. 

Best Regards, and a big thank you for CodeKit,
– Marcel
