### ISSUE TITLE
Feature Request: allow PHP file support in Frameworks

### ISSUE THREAD

**Issue by bokkagroup** [bdkjones/CodeKit-1-Old#196]
I'd like to start by saying this app is fantastic and you'll be getting my money regardless of cost.

It would be nice to manage PHP code snippets in the same fashion as LESS/JS files in Frameworks. Like many developers, I have to reference generic snippets on a regular basis and keeping them centrally located and managed would be great.

Excuse my ignorance if this is crazy complicated, outside of application scope or just generally absurd.

Thanks again for a great app.

**Comment by bdkjones** [comment]
The trouble here is that PHP files don't get "compiled". 

So your PHP file would have this line in it: 

```
<?php include("someFile.php") ?>  
```

And presumably someFile.php would be in a Framework in CodeKit. Well, that include statement is handled by the server, when it goes to load this page. So we can't just replace the path with the absolute path of the file "someFile.php" (which is wherever your framework is stored.) We COULD have CodeKit scan the PHP file for these statements, figure out which files they reference and then copy those files into the project in the right spot... but that eliminates the benefits of the frameworks (one file to modify, etc.)

The only other option is to have CodeKit strip out the include statement and drop in the code from the included file in its place and then write that result to a NEW php file that you could use. But this is cumbersome; now you'd have two php files in your project for the exact same page. 

I definitely see why you'd want to do this, but I think the better solution would be to use your editor's "snippets" feature. Store the PHP you reuse regularly as a snippet in Coda or Espresso and then it's right there when you need it.

**Comment by bokkagroup** [comment]
Makes complete sense. I appreciate the breakdown. Thanks for taking
the time. I still live the app.

Sent from my mobile

On Feb 17, 2012, at 10:32 PM, bdkjones
reply@reply.github.com
wrote:
