### ISSUE TITLE
Unexpected tab order in Compass config screen

### ISSUE THREAD

**Issue by Jonic** [bdkjones/CodeKit-1-Old#202]
I'd expect the tab order to go through the fields on the left, then down the right, but instead it jumps back and forth between the two columns..

**Comment by bdkjones** [comment]
Hmm, I just tested this and the tab key moves the focus down the textFields in the left column correctly.

Images, to Sass, to CSS, to Javascripts, in that order.

**Comment by Jonic** [comment]
Weird - mine goes from CSS output style, to images, environment selection, SASS, CSS, framework/pattern, JavaScripts, and then other options, but I can't tab to the second checkbox there at all.. I can reproduce this every time, whether I'm creating a new Compass project or adding it to an existing one..

I can maybe do a little screencast to show you, if you like?

**Comment by Jonic** [comment]
Just tested again - that tab order is for a brand new Compass project - if I'm adding it to an existing site profile it's different again!

**Comment by bdkjones** [comment]
Hmm, I'll try to replicate the issue.

**Comment by bdkjones** [comment]
Hi Jonic, 

I can't get this issue to duplicate on my machine no matter what I do. The tab order is always correct over here. Is your Mac set to use a language other than English as the default? Do you have any accessibility features turned on?
