### ISSUE TITLE
Feature request: watch all scss files

### ISSUE THREAD

**Issue by hamishtaplin** [bdkjones/CodeKit-1-Old#204]
Currently, CodeKit doesn't watch any .scss files that aren't directly compiled. For example, if you have a _mixins.scss that is imported elsewhere, changing it doesn't recompile your code.

**Comment by bdkjones** [comment]
This issue only applies to SASS partials (starting with an underscore) and is fixed in the upcoming release.

**Comment by hamishtaplin** [comment]
Sweet, I use these extensively. 

Great work btw, love it.
