### ISSUE TITLE
Google Closure Compiler Integration

### ISSUE THREAD

**Issue by josephhenig** [bdkjones/CodeKit-1-Old#209]
The title pretty much says it all.

**Comment by bdkjones** [comment]
Nope. Uglify.js is both faster and generates smaller files that closure. I did my homework and chose the very best tool.

**Comment by josephhenig** [comment]
I did not know that. Then I guess that is not a very important feature. But just for the record closure compiler is also supposed to make the code run faster. It actually parses and performs optimizations on the syntax tree. So it could still be useful to have that as an option. Although not extremely important.

**Comment by bdkjones** [comment]
Uglify.js does the same. :)

**Comment by josephhenig** [comment]
Alright, I looked into Uglify.js a little more and you're right. Good to know. Love the app, by the way.
