### ISSUE TITLE
XHR response header with null content-type error

### ISSUE THREAD

**Issue by bmoeskau** [bdkjones/CodeKit-1-Old#213]
I'm getting a particular javascript file include that results in "content-type" coming across with a null value.  This block of code properly checks for that case before processing the regex:

```
          for (var h in headers) {
            var value = xhr.getResponseHeader(h);
            if (h.toLowerCase() == 'content-type' && value) value = value.replace(/^(.*?);.*?$/i, '$1');
            info[h] = value;
          }
```

However, info[h] still gets set with value = null. Once it lands in the following code it produces a null error:

```
var Live = {

    refreshResource: function (url, type) {
      switch (type.toLowerCase()) {   // <------ type is null
```

Now obviously I need to check out why my one JS file does not seem to have a content-type set, but I think this code should check for this case to avoid locking up the browser (this forces me to completely kill the active tab).

**Comment by bdkjones** [comment]
Hi Brian,

Great catch. A few people have reported some trouble with the new injection reloading, so I'm tracking a handful of changes that need to be made. This is certainly one of them!

**Comment by bdkjones** [comment]
Issue fixed in 5380 by adding a check for null content types before the call to .toLowerCase().

**Comment by bmoeskau** [comment]
Awesome, thanks for the quick response. Great tool -- I'm eagerly awaiting being able to give you some money ;)
