### ISSUE TITLE
Ability to specify arbitrary globals

### ISSUE THREAD

**Issue by bmoeskau** [bdkjones/CodeKit-1-Old#214]
Feature request: Would be very helpful to be able to specify arbitrary globals, as CodeKit / JSHint can never hope to list all possibilities.  As one example, I use [Ext JS](http://sencha.com), plus write my own framework [Extensible](http://ext.ensible.com), both of which expose their own globals (`Ext` and `Extensible`). JSHint obviously supports this through custom comments (e.g. `/*global $:false, jQuery:false */`) -- however it would be impractical to have to go through every source file and add such comments manually (I have hundreds).  Would be super helpful if CodeKit could expose such an option in preferences to specify custom globals for JS[L/H]int.  Thanks!

**Comment by briandw** [comment]
I am very interested in this feature. Currently jshint/lint are of no value to me since I use Ember.js and have a global App object in addition to the Ember globals. I have to turn off the linting since it constantly tells me of the global issue. I love the app BTW, thanks.

**Comment by bdkjones** [comment]
Added in 5867. 

Support includes the ability to define both read-only and readwrite globals for both JSHint and JSLint.
