### ISSUE TITLE
v1.0 Build 5369 doesn't retain 'show growl notifications' pref setting.

### ISSUE THREAD

**Issue by yogoo** [bdkjones/CodeKit-1-Old#216]
Codekit v1.0 Build 5369 doesn't retain unchecked 'Show growl notifications' preference setting.
- Steps to reproduce: go to prefs, uncheck 'Show Grow notifications', quit, relaunch.
- Observed: the checkbox is checked.
- Expected: unchecked checkbox.
- Regression: since v1.0 Build 5369

**Comment by bdkjones** [comment]
Great catch. I'll fix this for the next release.

**Comment by bdkjones** [comment]
Fixed in 5389.
