### ISSUE TITLE
"Choose output folder..." - open in proposed output directory instead of last one chosen

### ISSUE THREAD

**Issue by kabojnk** [bdkjones/CodeKit-1-Old#218]
Title might be confusing. Let me explain better (and yes, this is very nitpicky):

I work on multiple projects, which sit in multiple directories, and we don't really use a css/ subdir for output.  Every time I add a project to Less, I have to change the output folder.  The problem is, every time I choose one, the dialog window always starts in the directory that I last chose for an output folder for the previous project. 

e.g. if I had Project A's output path in /blah/files/projectA/styles, when I add a new Project B and click "Choose output folder...", it starts the dialog window in /blah/files/projectA/styles, meaning I have to go back to the root projects folder and drill down to the appropriate directory.

So yeah, very nit-picky, but I thought I'd ask just in case.  I'd ask if there's a way for the dialog window to just default to the proposed "css/" path relative to the project the user just added... but in many cases that directory does not exist yet until the Less files are compiled (thanks for that, btw, it means I don't have to delete the default output directory every time I load a new project).  So... is there a way to have the dialog window just start out in the root directory of the project added? 

e.g. if I add a "Project B" at /blah/some/path/projects/projectB/styles, when I choose "Choose output folder..." could the dialog window just start out in /blah/some/path/projects/projectB/styles?

Thanks! Really loving the app otherwise. I will buy the shit out of it.

**Comment by kabojnk** [comment]
Ho ho, I'm a dumbass! Just checked the "Advanced" settings under preferences and I can just set my default output directory, which sort of bypasses the issue.  This solves my issue, but I'll leave this open just in case you want to address the whole dialog window's starting directory thing that I was nagging about. Won't take offense if you close it though. :)

**Comment by bdkjones** [comment]
A good suggestion. Implemented and closed. Thanks!

**Comment by kabojnk** [comment]
Cheers!
