### ISSUE TITLE
CSS "Choose output directory...": CodeKit crashes when left blank

### ISSUE THREAD

**Issue by kabojnk** [bdkjones/CodeKit-1-Old#220]
Ok, now I just feel like a jerk adding a new ticket after one earlier today... 

When I erase the path "./css" and leave it blank, CodeKit crashes when I add a new project (by dragging the .less file in, if that makes any difference).  Had to restart the program by resetting defaults in order to get it working again. I think the workaround would be just typing ./ for current directory (or if I was really intelligent I would have just chosen the radio button for "same directory").

Might be a good fix for the end-user experience, but not a big deal...

Here's the dump, just in case you need it:

2/20/12 8:46:36.267 PM CodeKit: (
    0   CoreFoundation                      0x00007fff8eb45fc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff93458d5e objc_exception_throw + 43
    2   CoreData                            0x00007fff9149db8e -[NSPersistentStoreCoordinator executeRequest:withContext:error:] + 1534
    3   CoreData                            0x00007fff914c6434 -[NSManagedObjectContext save:] + 708
    4   CodeKit                             0x000000010b0d337c -[LPModelController saveDataToDisk:] + 141
    5   CodeKit                             0x000000010b0d45b5 -[LPModelController didFinishFindingFilesInProposedNewProjectAtPath:withResult:] + 1080
    6   CoreFoundation                      0x00007fff8eb38591 -[NSObject performSelector:withObject:withObject:] + 65
    7   libdispatch.dylib                   0x00007fff8a3b0beb _dispatch_barrier_sync_f_slow_invoke + 80
    8   libdispatch.dylib                   0x00007fff8a3b172a _dispatch_main_queue_callback_4CF + 308
    9   CoreFoundation                      0x00007fff8eadb06c __CFRunLoopRun + 1724
    10  CoreFoundation                      0x00007fff8eada676 CFRunLoopRunSpecific + 230
    11  HIToolbox                           0x00007fff9383731f RunCurrentEventLoopInMode + 277
    12  HIToolbox                           0x00007fff9383e5c9 ReceiveNextEventCommon + 355
    13  HIToolbox                           0x00007fff9383e456 BlockUntilNextEventMatchingListInMode + 62
    14  AppKit                              0x00007fff8fdeff5d _DPSNextEvent + 659
    15  AppKit                              0x00007fff8fdef861 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
    16  AppKit                              0x00007fff8fdec19d -[NSApplication run] + 470
    17  AppKit                              0x00007fff9006ab88 NSApplicationMain + 867
    18  CodeKit                             0x000000010b0d022d main + 113
    19  CodeKit                             0x000000010b0d01b4 start + 52
)
2/20/12 8:46:36.267 PM CodeKit: **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This NSPersistentStoreCoordinator has no persistent stores.  It cannot perform a save operation.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00007fff8eb45fc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff93458d5e objc_exception_throw + 43
    2   CoreData                            0x00007fff9149db8e -[NSPersistentStoreCoordinator executeRequest:withContext:error:] + 1534
    3   CoreData                            0x00007fff914c6434 -[NSManagedObjectContext save:] + 708
    4   CodeKit                             0x000000010b0d337c -[LPModelController saveDataToDisk:] + 141
    5   CodeKit                             0x000000010b0d45b5 -[LPModelController didFinishFindingFilesInProposedNewProjectAtPath:withResult:] + 1080
    6   CoreFoundation                      0x00007fff8eb38591 -[NSObject performSelector:withObject:withObject:] + 65
    7   libdispatch.dylib                   0x00007fff8a3b0beb _dispatch_barrier_sync_f_slow_invoke + 80
    8   libdispatch.dylib                   0x00007fff8a3b172a _dispatch_main_queue_callback_4CF + 308
    9   CoreFoundation                      0x00007fff8eadb06c __CFRunLoopRun + 1724
    10  CoreFoundation                      0x00007fff8eada676 CFRunLoopRunSpecific + 230
    11  HIToolbox                           0x00007fff9383731f RunCurrentEventLoopInMode + 277
    12  HIToolbox                           0x00007fff9383e5c9 ReceiveNextEventCommon + 355
    13  HIToolbox                           0x00007fff9383e456 BlockUntilNextEventMatchingListInMode + 62
    14  AppKit                              0x00007fff8fdeff5d _DPSNextEvent + 659
    15  AppKit                              0x00007fff8fdef861 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
    16  AppKit                              0x00007fff8fdec19d -[NSApplication run] + 470
    17  AppKit                              0x00007fff9006ab88 NSApplicationMain + 867
    18  CodeKit                             0x000000010b0d022d main + 113
    19  CodeKit                             0x000000010b0d01b4 start + 52
)
2/20/12 8:46:36.267 PM [0x0-0x2e82e8].com.incident57.CodeKit: terminate called throwing an exception

**Comment by bdkjones** [comment]
This crash was actually due to something different. To recover, quit the app and start it back up while holding down shift.
It does not matter if the fields for the output paths are blank; CodeKit simply ignores them in that case.
