### ISSUE TITLE
Allow custom predef config 

### ISSUE THREAD

**Issue by jblanche** [bdkjones/CodeKit-1-Old#221]
Codekit uses JSHint predefined globals that sets a few globals (like browser for document...) for us. 
Sometimes you would like to add your own without the 

```
/*globals foobar: true */ 
```

in each file. 

JSHint gives us a way to do that by defining a predef options in the config file (see https://github.com/factorylabs/jshint-config/blob/master/lint.json or http://www.2ality.com/2011/09/jshint.html ) 
Would be great to have this option in CodeKit too.

**Comment by bdkjones** [comment]
Yea, I originally envisioned using the file comments to do this. But I can see how a GUI preference would come in handy. It's on my list.

**Comment by bdkjones** [comment]
This issue duplicates #214, so I've closed it to consolidate the list.
