### ISSUE TITLE
Add Modernizr support for JSHint

### ISSUE THREAD

**Issue by brilang** [bdkjones/CodeKit-1-Old#223]
In CodeKit, there are options for JQuery, Dojo, MooTools and other common Javascript libraries.
There should also be an option for Modernizr,
There should also be a per-project "free-form" field where additional non-standard libraries/global variables could be specified.

**Comment by bdkjones** [comment]
Yea, to get Modernizer globals defined, you'll need to open an issue with JSHint and JSLint. 

Those categories in the preferences for each tool are defined by the tools themselves and I don't want to branch them and then have to maintain my own separate branch. 

However, the need for custom global definitions is certainly clear and I'll add that.
