### ISSUE TITLE
When adding new CoffeeScript files, automatically set output paths...

### ISSUE THREAD

**Issue by pyronaur** [bdkjones/CodeKit-1-Old#224]
"By replacing all instances of this path component:" Coffeesauces
"With this path component": Resources

Dir Structure:
 /Coffeesauces/app.coffee **is compiled to** /Coffeesauces/app.js

The / in "dir structure" isn't the root of my HD, just the root of the Project folder.
Tried adjusting the paths with or without slashes, doesn't seem to work.

**Comment by bdkjones** [comment]
I just tested this using the exact steps listed and the output path is correctly set to /resources/app.js

My guess is that you typed in the path components, but did not choose the radio button next to the correct option in the preferences window. Please verify that that's the case. 

I think it's a good idea to make it so that when one of the text fields is clicked, the associated radio button is selected.

**Comment by pyronaur** [comment]
Nope.
http://d.pr/3Vg5

I've also tried removing the project from "Projects" and putting it in again (as the currently says "When adding new CoffeeScript files...." ,although it would be great if in the upcoming project manager it would change the settings for all project files instead of the "new" ones).

**Comment by bdkjones** [comment]
Hmm, 

So you have a project structure that looks like this:

```
--ProjectFolder
    --Coffeesauces
          --file1.coffee
          --file2.coffee
    --Resources
          --file1.js
          --file2.js
```

Correct? Because if the "coffesauces" folder IS the root project folder, then that explains what's going on here.

**Comment by pyronaur** [comment]
Exactly the structure you just laid out :)

**Comment by pyronaur** [comment]
Although in Coffeesauces I have also subdirectories (and directories with the same names in Resources), but that doesn't help.

**Comment by bdkjones** [comment]
Well, I'm not sure why it's not working on your end, but it works great over here. Can you send me the actual project so I can take a look?

**Comment by pyronaur** [comment]
> .<
> I found the bug and fixed it haha. It's called - being a human. I spelled Coffee with one F. Haha. I'm sorry, I guess we can close this terrible bug now ^_^
