### ISSUE TITLE
Compressing While Preserving (some) Comments (.less)

### ISSUE THREAD

**Issue by johnsardine** [bdkjones/CodeKit-1-Old#228]
Perhaps it could exist a way of preserving the first coment block on a .less file, similar to the minification in a javascript file.
For example, i develop wordpress themes, and there is the need of a comment block in the beginning of the css file, that would be helpful to preserve while the rest of the file is minified/compressed.

**Comment by bdkjones** [comment]
Hi John,

This is an issue that would need to be opened on the Less.js page. The Less.js compiler handles which comments are stripped and which are left.
