### ISSUE TITLE
.scss files not compiling with optional output_style

### ISSUE THREAD

**Issue by sygint** [bdkjones/CodeKit-1-Old#229]
i keep changing formats like "nested, expanded, compact, compressed" and its not compiling them any different than how it was when i last used compass.app

figured out the reason why is that codekit isn't even changing the output_style for me

other than that and its issue it had the other night with compiling multple .scss's, great program, can't wait to buy it.

**Comment by bdkjones** [comment]
Is this a Compass project?

**Comment by sygint** [comment]
Indeed it is, when I told CodeKit not to compile those two other files that didn't need to be compiled, my compiling worked, I just still couldn't change the  compiling format (expand/nest/compact/compress).

I msg'd you on twitter earlier about being a former windows application developer who is looking to get into mac development who wanted to beta for you.

**Comment by bdkjones** [comment]
If it's a Compass project, then you need to change the output style in the config.rb file for the project. CodeKit just compiles the whole project at once anytime a SASS file in a Compass project changes, so Compass uses the setting in that file to figure out how it should proceed.

**Comment by sygint** [comment]
The only reason reason I listed it as a bug is your program lead me to believe it was a bug was I thought that it worked the same way in Sass? config.rb? Am I wrong? If so, that'd be an awesome addition to support those simple config changes.

**Comment by bdkjones** [comment]
Hmm, not sure what you mean in your last post. 

As soon as you turn on Compass for a project, you handle all the settings for the SASS/SCSS files in that project by modifying the config.rb file. You can no longer change settings for SASS/SCSS files in CodeKit.

**Comment by sygint** [comment]
I am saying code kit could easily edit those files like compass.app does its very handy

**Comment by sygint** [comment]
http://i44.tinypic.com/axnvqr.png

^ in my compass project, i can change the settings they simply do nothing, more so than why won't they work, why do you not simply have those boxes edit the config.rb?

**Comment by sygint** [comment]
I am sorry for all the back and forth and misunderstandings, it seems this is more me not understanding how sass works compared to compass, I guess this is not a bug, and rather an ecstatic fan asking for a feature request to support editing of compass's config.rb via codekit :]

**Comment by bdkjones** [comment]
I may add that support at some point in the future.

Right now, my reasoning is that those folks who are comfortable with Compass are also comfortable editing a config.rb file to change settings. And adding support for CodeKit to edit these config.rb files is tricky, because the app must detect any changes a user made directly to the file itself and not overwrite those when editing the file.

For now, I have more important things to code.

**Comment by sygint** [comment]
fair enough :] love the program, can't wait to see what you add next
