### ISSUE TITLE
Dead softlinks = Crash

### ISSUE THREAD

**Issue by jaggli** [bdkjones/CodeKit-1-Old#230]
When linking .less files (maybe others too) and deleting the original file (dead links), CodeKit keeps crashing at startup/refresh.

Took me a while, to figure out. The links were made by "ln -s target/file.css ./"

Please don't just eliminate the ability to use softlinks, this is very usefull, e.g. linking file.less -> file.css for including the css file without renaming the original file.

**Comment by bdkjones** [comment]
I don't understand what you mean by "softlinks." I don't recognize the syntax: "ln -s target/file.css ./"

What is that?

**Comment by jaggli** [comment]
What a softlink is:
The correct name for softlinks is "symbolic links" - Somehow most people keep calling them softlinks, don't know why, maybe because there are also "hard links" in UNIX.
However, a symbolic link is a special type of a file. Being more specific, it's a location abstraction for an other file. It looks like a file to the system but it's some kind of an alias.
http://en.wikipedia.org/wiki/Symbolic_link

What the syntax means:
It's an unix command, entered in the Terminal ( /Applications/Utilities/Terminal.app ). It creates a symbolic link for the target/file.css in the current folder ./

**Comment by bdkjones** [comment]
Ah, yea, symbolic links.

These are not officially supported. The reason is fairly complex and has to do with how they interact with kernel queues and file aliases.

If you're going to use them, then you need to make sure they stay pointed at the right locations. I highly, highly recommend you don't use them. Renaming a file from "file.css" to "file.less" is much, much cleaner than creating a symbolic link.

**Comment by eturino** [comment]
In my case, it seems to work with the symlink but it is slower and gives a lot of errors to the Console. 

I have a "common" subdirectory where I have some .less files common to a bunch of projects. In each of the project in the /style folder there is a subfolder "common" which is a symlink to the actual common folder that is in another repository. 

I cannot change this right now... Can you look into it, please? 

Thanks

**Comment by matjae** [comment]
@eturino I experimented a lot with symlinks and CodeKit, my summary is:
Avoid it. 

A short list of my results:
Random crashes, startup crashes, UI-freeze, browser refresh-loops and a few more..

Long story short: Codekit does absolutely NOT support symlinks.
