### ISSUE TITLE
Coffeescript: Accidental File Cloning ?

### ISSUE THREAD

**Issue by pyronaur** [bdkjones/CodeKit-1-Old#232]
Okay,
Now that I have my Coffesauces and Resources setup properly, CodeKit is bugging like this now:
http://d.pr/YUXP

I'm seeing the file there multiple times, but thankfully in Finder I have only one of them. There are multiple variations of this bug ,sometimes coffeescript compiles a file, and then compiles the compiled file and adds the -ck extenstion of the filename (as the minified version). 
Build 5380

**Comment by pyronaur** [comment]
Problem?
http://d.pr/aPcI

**Comment by bdkjones** [comment]
I have no idea what's going on here. I'll need you to send me the project that's causing this so that I can attempt to replicate it on my end.

In the meantime, you'll want to quit CodeKit and restart it while holding down shift. Then, add the project again and see if this behavior continues.

**Comment by pyronaur** [comment]
Shift start helped. Maybe some bug due updating the versions of CodeKit or something. I has no idea.

**Comment by bdkjones** [comment]
I believe the data file was corrupted somehow. See if the issue returns. Until then, I'm gonna close this as a one-time bug.

**Comment by pyronaur** [comment]
Meh, it came back. A gazzilion of app.js files (in CodeKit) again.

**Comment by pyronaur** [comment]
A theory on what is causing this: Using an Aptana Studio based code editor called Titanium Studio, for mobile app development. When the project is "cleaned", something in CodeKit gets mixed up and suddenly CodeKit starts this bug.

**Comment by bdkjones** [comment]
Isn't that a Java app?

**Comment by pyronaur** [comment]
Well Titanium bought Aptana Studio, and with Titanium Studio you can make Cross-Platform mobile apps, written in JavaScript, so now Aptana/Titanium is mostly used for JavaScript (Aptana was good with JS before Titanium too).  
Long story short - when JavaScript files are being compiled and there are other kinds of files around - when the project is auto-cleaned, Codekit starts to bug this way. I assume something similar could happen with Node targeted development files as well.
The Javascript that is output by the Coffeescript I write isn't then compiled to binary code or something, the "clean" isn't doing anything with the javascript files, it i just cleaning the build folder.

CodeKit is watching for changes in /Project/*
I have my CS Files in /Project/Coffeesauces/*
I have my JS files compiled to /Project/Resources/
And when I build the app, I get a /Project/build/   folder full of android, iOS, Xcode, and even javascript files. 

I bet the build folder is causing the bug. An easy fix would be option to blacklist folders for projects (which would be a nice option anyways).

**Comment by bdkjones** [comment]
I meant: Isn't Aptana a Java-based app. As in: written in Java and requires the Java bridge on OS X to run.

The help page explains why CodeKit does not support Java-based editors.

**Comment by pyronaur** [comment]
I write my Coffeescript and perform most of my actions in Sublime Text. I only run, compile and clean from Titanium. 
And thats why "don't watch a folder" option would be really handy. If I could make CodeKit not watch the build folder, it wouldn't even know Java was there :)

**Comment by bdkjones** [comment]
This is easily done. Simply add the name of the build folder to the "skipped items" list in the preferences window. Then remove all projects that contain that folder and re-add them to CodeKit.

**Comment by pyronaur** [comment]
Lovely. 
Didn't notice you already have that. Well, this will probably remove all the bugs for me for now.(_"cough" need this in per project settings too "cough"_)

**Comment by bdkjones** [comment]
It doesn't make any sense in a per-project setting, because the items in that list are skipped WHILE you add the project. If you add the project to the app, THEN go set the skipped items list on that project, those items were already added. 

Please let me know if this solves the issue you're seeing though!
