### ISSUE TITLE
Working with file:/// in Chrome

### ISSUE THREAD

**Issue by TuckerWhitehouse** [bdkjones/CodeKit-1-Old#233]
In Chrome (and I believe safari as well), ajax calls cannot be made on local urls (so file:///). Not that this will effect hardly anyone, but on the off chance that you create a basic html and css/less project not running on a local web server, and you use CodeKit to compile the less file, any changes made that cause it to compile and attempt to dynamically inject in the browser will throw and error in the web console and not reload the css file.

If you could just add a line to the top of the live reload script that you use that checks for the file:/// protocol and reloads the page rather than try and ajax call, that would be perfect.

e.g. if ( location.protocol == 'file:' ) { location.reload(); return false; }

**Comment by bdkjones** [comment]
Nope. file:// urls aren't supported. 

I've tested a full-page reload with them and it turns out that because of some implementation semantics in Safari, even the full-page reload does not cause changes to display. You have to actually click the refresh button.

Hence the notes on the site.

**Comment by TuckerWhitehouse** [comment]
Wow, i'm sorry, I feel like a douche, i've ready every other releases notes, except this one.
Thank you.
