### ISSUE TITLE
@codekit-append fails to import files in "libs" subdir

### ISSUE THREAD

**Issue by ockam** [bdkjones/CodeKit-1-Old#234]
When using @codekit-append like this:

//@codekit-append "libs/file1.js", "libs/file2.js", "file3.js";

Codekit only see file3.js.

If I rename the directory to something other than "libs" (an update the import string accordingly), it works again.

This was working in the previous beta. I’m currently on 5380.

**Comment by bdkjones** [comment]
Please send me a test project that demos the issue.

**Comment by ockam** [comment]
Heres a sample project.

On 2012-02-24, at 17:12, bdkjones wrote:

> Please send me a test project that demos the issue.
> 
> Sent from my iPhone
> 
> On Feb 24, 2012, at 14:08, Ockam reply@reply.github.com wrote:
> 
> > When using @codekit-append like this:
> > 
> > //@codekit-append "libs/file1.js", "libs/file2.js", "file3.js";
> > 
> > Codekit only see file3.js.
> > 
> > If I rename the directory to something other than "libs" (an update the import string accordingly), it works again.
> > 
> > This was working in the previous beta. Im currently on 5380.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/bdkjones/CodeKit/issues/234
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bdkjones/CodeKit/issues/234#issuecomment-4166161

Pierre Lemieux  Associ
Ockam     44 Saint-Nicolas, Qubec  G1K 6T2    418.704-2344

**Comment by bdkjones** [comment]
There's nothing attached...

**Comment by ockam** [comment]
Seems like the attachment has been striped.

You can download it here: http://ock.am/temp/Codekit.zip

On 2012-02-27, at 00:31, bdkjones wrote:

> There's nothing attached... 
> 
> On 24 Feb 2012, at 15:27 , Ockam wrote:
> 
> > Heres a sample project.
> > 
> > On 2012-02-24, at 17:12, bdkjones wrote:
> > 
> > > Please send me a test project that demos the issue.
> > > 
> > > Sent from my iPhone
> > > 
> > > On Feb 24, 2012, at 14:08, Ockam reply@reply.github.com wrote:
> > > 
> > > > When using @codekit-append like this:
> > > > 
> > > > //@codekit-append "libs/file1.js", "libs/file2.js", "file3.js";
> > > > 
> > > > Codekit only see file3.js.
> > > > 
> > > > If I rename the directory to something other than "libs" (an update the import string accordingly), it works again.
> > > > 
> > > > This was working in the previous beta. Im currently on 5380.
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/bdkjones/CodeKit/issues/234
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/bdkjones/CodeKit/issues/234#issuecomment-4166161
> > 
> > Pierre Lemieux  Associ
> > Ockam     44 Saint-Nicolas, Qubec  G1K 6T2    418.704-2344
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/bdkjones/CodeKit/issues/234#issuecomment-4167288
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bdkjones/CodeKit/issues/234#issuecomment-4188255

Pierre Lemieux  Associé
Ockam     44 Saint-Nicolas, Québec  G1K 6T2    418.704-2344

**Comment by bdkjones** [comment]
If I add the sample project to CodeKit over here, everything works correctly. All three files are shown as imported into "compiled_scripts.js" and when I process that file, all three files are concatenated as expected.

Given that this issue resolves itself when you rename the "libs" folder to something else and then change the statements in the file, I'm pretty sure there's something that's not matching between the folder name and the append statement. That is, are you sure you've typed the folder name correctly?

**Comment by ockam** [comment]
You are right: I did some new tests and this morning and it works. This is really weird because it happened to me and a coworker on the same project. I don’t know what BOTH of us did wrong.

Anyway, thank you very much for your time. I’m really sorry to have bothered you with that.

By the way, it would be really useful to have a way to share Codekit configuration for a project, like allowing to create an optional config file (.codekit.conf) at the root of the project folder we’re watching. You could also use this file to specify file concatenation, instead of using a JS file (but that would be less obvious...).

On 2012-02-28, at 18:44, bdkjones wrote:

> If I add the sample project to CodeKit over here, everything works correctly. All three files are shown as imported into "compiled_scripts.js" and when I process that file, all three files are concatenated as expected.
> 
> Given that this issue resolves itself when you rename the "libs" folder to something else and then change the statements in the file, I'm pretty sure there's something that's not matching between the folder name and the append statement. That is, are you sure you've typed the folder name correctly?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bdkjones/CodeKit/issues/234#issuecomment-4228558

Pierre Lemieux  Associé
Ockam     44 Saint-Nicolas, Québec  G1K 6T2    418.704-2344

**Comment by bdkjones** [comment]
Yea, the details about how OS X stores information on folders and files are quite complex. Suffice it to say that I think something about that original project's folder/file information was messed up at a low level. Could be a bit of disk corruption, could be just something wacky. But it does not appear to be a bug in CodeKit. 

Glad you got it working!
