### ISSUE TITLE
Help button links to wrong page

### ISSUE THREAD

**Issue by davidhund** [bdkjones/CodeKit-1-Old#236]
I just tried adding a Framework that is also a Project. This threw a notice with a Help button. This button links to http://incident57.com/codekit/help but should link to http://incident57.com/codekit/help.php#navRibbon

Actually, adding a proper redirect from http://incident57.com/codekit/help would probably be a good thing ;)

**Comment by bdkjones** [comment]
Good catch. Fixed in 5443.
