### ISSUE TITLE
Crash: Optimize Images and 0-byte .jpg files

### ISSUE THREAD

**Issue by StevenBlack** [bdkjones/CodeKit-1-Old#237]
Hi Bryan,

I've just generated three or four automated crash reports while trying to optimize a folder of images, and subsequently smaller groups of images, zeroing-in on the problem file.

Turns out: a jpg with size 0-bytes crashes CodeKit while optimizing images.

Certainly this is an edge-case, but you may like to be aware of this and perhaps defensively test for this.

Great Product, good work man!

**Comment by bdkjones** [comment]
Can you send me a couple of the images that produce the crash?

**Comment by bdkjones** [comment]
So... any zero-byte images floating around?

**Comment by StevenBlack** [comment]
Hi Brian,

I have a zero-byte image.  I suspect the mail system might reject or mangle it 
so I've zipped it with another image because we don't want the zip file to 
edge-case on us either.

To crash Codekit, select several images including the zero-byte one, then hit 
optimize.  Boom.

I fricken LOVE Codekit Brian.  I hope it makes you rich.  Don't lowball the price.

bdkjones wrote:

**Comment by bdkjones** [comment]
Sweet, except I didn't see a link or an attachment

**Comment by StevenBlack** [comment]
I just checked and there was definitely a file named twoImages.zip attached to 
my last email.

Here it is again.

To create the image I used to crash Codekit again, I created an empty file and 
gave it a .jpg extension.  I crash Codekit when this file is among several .jpg 
files to be optimized together.

bdkjones wrote:

**Comment by StevenBlack** [comment]
Sorry just realizing now that I was replying by email and you are reading this here.

To create the zero-byte image, I created an empty file and gave it a .jpg extension.

**Comment by bdkjones** [comment]
How, exactly, did you "create an empty file"? 

If I go into photoshop and create a new image with absolutely nothing in it, then save it, I still get an image file that's bigger than 0 bytes.

**Comment by StevenBlack** [comment]
Several ways to create an empty .jpg

Possibly the easiest generically is, In terminal:  `touch foo.jpg` creates a new zero-byte file named `foo.jpg`.

**Comment by bdkjones** [comment]
Well, yea... but that's not really a jpg. How did you come across this issue in daily use? In other words, how would a web designer end up with a zero-byte "image" file?

**Comment by StevenBlack** [comment]
How can a zero-byte file be anything other than a what it purports to be?

I don't know how I have a zero-byte file with a .jpg extension.  A failed download perhaps?  It happens.

The point is, it hard-crashes CodeKit with no indication why.  

In my case, with several hundred images in a folder, it took quite awhile to isolate the problem.   

I wasn't sure if it was a bad resource, or had I busted some limit within CodeKit itself?  Codekit was not helpful because it seemed to be optimizing images in a sequence that didn't reflect my images viewpane.  Green checkmarks appearing randomly here and there.  

CodeKit's liberal use of vertical space is not helpful here. It limits what we can see being processed.

Here's the point:  Anyone who uses CodeKit is doing-so on a quasi mission-critical basis.  That cuts both ways for both you and your users.

So there are two issues here.

1)  A zero byte file is obviously (in hindsight) a bad file and a preventable edge-case.

2) Codekit isn't good at telling us what it's doing when it goes off, zones-out as it often does, in a batch process.  If CodeKit crashes in a batch operation, users can count on being down for awhile because, as far as I can tell, there are no logs.  It's hit and miss to fix problems like this.

Sensible?

**Comment by StevenBlack** [comment]
You aren't dividing by zero when calculating optimization stats, are you?  A zero-byte file is already optimized :-)

**Comment by bdkjones** [comment]
I agree that nothing should crash the app, and I will certainly fix this issue. My question was intended to help me understand where the zero-byte file came from so that I could get some context on the situation, not to insinuate that the issue does not need attention.

The reason the app optimizes images in an apparent random order is simple: it dispatches optimizations simultaneously based on how many cores your computer has, how much of those cores are free, etc. Right now, the app will run two optimizations per core at the same time. On a Core i7, that's 8 images optimizing simultaneously. It doesn't matter what order we do it in. 

If an optimization fails, the app provides an error message in the log. Otherwise, there's no need to log success messages.

**Comment by bdkjones** [comment]
That is indeed the issue. Check added, bug fixed. Thanks!

**Comment by StevenBlack** [comment]
Interesting.  Thanks for the clarification.

For my own information, still fairly new to OSX, where's the log kept?
