### ISSUE TITLE
Fails to compile with properly quoted MS filter string

### ISSUE THREAD

**Issue by Digitalsabre** [bdkjones/CodeKit-1-Old#238]
Have read the docs.  less fails to compile with a MS filter when properly quoted or when properly quoted _and_ prefixed (per docs) with a tilde (~).

Both of the following lines will fail.
`filter: "progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=scale, src='img/50p_white.png')";`
`filter: ~"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=scale, src='img/50p_white.png')";`

**Comment by bdkjones** [comment]
This is not an issue with CodeKit. You'll need to open a bug report on the Less.js GitHub page.
