### ISSUE TITLE
How can I get this to work with Cakephp ctp files?

### ISSUE THREAD

**Issue by Forbin** [bdkjones/CodeKit-1-Old#242]
Is there a way to get CodeKit to compile to .ctp rather than html, AND can it work with PHPHAML or phaml so that php is shortened as well?

**Comment by bdkjones** [comment]
Support for custom file extensions recognized as webpages added in build 5867.

**Comment by Forbin** [comment]
Fantastic news! How do I get the latest build? The beta build is 5380.

Cheers, John Petit

tel: (970) 369 0558
skype: jpetit7
