### ISSUE TITLE
ParseError on textarea { width: 150px; }

### ISSUE THREAD

**Issue by lucasRolff** [bdkjones/CodeKit-1-Old#243]
Hi,

I was sitting here developing, and I'm using CodeKit because I think it's really awesome!

But getting this ParseError on:

```
textarea {
    margin: 0;
}
```

Does anyone know what's wrong doing that?

**Comment by bdkjones** [comment]
What language are you developing in?

**Comment by lucasRolff** [comment]
Update: LESS

**Comment by bdkjones** [comment]
My advice is to create a new file from scratch. It's likely that something is corrupted in your original one. This is not a CodeKit issue, though; this would need to be opened on the Less.js page.

**Comment by lucasRolff** [comment]
Hmm I see I will make a ticket on the less.js then, because the document I made, it was like one of the very first styles I made.

Thank you!
