### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by sammdec** [bdkjones/CodeKit-1-Old#248]
I have added a project folder that has css in a sub folder, is there an obvious reason why it is not pulling it into the project?

**Comment by bdkjones** [comment]
CodeKit does not do anything with CSS files. Use Less, Sass or Stylus.

-Bryan

**Comment by davidjdixon** [comment]
It should be noted that a CSS file _is_ also a valid less/sass/stylus file. To have it work correctly with includes, just rename is with a .less (etc) extension.
