### ISSUE TITLE
Codeigniter Log Files (Probably other Frameworks)

### ISSUE THREAD

**Issue by Leenug** [bdkjones/CodeKit-1-Old#249]
Hi, 

Firstly thanks, been a user of both your Less preprocessor and codekit for a while now.

I believes its a known issue that when logfiles are updated it throws codekit's auto refresh feature into an infinite loop. Would it be possible to add a global setting to codekit whereby we can specify a file name pattern that codekit should ignore when refreshing the browser?

Cheers, 
Lee

**Comment by jrschumacher** [comment]
Did you try adding *.log in the skipped files under preferences?

**Comment by Leenug** [comment]
The CI log filenames are: log-{date}.php adding log-\* to the skipped files doesn't seem to remedy this.

**Comment by bdkjones** [comment]
Can you not set CI to spit out log files in a certain folder and then simply add that folder name to the skipped items list?

It's not really possible to do a pattern match for "log-[date].php" for two reasons:

1) The date format varies by region. Is it 12/1/2012 or 1/12/2012?
2) RegEx isn't natively available in lower-level languages and tends to be slow.

**Comment by jrschumacher** [comment]
What about filtering by directory? CI uses /log by default.

On Wed, Mar 7, 2012 at 2:06 PM, bdkjones <
reply@reply.github.com

**Comment by bdkjones** [comment]
Perfect. That's gonna be the solution. I will update the help page with this advice for other users.
