### ISSUE TITLE
Mixin called .border-radius adds spurious code

### ISSUE THREAD

**Issue by nathanpitman** [bdkjones/CodeKit-1-Old#253]
If I create a mixin called .border-radius and use it to generate 'any' kind of output:

```.border-radius(@something) {
    background-color: @something;
    }

``````

 CodeKit parses it just fine but appears to add two lines of unwanted code:

```-moz-border-radius: "something";
  border-radius: "something";
``````

As a workaround I've changed my function to be called .rounded_custom instead, with that the problem vanishes.

**Comment by greystate** [comment]
It's very unlikely that CodeKit is adding those lines - more likely that you have multiple definitions of that Mixin - are you referencing a Framework that's got it's own definition of `.border-radius` by any chance?

**Comment by bdkjones** [comment]
This is definitely not a CodeKit issue. It's either a mistake in the source stylesheets as greystate pointed out, or an issue with Less.js itself.

**Comment by fabiozc** [comment]
probabily u are referecing the twitter bootstraps that have .border-radius property.

**Comment by nathanpitman** [comment]
Ok, thanks for the pointers. I'll take another look at it but I suspect you're all right and it's a case of user error! :) Thanks!
