### ISSUE TITLE
Reorder Projects in Sidebar

### ISSUE THREAD

**Issue by iansoper** [bdkjones/CodeKit-1-Old#254]
I would like to be able to reorder projects or frameworks in the sidebar, right now It appears that I can't do that.

**Comment by edwardsdesign** [comment]
I second this request. This could allow the user to group them by client, company or some other unique arrangement.

Thanks for he hard work and care with this app, it has become an essential part of my workflow.

**Comment by davidjdixon** [comment]
+1

Additionally, it would be useful to group projects together in some fashion to allow (for example) sorting projects according to client, or technology etc

**Comment by ialphan** [comment]
+1

I would like this as well (grouping/ordering).

**Comment by bdkjones** [comment]
Implemented in 2.0.
