### ISSUE TITLE
Issue(s) with Twitter Bootstrap

### ISSUE THREAD

**Issue by davidhund** [bdkjones/CodeKit-1-Old#255]
I have just cloned the latest Twitter Bootstrap (Mon Mar 12 14:09:38 2012 -0700) and have downloaded the latest CodeKit (1.0 5380) with Less version 1.2.1

I am running into various issues where Less is not compiling my Bootstrap.

My current folder setup is:

```
project/[...]/
project/static/less/bootstrap/less/*.less ( all Bootstrap less files )
project/static/less/my-project.less ( @imports "bootstrap/less/bootstrap.less" )
project/static/css/my-project.css ( output CSS )
```

When compiling CodeKit throws the following warning:

```
TypeError: Cannot call method 'charAt' of undefined
    at getLocation (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:212:34)
    at new LessError (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:221:19)
    at Object.toCSS (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:381:31)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/bin/lessc:102:28
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:430:40
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:94:48
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/index.js:115:15
    at Object.parse (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:432:17)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/index.js:114:14
    at [object Object].<anonymous> (fs.js:107:5)
```

This error, I _think_ relates to https://github.com/cloudhead/less.js/issues/592

However: when I move _my project .less file_ _into_ the `bootstrap/less/` folder I get a different error:

```
NameError: #grid > .core is undefined in /Users/davidhund/Dropbox/_dave/_vs/_projects/sherpazz/sherpazz.com/htdocs-
bootstrap/static/less/bootstrap/less/grid.less:2:0
1 // Fixed (940px)
2 #grid > .core(@gridColumnWidth, @gridGutterWidth);
3 [0m
```

This, I _think_ , relates to https://github.com/twitter/bootstrap/issues/2516#issuecomment-4441645

NOTE: compiling through `lessc` gives the same error.

The conclusion with that last issue seems to be that Bootstrap 2.0.2 (WIP) requires Less 1.3.0.

So: I run into at least 2 different issues trying to compile Bootstrap with Less (CodeKit)
- Some import error when my project's .less file lives a folder up from Bootstrap less
- Some compile error with Bootstrap's code and Less < 1.3.0

I appreciate these are not CodeKit errors but I wonder:
- Are these issues with Bootstrap familiar/known?
- Is there any way for me to easily update the Less version CodeKit uses?

Thx.

**Comment by bdkjones** [comment]
This will be solved in the release coming later this week, which includes Less.js 1.3.0.

**Comment by alampros** [comment]
@davidhund nice sleuth work tracking down the source of this error. Helped me a lot – thanks!

**Comment by davidhund** [comment]
@alampros n.p. It cause(s|d) me a bit of a headache. The LESS `charAt TypeErrors` are unhelpful to say the least ;)

I wonder @bdkjones if these were simply Less.js < 1.3.0 issues and I also wonder if there's any way for us to manually change the Less version CodeKit uses?

**Comment by netatoo** [comment]
For update LESS manually on CodeKit, go to /CodeKit.app/contents/resources/engines/less. Work for me.

**Comment by TechRemarker** [comment]
@netatoo was hoping for a manual fix for this until a new version is released. Thanks for the find!

**Comment by martylouis** [comment]
@netatoo This worked perfect for me too. Thanks.

**Comment by bentographics** [comment]
Run into the same issue.

Sorry, again for dummies:
- Where do you download the new LESS version?
- Which files do you replace exactly (parser.js)?

Thanks for any hints.
