### ISSUE TITLE
Stylesheets directory not being recognized

### ISSUE THREAD

**Issue by JJSIII** [bdkjones/CodeKit-1-Old#257]
I keep my .css in a folder named 'css' and Codekit isn't recognizing that folder at all. Under the 'Styles' pane in CK the list is completely empty.

**Comment by bdkjones** [comment]
CodeKit does nothing with CSS files. Use less, sass or stylus.

**Comment by JJSIII** [comment]
Oh. Duh. Thanks. I thought it would minify like it does .js.
