### ISSUE TITLE
Nondescript error message

### ISSUE THREAD

**Issue by rizqidjamaluddin** [bdkjones/CodeKit-1-Old#259]
Today, while trying to upgrade my Bootstrap library framework, I immediately got a slew of error messages. I've tried fiddling into the files and commenting out lines, but while I can figure out the point where it breaks, the error message doesn't show why it does so.

This is the error message:

```
TypeError: Cannot call method 'charAt' of undefined
    at getLocation (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:212:34)
    at new LessError (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:221:19)
    at Object.toCSS (/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:381:31)
    at /Applications/CodeKit.app/Contents/Resources/engines/less/bin/lessc:102:28
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:430:40
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:94:48
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/index.js:115:15
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:430:40
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:94:48
    at /Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/index.js:115:15
(This action was triggered by a change to bootstrap.less)
```

I'm not sure where the error actually lies; all I did was paste over new bootstrap's files over the old one, and I imagine that might be the cause. In either case, it'd be a good idea to make the error messages clearer.

I'm running build 5380.

**Comment by bdkjones** [comment]
The latest version of Bootstrap requires Less 1.3+. Build 5380 of CodeKit includes Less 1.2. Hence the problem.

The app will be updated in the next day or two.

-Bryan

**Comment by rizqidjamaluddin** [comment]
And 15 seconds right before I worked out that the issue was this syntax:

```
(~".span@{index}") { .span(@index); }
```

Seems to be one of them typical bootstrap mangled wizardry that makes no sense to the unaided eye.

Thanks the the quick reply. Looking forward to it!

**Comment by bdkjones** [comment]
The error messages are generated by the tools themselves, not by CodeKit. What you see above is exactly what you would see in the Terminal if you ran lessc from there. 

I do implement some of my own error messages for various things, but they are all very clear and helpful. The ones I get from the tools, however, I can't do anything about.
