### ISSUE TITLE
Can't hide files via extension

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#26]
I'd like to be able to hide files using using *.php or *.html in preferences.

**Comment by bdkjones** [comment]
An oldie but a goodie. 

The auto-hide and auto-ignore tables have been removed in build 5124. In their place is a new "skipped items" table. You can add filenames, folder names, and extensions (via *.js or *.php) to this table. CodeKit will completely skip the listed items when it scans for new files --- both during a refresh and when adding a new project.

It will not remove EXISTING files that are already in the app, but it won't add any new ones that match your specified criteria.

The advantage here is that you're not using any of the 10,000 file descriptors to watch these files. Previously, when you added items to the auto-hide or auto-ignore list, they still got added to the app and watched just like every other file; CodeKit simply didn't do anything when they changed. Now, those files aren't even tracked by the app, which means they don't eat into your total 10,000 file limit.

**Comment by bdkjones** [comment]
I have been working on downplaying the "hide" functionality. I originally added it because I didn't want to see the 20 javascript files associated with Shadowbox.js. I think the "skip" feature is a better approach.
