### ISSUE TITLE
CSS import Google Web Font - Error

### ISSUE THREAD

**Issue by chadsaun** [bdkjones/CodeKit-1-Old#260]
When I use this statement to import a Google Web font I get the below error.

@import url(http://fonts.googleapis.com/css?family=Maven+Pro:400,500,700);

```
SyntaxError: expected ')' got ',' in /Users/chad/Sites/retail2/lib/less/main.less:1:64
1 @import url(http://fonts.googleapis.com/css?family=Maven+Pro:400,500,700);
2 [0m
```

**Comment by bdkjones** [comment]
1) This is not an issue with CodeKit. It's an issue with Less.js.

2) I believe you can solve it by using quotes inside the brackets: @import URL("http://bigassURL/"); try that.
