### ISSUE TITLE
On a Safari CSS auto-refresh, linked CSS media types attributes get deleted.

### ISSUE THREAD

**Issue by NathanBowers** [bdkjones/CodeKit-1-Old#261]
In my HTML I've got:

``` html
<link href="screen.css" media="screen" rel="stylesheet">
<link href="print.css" media="print" rel="stylesheet">
```

When I save an .scss file CodeKite refreshes Safari and the media types get cut off in the DOM, and I end up with:

``` html
<link href="screen.css" rel="stylesheet">
<link href="print.css" rel="stylesheet">
```

So the print and screen styles _both_ render. My workaround for now is to remove print.css during testing.

I'm loving CodeKit otherwise! :-)

**Comment by bdkjones** [comment]
Already fixed. Will be in next release.
