### ISSUE TITLE
Feature Request: Opt-in/Out of Frameworks

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit-1-Old#264]
I have run into a few instances where some Framework naming conventions are overlapping and it is causing me to duplicate code in my projects to override global framework names. I can only imagine this becoming more of an issue as I start recommending CK into the workflow of my clients / peers. As one can imagine this could become a cluster very fast seeing that one client might want to maintain a framework with in house developers that I need to keep in sync along with some other clients with the same scenario.

To help relieve this very real situation for freelance / contract developers I would like to request the ability to opt-in/out of frameworks on a project level vs the all or none approach that is currently applied.

Thanks for listening.

**Comment by bdkjones** [comment]
Implemented in 2.0.
