### ISSUE TITLE
Compass Frameworks: Broken

### ISSUE THREAD

**Issue by kennonb** [bdkjones/CodeKit-1-Old#265]
I've gone round and round with this and I believe this is a CodeKit issue, which is why I'm submitting this issue.

I realize that CodeKit doesn't allow Frameworks from CodeKit to be used within Compass. You have to specify the framework files within Compass config.rb. So I created a framework folder in the root of my local Sites. I then call it in the config.rb file. This should then allow those files to be imported within Compass files. This doesn't work in CodeKit. It throws an error that the file can't be found.

I thought maybe it was just me, but this works just fine using the command line, or LiveReload, so I believe this is a CodeKit bug.

Does CodeKit pull from a different directory possibly and that's causing the issue?

Let me know what I can submit to help out here.

**Comment by bdkjones** [comment]
Did you specify the full, root-relative path to the Compass extension in the config file?

**Comment by kennonb** [comment]
Wow.. I'm a moron. Thanks that seems to work now. :)
