### ISSUE TITLE
Chrome goes first plan when saving project file

### ISSUE THREAD

**Issue by zanona** [bdkjones/CodeKit-1-Old#266]
After installing v1.0 (5943) I've noticed that when saving a project file such html or js Chrome then pops up in the first plan hiding all the other windows which were active beforehand. I've noticed this when deciding to make some cross-browsing tests on my project and had opera and firefox opened or any other finder windows...for each save, Chrome popped up and I had to go and hide it manually. although it didn't happen before this update.

Can you replicate it?

**Comment by bdkjones** [comment]
I have replicated this over here.

The short answer is that I have no idea why Chrome is doing this; I have not coded that behavior. I have noticed that it only occurs if "injection reloading" is OFF. Can you confirm that on your end?

**Comment by doginthehat** [comment]
It happens for me as well, with injection _ON_.

It also seems to now and then stubbornly pick the wrong tab.

**Comment by zanona** [comment]
yes, injection for me is ON as well.
