### ISSUE TITLE
Faulty imports in LESS

### ISSUE THREAD

**Issue by botteu** [bdkjones/CodeKit-1-Old#269]
We have a problem where CodeKit won't compile imported LESS-files. The code below would work in the previous version of CodeKit, but in the latest version it acts as if it can't find the mix-ins in an imported file.

This is the content of Main.less:

@import "globalMixins.less";
@import "reset.less";
@import "global.less";
@import "customContent.less";
@import "temporaryPage.less";
@import "mediaQueries.less";

Won't compile and throws this error (worked with previous version of CodeKit):

RuntimeError: No matching definition was found for `.text-shadow(#ffffff, 1px, 1px, 0)` in /Users/pathwayExcluded/less/global.less:92:1
91  color: @headlineGray; 
92  .text-shadow( #fff, 1px, 1px, 0 );
93  line-height: 1.2em;[0m

It seems like the compiler can't parse what's in globalMixins.less (since that's where .text-shadow() is defined)

**Comment by bdkjones** [comment]
Hi Daniel,

```
I've had many reports of problems like this one. The issue is the parameters in the mixin --- Less 1.3.0 is throwing errors on parametric mixins that previously worked fine. 

Another user was able to resolve this problem by using the syntax described here: https://github.com/cloudhead/less.js/issues/305

Alexis, I've copied you on this email so you're aware that this is tripping up a lot of people. I keep seeing emails about it. 
```

-Bryan

**Comment by bdkjones** [comment]
This isn't a CodeKit issue; it's an issue with Less.js itself. Therefore, closed.

**Comment by botteu** [comment]
Thanks for the help!

/D

**Comment by bdkjones** [comment]
Yea, mixin behaviour has changed in 1.3.0 in a breaking way.

If you want the bahviour of .foo () {}   you have to do:  .foo(...) {}

Cheers

**Comment by botteu** [comment]
This solved my problem! Thanks a million. 

And keep up the good work. I know it'll be a day one purchase of CodeKit from our company.

Cheers
