### ISSUE TITLE
Performance issue with live reloading Safari

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit-1-Old#271]
I've had to turn off the "Inject CSS changes without a full reload" setting in the latest two builds (5943 + the one just before) because Safari would grind to a halt when I'd done about 10 or so little tweaks.

In Activity Monitor, the "Safari Web Content" process quickly grows to ~ 1.7GB and a simple margin change can take 5 or six seconds to actually happen in the browser after the CodeKit Growl notification has disappeared.

When I uncheck the box and let Safari reload after save there's no problems - and thhe process stays below ~200MB.

I'm using LESS, editing in TextMate, running the webpage as a flat HTML file in the public directory of a simple Pow server (http://pow.cx) setup. 

Everything worked awesomely cool in Beta 9 - but I can't go back, since it's expired... (sad trombone)

**Comment by bdkjones** [comment]
Are there any external CSS files in the page you're reloading? (that is, CSS files not local to the project itself.)

Can you send me the project (stripped down) that demonstrates the issue so I can test it over here?

**Comment by greystate** [comment]
Aah - yes, I'm using fonts from Typekit, so there's a typekit JavaScript file that injects a stylesheet and a couple of webfonts. I just tried to disable that and that's **definitely** the culprit.

Do you still want the project, or is this enough for scrutinizing?

**Comment by jonikorpi** [comment]
I'm getting the same issue. For me the "Safari Web Content" process also starts using >90% CPU.

I'm using external CSS too, but from Fontdeck instead of Typekit. It uses a plain CSS file filled with @font-face declarations instead of an injecting JavaScript file.

**Comment by bdkjones** [comment]
Please upgrade to build 5987 and let me know if this issue persists.

**Comment by greystate** [comment]
Confirmed - build 5987 has fixed this for me. Thanks!

**Comment by minimaldesign** [comment]
Getting the same problem. No external fonts, but using boilerplate so I got //ajax.googleapis.com/ajax/libs/jquery/etc... script tag in my footer. I haven't checked activity monitor but Safari gets stuck to the point it can't reload. If I got to Safari and hit reload, it asks me if I want to do a force reload and if I do, everything goes back to normal until I start making multiple small CSS changes in row...

OS X 10.7.3 + CK 1.0 (6010) - Working with SCSS files and straight up javascript (compiled + minified)

Thanks!

**Comment by bdkjones** [comment]
Please email me the project that's showing this issue so I can debug it.

**Comment by minimaldesign** [comment]
It's not project specific though, but I can send you one for you to check
out if you want... Which email should I send this to? I'm must be retarded
but I don't see how you email someone directly from github.

Thanks!

On Sun, Apr 8, 2012 at 11:48 AM, bdkjones <
reply@reply.github.com
