### ISSUE TITLE
LESS generates error after update to version 1.0 (5943)

### ISSUE THREAD

**Issue by leaase** [bdkjones/CodeKit-1-Old#272]
After update to the latest beta version of CodeKit there is a compile error when I try to save my main LESS file. It no longer finds the mixin I use to generate a box shadow:

RuntimeError: No matching definition was found for `.box-shadow()` in /Users/leaase/Sites/Somesite/less/style.less:82:2
81      text-align:center;
82      .box-shadow(@shadow);
83      margin:auto;[0m

I used Time Machine to restore the previous version of CodeKit and then it compiles just as it should.

The .box-shadow() mixin is fetched from a framework file and imported to the style.less file like this: @import "css3.less";

Am I the only one experiencing this?

**Comment by bdkjones** [comment]
CodeKit Beta 10 includes Less.js 1.3.0. 

Less 1.3 brings a new syntax for mixins with parameters. See the lesscss.org website for more information, or the GitHub page for Less.js. 

The short answer is that you need to change your code; there's nothing wrong with CodeKit or with Less.
