### ISSUE TITLE
Feature Request: Live Reload on multiple devices

### ISSUE THREAD

**Issue by TuckerWhitehouse** [bdkjones/CodeKit-1-Old#274]
The actual live reload (http://livereload.com/) has the ability to reload the web page and inject new styles on the fly across a multitude of devices, including mobile devices such as the iPad and iPhone. It would be cool if you could somehow incorporate this into CodeKit, but I understand it may not be possible where you have offloaded this process off of the main thread, in addition to doing it without injecting any scripts into the web page.

**Comment by bdkjones** [comment]
This is definitely something I want to do.

However, I want to do it cleanly and magically and I'm still working on finding a way to do that.

**Comment by bdkjones** [comment]
Implemented in 2.0. And dear holy god is it magical.
