### ISSUE TITLE
newest forced update refuses to start

### ISSUE THREAD

**Issue by sygint** [bdkjones/CodeKit-1-Old#275]
i installed the newest beta because after it hung mid process last night and i was forced to quit it this morning and update to the new one

i promptly did so and now it doesn't even start up, i'm dead in the water as i was relying alot on the ability to concatenate my javascript files

**Comment by sygint** [comment]
calling this a duplicate, please fix this asap

**Comment by bdkjones** [comment]
Quit the app, the restart it while holding down shift.

-Bryan

**Comment by greystate** [comment]
(See #276)
