### ISSUE TITLE
5977 Failure to Launch

### ISSUE THREAD

**Issue by atEverychance** [bdkjones/CodeKit-1-Old#276]
Just downloaded/installed the new Codekit, always an exciting time!

However, today's build 5977 fails to launch. When I try via command line:

dyld: Library not loaded: @executable_path/../Frameworks/Growl.framework/Versions/A/Growl
  Referenced from: /Applications/./CodeKit.app/Contents/MacOS/CodeKit
  Reason: image not found
Trace/BPT trap: 5

Help, thanks.

**Comment by greystate** [comment]
Me too - reverted to the previous

**Comment by alampros** [comment]
Any chance you could post the previous build archive? Like an idiot I trashed it (/facepalm).

**Comment by sygint** [comment]
the previous copy tells you you must download the new one or quit, how did you sucessfully revert? this is ruining my day

**Comment by greystate** [comment]
Here's the build 5943 that works for me: http://dl.dropbox.com/u/170259/codekit-beta10.zip

(Though I bet @bdkjones will post a new build shortly - what is it? All of 15 minutes since it broke :-)

**Comment by alampros** [comment]
@greystate you, sir, are awesome. Thanks!

**Comment by bdkjones** [comment]
Issue resolved. Something got corrupted when I uploaded the zipped file to the server. 

Try downloading it again.
