### ISSUE TITLE
Feature Request: Happy funtime messages

### ISSUE THREAD

**Issue by hawkz** [bdkjones/CodeKit-1-Old#278]
I would like to be praised when my markup is successfully validated:
"Don't growl at me, big me up!"

E.g. Instead of "Success: Compiled blah.less"  
show me "You're awesome today! Another perfect compile"
show me "Well done sir! It's a pleasure compiling for you"

you get the idea..

It's been a long day :)

**Comment by TuckerWhitehouse** [comment]
+1

Kinda like when checking for updates and your on the latest version, the button isn't some plain "Close", it says "Awesome" :) Just adds a little character to the app.

Google Chrome had a dialog that appeared when you hadn't updated in a while that started out "Old school's not cool."

**Comment by JimmyRittenborg** [comment]
+1 

Bryan is so full of funny stuff to say, it actually makes you wanna read all the text on his website, FAQ etc. EVEN the freakin' ..and i quote "lawyer nonsense" when placing the order! (:

**Comment by bdkjones** [comment]
Thanks guys, I'll keep this in mind for the future.
