### ISSUE TITLE
Latest release - Version 1.0 (5987) - will not launch

### ISSUE THREAD

**Issue by chadclark** [bdkjones/CodeKit-1-Old#279]
Hello,

After being prompted on launch to update to the latest version, CodeKit will no longer launch. I tried everything I could think of including starting the app holding down shift, trashing the prefs, deleting the app and re-downloading from the site. No luck. I even had a friend send me the release right before 5987, but that will not launch either.

I have repaired disk permissions, checked permissions on the actual app, no luck.

Any ideas on why this is happening and how I can remedy? Thanks.

**Comment by chadclark** [comment]
Trying to launch from command line produces this error:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/CodeKit.app.
```

**Comment by chadclark** [comment]
And from System.log

```
Mar 22 12:01:32 iMac com.apple.launchd.peruser.501[507] ([0x0-0x3f03f].com.incident57.CodeKit[743]): posix_spawn("/Applications/CodeKit.app/Contents/MacOS/CodeKit", ...): Operation not permitted
Mar 22 12:01:32 iMac com.apple.launchd.peruser.501[507] ([0x0-0x3f03f].com.incident57.CodeKit[743]): Exited with code: 1
```

**Comment by jiserra** [comment]
I have this issue too, but if I launch it from the command line, nothing happens. I checked system.log and it points me to this crash.log file:

```
Process:         CodeKit [10303]
Path:            /Applications/CodeKit.app/Contents/MacOS/CodeKit
Identifier:      com.incident57.CodeKit
Version:         1.0 (5977)
Code Type:       X86-64 (Native)
Parent Process:  launchd [386]

Date/Time:       2012-03-22 14:36:21.108 -0300
OS Version:      Mac OS X 10.7.3 (11D50)
Report Version:  9

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/Growl.framework/Versions/A/Growl
  Referenced from: /Applications/CodeKit.app/Contents/MacOS/CodeKit
  Reason: image not found

Binary Images:
       0x104400000 -        0x104499ff7 +com.incident57.CodeKit (1.0 - 5977) <5E572C54-AB04-3B28-9285-220DE052C1C3> /Applications/CodeKit.app/Contents/MacOS/CodeKit
    0x7fff64000000 -     0x7fff64034baf  dyld (195.6 - ???) <0CD1B35B-A28F-32DA-B72E-452EAD609613> /usr/lib/dyld
    0x7fff85ae6000 -     0x7fff85ae6fff  com.apple.Cocoa (6.6 - ???) <9E3D4787-A2CE-38E0-BEF8-E5DA63B6E6A1> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff86047000 -     0x7fff86047fff  com.apple.Carbon (153 - 153) <E37A515C-4C10-3102-8146-C0FBD458F8CF> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff890ed000 -     0x7fff89149ff7  com.apple.QuickLookFramework (3.1 - 500.10) <35BF320E-26F5-310C-9FA9-D60919B218EC> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff8a28f000 -     0x7fff8a2abfff  com.apple.ScriptingBridge (1.2.1 - ???) <3E99B861-E011-3594-A9C4-E39B7EFE2F3F> /System/Library/Frameworks/ScriptingBridge.framework/Versions/A/ScriptingBridge
    0x7fff8ba4f000 -     0x7fff8ba4ffff  com.apple.quartzframework (1.5 - 1.5) <A7A2DBBA-BFFC-35C0-A927-CC0BA4C851E7> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff8ba7c000 -     0x7fff8ba7cfff  com.apple.CoreServices (53 - 53) <043C8026-8EDD-3241-B090-F589E24062EF> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff8e05c000 -     0x7fff8e2e7fff  com.apple.JavaScriptCore (7534.53 - 7534.53.8) <619D6392-D833-3C55-B1C0-4DAA0477796C> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
```

**Comment by bdkjones** [comment]
Jiserra --- Please go to http://incident57.com/codekit/download.php and re-download CodeKit. The build 5977 was corrupted when I uploaded it to the server. I corrected that yesterday and if you re-download you should be good to go.

Chad --- That is really weird. I haven't had reports from anyone else that build 5987 fails to launch. I also downloaded it from the site and tested it myself just now and it's working correctly. To begin diagnosing this, do you have another machine that you can attempt to run the latest build on? If so, please give that a go. If not, try creating a new user account on your Mac and attempting to download and run the app from that user account. Let me know if that works and we can figure out what's going on.

**Comment by chadclark** [comment]
Luckily I had access to a different machine. I downloaded and ran it successfully. I copied the app over to the machine I was having issues with, and I can now run the app. Definitely a very weird issue. I will let you know if anything else pops up.

**Comment by jiserra** [comment]
Thanks, re downloading solved the issue :)

**Comment by bdkjones** [comment]
Very weird. The only explanation I can see is that when you downloaded the app on your primary machine, the cache in the browser was still delivering the old, corrupted file. 

Clearing the browser cache should do the trick.
