### ISSUE TITLE
Less output is not minified

### ISSUE THREAD

**Issue by ginghamsburg** [bdkjones/CodeKit-1-Old#281]
The CSS output file from a LESS source isn't coming out compressed or minified. Comments are left in and the CSS is spread out over multiple lines. Using build 5987.

**Comment by bdkjones** [comment]
I just tested this over here. All three output styles are working for LESS files in build 5987. 

Are you sure you've selected the minified or compressed option for the Less file you're compiling?

**Comment by ginghamsburg** [comment]
I have tried both with no results.
[cid:EAD7FD90-3786-431F-AC0B-B029DF0379AA]

Odd. FWIW, I've attached the output CSS file.

Take care,

## Chris

Christopher W. Boerger
Web Developer
Ginghamsburg Church
937.667.1069 x297
http://www.ginghamsburg.org

On 3/22/12 2:47 PM, "bdkjones" <reply@reply.github.com<mailto:reply@reply.github.com>> wrote:

I just tested this over here. All three output styles are working for LESS files in build 5987.

Are you sure you've selected the minified or compressed option for the Less file you're compiling?

---

**Comment by bdkjones** [comment]
Please send me the LESS file that's showing the issue.

**Comment by ginghamsburg** [comment]
Here you go.

Take care,

## Chris

Christopher W. Boerger
Web Developer
Ginghamsburg Church
937.667.1069 x297
http://www.ginghamsburg.org

On 3/23/12 2:02 AM, "bdkjones"
<reply+i-3768476-24870aabe46344ca2232ee59aa8de5894de2b410-1108177@reply.git
hub.com> wrote:

**Comment by ginghamsburg** [comment]
Just curious, I'm running build 6010 and still have the problem of the CSS output file not being minified. Is there perhaps some external library or binary that CodeKit relies upon? I use MacPorts and my path looks in MacPorts first before using the default system locations.

Have you been able to minify the output from the LESS file I sent?

**Comment by bdkjones** [comment]
Hi guys,

Please upgrade to build 6502 (version 1.2.2). I've tested and confirmed that the Less output styles work correctly on that build.
