### ISSUE TITLE
Coffeescript not compiling correctly

### ISSUE THREAD

**Issue by charliemagee** [bdkjones/CodeKit-1-Old#284]
Thanks for Codekit. It's great.

Just updated to 5987. Lion 10.7.3. Using Sublime Text 2, Codekit, Chrome, MAMP Pro.

The first two lines are compiling to correct Javascript. The next two don't. All spacing is the same, variables are declared correctly in code above. moodSummary is an array that I'm pushing localStorage items into but only when they're not null.

These same lines compile fine at js2coffee.org

CS:
  moodSummary.push amConfused  if localStorage.getItem("moodconfused") isnt null
  moodSummary.push amStressed  if localStorage.getItem("moodstressed") isnt null
  moodSummary.push amSad  if localStorage.getItem("moodsad") isnt null
  moodSummary.push amWorried  if localStorage.getItem("moodworried") isnt null

Compiled JS:
    if (localStorage.getItem("moodconfused") !== null) {
      moodSummary.push(amConfused);
    }
    if (localStorage.getItem("moodstressed") !== null) {
      moodSummary.push(amStressed);
    }
    if (localStorage.getItem("moodsad") !== null) moodSummary.push(amSad);
    if (localStorage.getItem("moodworried") !== null) moodSummary.push(amWorried);

The Codekit log beeps and says it compile and saved, but didn't pass JSHint. Problem: Expected '{' and instead saw 'moodSummary'.

Any ideas?

Thanks again,

Charlie Magee

**Comment by bdkjones** [comment]
Please use the very latest version of CoffeeScript from the GitHub page. 

Run the command line executable to compile the file and see if it produces the same results. Thanks!

**Comment by charliemagee** [comment]
Already using current version of CoffeeScript.

Running the command line compile gives me the same results, so it must be something in my code. It runs fine, but I get jsHint errors. Sorry to have bothered you. I'll do a double-check that way in the future.
