### ISSUE TITLE
App will not start

### ISSUE THREAD

**Issue by exquisiteOntologist** [bdkjones/CodeKit-1-Old#285]
I have reinstalled your application 3 times today after the previous version expired. Will not even attempt to run. Thanks for a great application, I will buy it when you start to selling it.

**Comment by bdkjones** [comment]
Clear your browser's cache, then re-download the app from the website.

Hold down shift while you launch the app.

**Comment by exquisiteOntologist** [comment]
Thanks for the reply. That solution doesn't solve the problem. I don't need it solved for myself, just letting you know.

**Comment by ghost** [comment]
Cannot get the app to start either. Was given the message that the previous beta had expired, downloaded the new version and neither fix above is currently working. Running 10.7.3

**Comment by zachwise** [comment]
I'm having the same problem.
It's logging something about "posix_spawn Operation not permitted."

**Comment by bdkjones** [comment]
Hmm, Can you send me the exact log message?

Also, can you try creating a new user account and logging into that account and attempting to run the app from there?

Finally, you have rebooted and tried to launch the app after that, correct?

**Comment by zachwise** [comment]
3/29/12 4:19:08.107 PM com.apple.launchd.peruser.501: ([0x0-0x3f13f1].com.incident57.CodeKit[26097]) posix_spawn("/Applications/CodeKit.app/Contents/MacOS/CodeKit", ...): Operation not permitted
3/29/12 4:19:08.107 PM com.apple.launchd.peruser.501: ([0x0-0x3f13f1].com.incident57.CodeKit[26097]) Exited with code: 1

I'll try the new account attempt later.
I have tried rebooting.

**Comment by ghost** [comment]
Mar 29 16:20:30 XXXXX com.apple.launchd.peruser.501[128]([0x0-0x1de1de].com.incident57.CodeKit[6367]): posix_spawn("/Applications/CodeKit.app/Contents/MacOS/CodeKit", ...): Operation not permitted
Mar 29 16:20:30 XXXXX com.apple.launchd.peruser.501[128]([0x0-0x1de1de].com.incident57.CodeKit[6367]): Exited with code: 1

also have tried rebooting, cleaning caches (browser and computer), running all maintenance scripts, etc
Will try the alternate user when this render finishes.

**Comment by bdkjones** [comment]
Render, eh?

How many active processes and threads are running on your Mac? OS X will refuse to spawn new processes once it reaches a certain amount of active ones.

**Comment by zachwise** [comment]
Just tried creating an account and launching the app. Got the same logged error.

**Comment by bdkjones** [comment]
Youve downloaded build 6010 right?

There was a corrupted file in 5978 that caused this issue.

Sent from my iPad

**Comment by zachwise** [comment]
Yep, I downloaded a fresh copy from the newly created account before trying to launch it.

**Comment by zachwise** [comment]
I found a work around for now http://www.itcrumbs.com/?p=169
Basically I removed the the quarantine flag manually and it works fine.

**Comment by ghost** [comment]
Hm, tried removing the specific quarantine flag, and failing that shut down quarantine flags altogether, rebooted, no dice. http://cl.ly/0g2z2K2W3C1K42122g41 - that's my error log. I've tried opening it directly after a clean boot and as a separate user as well.

**Comment by zachwise** [comment]
did you remove the flag on the exec? /Applications/CodeKit.app/Contents/MacOS/CodeKit?
That worked for me.

**Comment by ghost** [comment]
It's alive! Sweet.

**Comment by ghost** [comment]
I hade to run `xattr -d com.apple.quarantine [path to bin]` on the bin/executable in every single folder in /Applications/CodeKit.app/Contents/Resources/engines/ before 6010 would fully function for me.

**Comment by bdkjones** [comment]
Have you by any chance turned on GateKeeper in 10.7?

**Comment by zachwise** [comment]
I thought GateKeeper was only in 10.8?

**Comment by igaenssley** [comment]
I am also getting this exact issue as well. I've also noticed that since downloading and attempting to run 6010, any other less compiler I have installed also seems to be fizzling out.

All of this was working minutes before installing 6010, no restart, system update, or any other software was installed between the time it was working and the time it was not.

**Comment by ghost** [comment]
For me the issue has been  with OS X app quarantine and I had to dequarentine the entire app folder. This has happened to multiple apps for me in the last three months, not just this one.

Try:

sudo xattr -dr com.apple.quarantine /Applications/Codekit.app/

**Comment by bdkjones** [comment]
Greg: that's REALLY useful information. 

What other apps have shown this issue? It's possible that the bug rests with Apple and not CodeKit. As it stands, the app installs and runs perfectly for 99% of users. You guys are just the lucky few!

**Comment by exquisiteOntologist** [comment]
bdkjones, after reading Greg's discovery, I discovered that osx flags applications unzipped by 3rd party un-archivers for quarantine. I was using "The Unarchiver" from the app store. So I deleted it, restarted the mac, and unzipped Codekit using OSX's finder. IT WORKS! :) Found solution here: https://discussions.apple.com/thread/3851085?start=0&tstart=0

**Comment by bdkjones** [comment]
Oh thank God. I went over and over and over the project in Xcode trying to figure out WHAT THE HELL was going on with this issue. Glad it wasn't my fault and thanks very much for taking the time to post here!

**Comment by exquisiteOntologist** [comment]
Yeah, sorry about that.

**Comment by ghost** [comment]
Oh for the love of god, is that really it? Thanks for Finding that Jevlon.
