### ISSUE TITLE
Ship It!

### ISSUE THREAD

**Issue by StevenBlack** [bdkjones/CodeKit-1-Old#287]
Brian, CodeKit has been working great for me for weeks on multiple projects.  The latest build has no retrogrades that I have found.

I've even re-organized projects and folders, fully expecting to crash CodeKit.  It didn't happen.

On balance, CodeKit has made the predicate upgrade to Lion worthwhile, which is saying something.

I would be very happy with this product in its current state.  It's streets ahead of many other 1.0 products at this stage.

You've done a great job with this!

**Comment by mindfullsilence** [comment]
Agreed, I and many others would be willing to pay the $20 at this point. A bonus would be automated updates, but really this is one of those few apps that have me begging someone to take my money regardless of future features.

**Comment by thrashr888** [comment]
+1. I'd happily pay for CodeKit. Take my stinking money already.

**Comment by bdkjones** [comment]
Soon!
