### ISSUE TITLE
Request: Per project 'Hidden Folders & Files' please

### ISSUE THREAD

**Issue by mkoistinen** [bdkjones/CodeKit-1-Old#29]
Title says it all.  I work on about 5 different projects throughout the each day and my customers often impose different file structures upon me, so, its not a one-size fits all for me.

**Comment by paulyoung** [comment]
Seconded, previously requested via email.

I suggest being able to single click a project and set it's hidden / ignored files in the sidebar in the same style as you would see in the preference pane but similar to imports when selecting a file.

**Comment by paulyoung** [comment]
I mocked [this](http://db.tt/nbAw9SJ) up to show what I had in mind for hidden / ignored files and folders on a per-project basis.
