### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by bokkagroup** [bdkjones/CodeKit-1-Old#290]
It would be nice to have multiple versions of a Framework. We use several including Twitter Bootstrap fairly often and the current functionality is fantastic for new projects. Problem comes in maintaining old projects that use a previous version. We may not have the time or resources to retrofit every past project to use the most recent version of a framework but still need the ability to compile LESS, JS, etc. for those sites.

Ideally, when new versions of frameworks are released, the old syntax and methods would still work correctly but that's not always the case.

Has anyone run into similar issues? Do you have a recommended solution?

Many thanks. As always, love the product.

**Comment by bdkjones** [comment]
Solution is in the works.
