### ISSUE TITLE
Can't use the third-party compass plugins

### ISSUE THREAD

**Issue by judewang** [bdkjones/CodeKit-1-Old#291]
I have added a require statement contained a full path to the plugin's required file to the beginning of my project's config.rb file, but there's still a problem with the compass-twitter-bootstrap I've installed. CodeKit throwed the following error:

```
LoadError on line 1 of /Users/WANNI/.rvm/gems/ruby-1.9.3-p125/gems/compass_twitter_bootstrap-
2.0.1.2/lib/compass_twitter_bootstrap.rb: no such file to load -- compass_twitter_bootstrap/version
Run with --trace to see the full backtrace
```

You can see the files of **compass-twitter-bootstrap** [here](https://github.com/vwall/compass-twitter-bootstrap).
I'm using CodeKit version 1.0 (5987), looks like this maybe is a bug.

**Comment by judewang** [comment]
Still got the same error when using version 1.0 (6010).

**Comment by flyingeek** [comment]
It would be nice like in LiveReload to be able to specify the ruby interpreter to use when using compass. That way we could use plugins inside a rvm

**Comment by judewang** [comment]
Yes, I think so, too. I just bought the LiveReload last week from the 99 cents promo. Since it still got the same error, I'm now using LiveReload and the Compass Plugins, but I'd rather choose to use the CodeKit if the problem can be solved, even if it may cost more than LiveReload.

**Comment by benfrain** [comment]
I get the same problem using sassy buttons and susy grid (https://github.com/ericam/compass-susy-plugin) - compiles just fine from command line but CodeKit says

`LoadError on line 160 of /Applications/CodeKit.app/Contents/Resources/engines/compass/bin/../lib/compass/configuration/data.rb: no such file to load -- susy
Run with --trace to see the full backtrace`

**Comment by bdkjones** [comment]
Issue #161 was closed with an explanation. This item is checked off the list and complete; it'll be in the very next release.
