### ISSUE TITLE
Shortcut for 'Show Window'

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit-1-Old#293]
It is good practice to have a shortcut for showing/opening the application window if it is closed to the dock (the app is running only in the dock). The default is **⌘\** .
Better would be:

**⌘1** for 'Window -> Show Files'
**⌘2** for 'Window -> Show Log' .

**Comment by bdkjones** [comment]
Shortcuts added in 6145.

**Comment by ghost** [comment]
Thank you for implementing those shortcuts. The only thing missing is that none of these shortcuts opens the window if it is closed to the dock.
