### ISSUE TITLE
SCSS will not compile

### ISSUE THREAD

**Issue by jonathanpatt** [bdkjones/CodeKit-1-Old#295]
v1.0 (6010), all SCSS files error and do not compile, and the following gets logged to the Console:

```
CodeKit: *** NSTask: Task create for path '/Applications/CodeKit.app/Contents/Resources/engines/scss/bin/scss' failed: 22, "Invalid argument".  Terminating temporary process.
```

**Comment by bdkjones** [comment]
remove the quarantine flag on the scss executable:
xattr -d com.apple.quarantine /Applications/CodeKit.app/Contents/Resources/engines/scss/bin/scss

**Comment by bdkjones** [comment]
This occurs when you unzip the CodeKit download using a 3rd party unzip app. Use the one that came with OS X.
