### ISSUE TITLE
Less compile problem

### ISSUE THREAD

**Issue by zachwise** [bdkjones/CodeKit-1-Old#296]
I've had some problems with the latest beta.
The latest is when I try and compile and less file. It fails saying "Invalid Argument"
Here's the log from console:

4/1/12 8:39:21.090 PM CodeKit: **\* NSTask: Task create for path '/Applications/CodeKit.app/Contents/Resources/engines/node/node' failed: 22, "Invalid argument".  Terminating temporary process.

I first had this problem where the app wouldn't start:
https://github.com/bdkjones/CodeKit/issues/285

I think they might be related.

**Comment by bdkjones** [comment]
Are you running build 6010?

**Comment by zachwise** [comment]
Yes. build 6010.

**Comment by zachwise** [comment]
I have a crash report:
http://cl.ly/1T372A3D1s0Y3m1v3k46

**Comment by zachwise** [comment]
I'm getting some other crashes that are similar also related to node

**Comment by zachwise** [comment]
Got it working by removing the quarantine flag manually:
xattr -d com.apple.quarantine /Applications/CodeKit.app/Contents/Resources/engines/node/node 
This is the same thing I had to do for the CodeKit exec. 
Any idea why this might be happening?

**Comment by bdkjones** [comment]
are you running the 10.8 preview?

-Bryan

**Comment by zachwise** [comment]
System Version: Mac OS X 10.7.3 (11D50)
  Kernel Version:   Darwin 11.3.0

**Comment by bdkjones** [comment]
This is caused by OS X quarantining the resources inside the CodeKit application bundle. Did you unzip the download with a 3rd-party unzip app? If so, delete CodeKit, re-download it and then unzip it using the built-in unarchiver that ships with OS X. There is more info in several other threads on here.
