### ISSUE TITLE
MachintoshHD/Applications/Safari/Contents/Resouces path opens every time I hit save

### ISSUE THREAD

**Issue by jozzs** [bdkjones/CodeKit-1-Old#299]
It happens with both SublimeText2 and TextMate. I'm using just Safari. I tried with Chrome and It works fine.

**Comment by bdkjones** [comment]
Do you have the WebKit Nightly installed on your system?

Which version of OS X are you running? What version of Safari? What Safari Extensions are installed and running? Are you running any other apps that affect Safari? How are you previewing your webpages (Mamp, file:// etc)? What settings are you using in CodeKit relating to browser reload (active tab, urls, etc)? 

Did this happen with older versions of CodeKit or is it new in 6010? Does it happen on every project/webpage you try? The more information you can give me, the better!

**Comment by jozzs** [comment]
I'm sorry! Here it goes
- I have WebKit r103689 installed.
- Mac OS X 10.7.3 (11D50)
- Safari 5.1.4 (7534.54.16)
- Safari extensions:
  - User CSS 1.3.2 (http://code.grid.in.th/)
  - AdBlock 2.5.23 (http://safariadblock.com/)
  - YouTubeWide 8.0 (http://pedrocc.com/safari) _Currently disabled_
  - Duplicate Tab Button 1.1
  - Cuevana Stream 4.1
  - BetterSource 1.0 (http://www.awarepixel.com/safari/bettersource/)
- I have Flash Player installed
- I'm using Mamp Pro with a custom host to my project path
- CodeKit configuration:
  - Safari & Chrome
  - Update specific URL's
  - Inject changes without a full reload _disabled_
- It didn't happen in older version, but it didn't happen in this version either.
  It has started today. I have tried restarting, but the window still appears every time I hit cmd-S, no matter what project or file.

**Comment by jozzs** [comment]
It also happens with file://

**Comment by bdkjones** [comment]
Interesting. 

What changes have you made to your system today that you can recall?

**Comment by jozzs** [comment]
I think I haven't made any changes at all. I started as usual and when I hit save the window appeared

**Comment by jozzs** [comment]
I don't know how, but it seems the bug is fixed. I left the MacBook in sleep and now is working all fine. It must be something with my Mac. Sorry for the inconvenience and thank you for the support!

**Comment by jozzs** [comment]
The bug is still there. Cmd+S and the window appears, but the strange thing is that it doesn't appear every time, just two or three times, then inexplicably all goes fine.

**Comment by Julien76** [comment]
I have the same issue randomly with build 1.1.1 (6145).

**Comment by bdkjones** [comment]
This appears to be an Apple bug. 

Others have reported that if you restart your Mac AND choose NOT to reopen windows when logging back in, the issue resolves itself. 

As it stands, there's absolutely nothing in CodeKit that would cause the Finder to open that path. I've logged the issue with Apple and hopefully it gets resolved soon.
