### ISSUE TITLE
Codekit will not import less files if the previous file is blank 

### ISSUE THREAD

**Issue by bleeppurple** [bdkjones/CodeKit-1-Old#300]
small bug when importing and compiling less files...

To reproduce:

say I have a main less file which i import other less files into

styles.less

@import "modules/1.less";
@import "modules/2.less";
@import "modules/3.less";

if '2.less' is a file but its contents is blank (i.e an empty file)

styles.less will compile but will not import '3.less'

**Comment by bdkjones** [comment]
This is an issue with Less. The fix is simple: don't import blank files.

**Comment by assertchris** [comment]
Just spent and hour with this issue. Please could you make a note somewhere about this?
