### ISSUE TITLE
Use Framework name in import paths

### ISSUE THREAD

**Issue by gabrielso** [bdkjones/CodeKit-1-Old#303]
Using the framework name with the file name in @import declarations would allow having multiple files with the same name and also multiple versions of frameworks (considering different folder names), minimizing the 'unique file name' restriction.

Following your video demo we could import the vdkbuttons.less with:

@import 'VDKFramework/vdkbuttons.less'

You type a little more but the benefits are huge!
Congrats for the project!

**Comment by TuckerWhitehouse** [comment]
+1

**Comment by stef-rausch** [comment]
+1
