### ISSUE TITLE
Hangs when using project-specific settings

### ISSUE THREAD

**Issue by mcraddick** [bdkjones/CodeKit-1-Old#307]
When using project specific settings and attempting to edit them; all of the tabs except the languages tab will be empty - after switching between 2 the entire app will hang and have to force quit. Global preferences work fine though.

**Comment by johanmoberg** [comment]
I can confirm this. It also appears that it is not honoring the project specific settings. If I for example specify that the output path for sass should be the same folder as the source file, it still use the app-wide settings.

**Comment by bdkjones** [comment]
Issue fixed in 6166 (1.1.3). Johan - changing the output paths will only affect NEW files that you add to the project from then on. It will not affect any files that are already in CodeKit.

**Comment by mcraddick** [comment]
comfirm fixed. Thanks!
