### ISSUE TITLE
JADE to HTML: extra line break with every tag

### ISSUE THREAD

**Issue by Julien76** [bdkjones/CodeKit-1-Old#308]
Hi,
I'm quite new to CodeKit (and gitHub) so I hope I post the message at the right place.
For every tag in Jade like:
`p some text`

I always end up with:
`<p>some text`
`</p>`

instead of:
`<p>some text</p>`

It makes very hard to read the non-minified output with long html pages.
For your info, I'm using the version 1.0 (6010)

Thanks,

Julien

**Comment by bdkjones** [comment]
Hi Julian,

Thanks for using CodeKit! Unfortunately, this issue is not something I can fix because it has nothing to do with the app itself. Rather, it's a problem in the Jade language. You should file a bug report on the Jade GitHub page.

**Comment by Julien76** [comment]
Thanks.
I will address the bug on the Jade GitHub page.
