### ISSUE TITLE
Jade recompile file that extends another file

### ISSUE THREAD

**Issue by lstebner** [bdkjones/CodeKit-1-Old#309]
I feel like the "extends" command should work similarly to how the "include" works. Where if I have a "layout.jade" that includes other files, the layout would get recompiled when the included files get modified. However, if I then have a file that extends layout, it does not get recompiled when layout or the other included files get modified. 

Currently using Version 1.0 (6010).

**Comment by grahambird** [comment]
Completely agree. I am using Jade extends alot and it's a real pain that CodeKit doesn't detect pages that use a layout and recompile those pages when the layouts change.

**Comment by bdkjones** [comment]
Hi guys,

I don't use Jade myself, so it would help if someone could put together a very simple test project that I can use to develop support for the extends command.

Can one of you do this and send me the files?

**Comment by grahambird** [comment]
Hi,

Here is a basic example. A layout.jade template file with a block called content and an index.jade which uses (extends) the layout template and populates the content block with a "Hello world" paragraph.

Currently this all works fine in CodeKit. What doesn't work is that layout.jade is not detected as being imported by index.jade so changes to layout.jade don't cause index.jade to be recompiled.

Hope that helps explain. BTW GitHub's textarea is stripping the indenting.

Graham

File: layout.jade

html
    body
        block content

File: index.jade

extends layout
    block content
        p Hello world

File: index.html

&lt;html>
&lt;body>
&lt;p>Hello world&lt;/p>
&lt;/body>
&lt;/html>

**Comment by bdkjones** [comment]
Issue fixed in upcoming release. Thanks for the heads up.

**Comment by grahambird** [comment]
Thanks very much. This will make a huge difference! :)
