### ISSUE TITLE
// @codekit-prepend not picked up

### ISSUE THREAD

**Issue by nodeGarden** [bdkjones/CodeKit-1-Old#310]
I have the following (shortened):

```
 // @codekit-prepend "/js/libs/jquery-1.7.2.js";
 // @codekit-prepend "/js/libs/jquery-ui-1.8.18.custom.js";
```

These are not getting picked up by the app auto-magically. I have to drag them into the "Imports" pane in UI.

I tried with a space between  //  and  @ 
as well as without. If I leave off the comment then it fails to minify.

_References:_

http://d.pr/8iHE
http://d.pr/qwOa
http://d.pr/NqL7

**Comment by bdkjones** [comment]
Do me a favor and try removing the first slash. So, //@codekit-prepend "js/libs/jquery-1.7.2.js";

If you're attempting to use the leading slash to establish a root-relative link, I don't believe CodeKit currently supports that. Although, it is something I should add. The leading slash should indicate the project's root folder.

Let me know if this solves the issue and we'll go from there.

Also: you're absolutely positive that named files exist in the locations you're specifying, right?

**Comment by nodeGarden** [comment]
dooah... obviously didn't think this one through, else I would have realized that the base JS file was already in /js/. It would make sense that everything is relative and that "/" would mean nothing outside the webserver.

Thanks for the reality reminder. Might want to give a notice in the log to say file is missing though, else when others forget (like me) it, then theres something to remind them.
