### ISSUE TITLE
Doesn't seem to be working with Adobe Shadow

### ISSUE THREAD

**Issue by torkiljohnsen** [bdkjones/CodeKit-1-Old#312]
Adobe Shadow (http://labs.adobe.com/technologies/shadow/) is a nice app/plugin that allows you to mirror your computer browser to your iOS or Android devices, so that changes that happen in the computer's browser are shown automatically on your other devices. Brilliant when working with responsive sites and testing in multiple screen sizes simultaneously.

When CodeKit refreshes the browser however, Adobe Shadow can't keep up it seems, and I have to manually refresh in Chrome on my computer to see the updated website on the other devices.

Not a big deal at all, just letting you know :)

**Comment by bdkjones** [comment]
Yea, that's because CodeKit tells Chrome, "Inject this CSS into the webpage in tab 2". There is no way to do this to the remote devices, as far as I'm aware.

**Comment by torkiljohnsen** [comment]
Would it be possible to configure CodeKit to tell Chrome instead: "Refresh tab 2 please" ?

**Comment by aripalo** [comment]
@torkiljohnsen Yes it is, in preferences panel uncheck the option "Inject CSS changes without a full reload"

**Comment by torkiljohnsen** [comment]
Haha :) Danke!

On Thu, Apr 26, 2012 at 2:10 PM, Ari Palo <
reply@reply.github.com
