### ISSUE TITLE
GateKeeper Bug, or CodeKit issue with GateKeeper?

### ISSUE THREAD

**Issue by kennonb** [bdkjones/CodeKit-1-Old#314]
I know most developers don't support beta operating systems, but I wanted to give you the logs anyway.

Running Mountain Lion DP3 the new v1.1 crashes. v1.0 was fine with DP3 so maybe it's an app issue and not OS related?

Logs:

4/19/12 2:51:07.560 PM com.apple.launchd.peruser.501[282]: ([0x0-0x1d11d1].com.incident57.CodeKit[48155]) Job failed to exec(3) for weird reason: 1

4/19/12 2:51:07.000 PM kernel[0]: qtn-exec: not allowed to exec quarantined /Applications/CodeKit.app/Contents/MacOS/CodeKit: 00000007

4/19/12 2:51:09.569 PM CoreServicesUIAgent[48156]: Unable to continue stopped application -- error -600

Take care,
kennon

**Comment by kennonb** [comment]
And I do have it set to allow applications downloaded from anywhere to run in Sys Prefs > Security & Privacy.

**Comment by bdkjones** [comment]
Do you get the same issue on 10.7? 

I'm going to install 10.8 later this month and start testing it. Until then, I'm gonna chalk this one up to Apple.

**Comment by kennonb** [comment]
No, it works fine in 10.7. The odd part to me is that 1.0 works fine in 10.8, so that's why I thought it could be a 1.1 issue. 

Anyway, 1.0 is working for what I need it for, so no worries.

**Comment by kennonb** [comment]
Hah.. looks like v1.0 just expired. Wondeful. Guess it's back to Terminal for a while. :)

**Comment by bdkjones** [comment]
Please see issue #285 or the top of the help page at http://incident57.com/codekit/help.php

The problem is third-party unarchivers, I believe. Did you unzip CodeKit using one? There's also a fix explained on the help page.

**Comment by kennonb** [comment]
Interesting. That did it. I missed that part in the Help docs. Sorry for wasting your time. :/ Thanks for the awesome app.
