### ISSUE TITLE
Application Icon res too low.

### ISSUE THREAD

**Issue by atEverychance** [bdkjones/CodeKit-1-Old#315]
When I launch CodeKit using Quicksilver, the icon looks terrible. "QS doesn't support displaying 512px icons in pane 1, so reverts to the next size down which, in some cases in Lion, means a 32px icon." A 32px icon in QS makes some for fugly pixelation. 

As a workaround, I went into /Applications/CodeKit.app/Contents/Resources and opened less.icns in Preview. Saving it 128x128px makes for a lovely QS icon. I have (so far) found no downside to this.

So that I don't need to do this with each release, perhaps a 128x128 version can be added with  Icon Composer.app?

Thanks for the great app!

**Comment by bdkjones** [comment]
Fixed in the next release. Thanks!
