### ISSUE TITLE
Jade Regular output style still minified

### ISSUE THREAD

**Issue by kentorg** [bdkjones/CodeKit-1-Old#316]
Version 1.1 (6143) Jade file output style of Regular (Indented) still produces minified version. I replaced the package contents of the build with the previous CodeKit's Jade folder for now.

**Comment by Julien76** [comment]
I've got the same issue using version 1.1.1 (6145)

**Comment by GarthDB** [comment]
Still seeing it in 1.1.2 (6149)

**Comment by netzintelligenz** [comment]
Same here, 1.1.2 (6149)

**Comment by bdkjones** [comment]
Fixed in 6166 (1.1.3)
