### ISSUE TITLE
Files only compile once

### ISSUE THREAD

**Issue by TuckerWhitehouse** [bdkjones/CodeKit-1-Old#317]
Today I purchased and downloaded the latest version of CodeKit.

I noticed that when I saved my files, they wern't being updated (the minified and compiled versions).

I checked the log in CodeKit, and it indicated that I was only able to compile each file once.

Cleared all projects in CodeKit, rebooted, re-added my projects and tried again.

Files of either .LESS or .JS I can save, and will get 1 successful compile, and then nothing appears in the log on any subsequent saves.

I've changed nothing other than updating my version of CodeKit.

I also tried uninstalling CodeKit (using TrashMe, so all related files were removed as well), re-downloaded, added the project, saved the file, got 1 successful compile, tried to save it again, and nothing.

**Comment by bdkjones** [comment]
If you're seeing this issue, please download this build and give it a try. Let me know if it fixes the problem:

http://incident57.com/codekit/files/codekit-6144.zip

**Comment by TuckerWhitehouse** [comment]
Worked for me!

Thank you very much for the quick build.

**Comment by bdkjones** [comment]
Awesome. Thanks.
