### ISSUE TITLE
Codekit + less + Instant Preview IDE Apps (eg. Espresso)

### ISSUE THREAD

**Issue by voodoo6** [bdkjones/CodeKit-1-Old#320]
Hi,

Loving CodeKit since I started getting into LESS recently.. great work.

One thing I _really_ miss when coding with LESS and CodeKit is the **instant-preview** and the **applied styles inspector** offered by espresso. Its so great seeing the preview change **without** having to hit Cmd-S every-time.

Is this even possible using CodeKit and LESS with an IDE app like espresso that has an instant preview feature? Is it something planned? (Or am I just doing wrong!)

How would we get around having _@import "mixins";_ type rules, where I need to save the .less stylesheet to get them imported?

Any thoughts?
Matt

**Comment by benklocek** [comment]
I"m in the same boat, and have resigned myself to using Chrome Dev Tools instead of the Inspector. I know it's not ideal, but it's actually making me a better coder, as I can't just flip through options quickly, I need to actually know what I want to do.

**Comment by bdkjones** [comment]
The trouble here is that the Less file is not CSS and must be compiled before a browser can do anything with it. Compiling large less files can take a few seconds, so it's not something that can always be done instantaneously when the user pauses in his typing.

As such, this is probably outside the realm of the possible right now.
