### ISSUE TITLE
New version crashing on compile

### ISSUE THREAD

**Issue by bokkagroup** [bdkjones/CodeKit-1-Old#321]
I just bought the new version and although I can set up my sites and frameworks fine, it crashes every time I try to compile a LESS file. I can click the file in CK and compile it fine but when I'm in the code (WebStorm) and save it file, it crashes CK.

**Comment by bdkjones** [comment]
Tons of java-based editor users and macVim users are reporting crashes with the release build.

I've put out a fix that rolls back an earlier change. Please download this build: http://incident57.com/codekit/files/codekit-6149.zip and let me know if it works. Thanks!

**Comment by bokkagroup** [comment]
That worked perfectly. Thanks Bryan.
