### ISSUE TITLE
Ouput Paths / Less / To this path — relative to source file

### ISSUE THREAD

**Issue by slackero** [bdkjones/CodeKit-1-Old#323]
Output path is set false when I use 
To this path: ../css
Relative to: The folder that contains the source file

My assets are structured like this
assets/less
assets/css

I import "less" folder directly as project folder. So the less source files become this:
/my.less
Based on preference it should compile .css to
/[source file's folder]../css/my.css -> assets/css/my.css

But the "../" does not have an effect. It is compiled to:
assets/less/css/my.css

**Comment by thelitek** [comment]
Same thing when paths are set relative to project's root. Wrong paths are exported to codekit-config file.

**Comment by bdkjones** [comment]
You failed to read the note that appears below the box: if you attempt to use the ../../ syntax to set a folder that's ABOVE the project's root folder, any additional "../" that takes you above the project's root folder is ignored. 

In short: your output path must be contained at or below the project's root folder. There are a variety of really good, technical reasons for this limitation -- many of them concerned with safety.

**Comment by slackero** [comment]
The problem is if you prefer to use LESS files only like I do (in general). Also the description is not clear: Relative to [The folder that contains the source file]. I cannot see a real security problem here… If this cannot be changed it might be better to have an option to filter folders and/or file types by default while creating projects.
