### ISSUE TITLE
Garbled files with Git

### ISSUE THREAD

**Issue by malvese** [bdkjones/CodeKit-1-Old#324]
We're experiencing a strange issue with Codekit on our current project. I'm aware there are issues with Git/Subversion and read about them and the FAQ, but I'm not sure if this is part of the known problems.

What happens is when we do a git pull --rebase and have updated files opened in our editors, the files get garbled. Instead of merging the changes where they belong, they are added as unicode "diamond" signs at the end of the file.

Example: I have a file that ends with :

 .push-esfy {
   position: relative;
   text-align: center;
   .field-name-c-content-title {
     font-size: 12px;
     font-weight: bold;
     margin-top: 10px;
   }
   .picto {
     position: absolute;
     top: 60px;
     width: 100%;
   }
   .call-to-action {
     bottom: 20px;
     position: absolute;
     width: 100%;
   }
 }

If I pull and something has been changed anywhere in the file that are opened in the editor, I'll
end up with something like :

 .push-esfy {
   position: relative;
   text-align: center;
   .field-name-c-content-title {
     font-size: 12px;
     font-weight: bold;
     margin-top: 10px;
   }
   .picto {
     position: absolute;
     top: 60px;
     width: 100%;
   }
   .call-to-action {
     bottom: 20◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆

I initially put the blame on the old and clunky Textmate, but others in the team have the same issue with other editors (phpStorm,
SublimeText 2…)
We all use Vmware Fusion virtual machines, may that be the origin of the problem? We use either NFS or Samba to access the files inside the VM.
We could uncheck the project every time we pull/merge/checkout, but it's not ideal and we often forget and swear like mad sailors :)

I also read about how we could include the whole project tree, including the .git directory, but we can't on this project as it has over 20.000 files! Zuckerberg doesn't work here so obviously we do something wrong, unfortunately we have no control over the project's structure…

**Comment by bdkjones** [comment]
Hmm,

This one will be tough to do anything about because I'm almost positive the trouble lies in the VM/NFS/Samba combination. Those layers all add massive complexities to the underlying file-watching routines that power CodeKit. I don't have any of these things over here to test with, so it would be very difficult to track down the cause. Additionally, it's highly likely that the issue is beyond my control --- it's something to do with OS X's file-watching APIs.

**Comment by malvese** [comment]
Doesn't seem to happen anymore with newer versions.
