### ISSUE TITLE
Feature Request: Framework Scopes

### ISSUE THREAD

**Issue by bluestrike2** [bdkjones/CodeKit-1-Old#325]
Hi Bryan,

Loving Codekit so far. Especially now that I've been able to buy a license to support you a bit (and I've kind of crammed the need to get Codekit down the throat of most people who will listen between you and I).

Anyhow, I really think the framework idea is rather interesting (though I do wish there were a way to integrate it with git repos, i.e. symlinks and then one can have git add files beyond symlinks - though I realize that's kind of moving beyond what you're aiming for and I'm not certain that idea even makes sense in an implementable way). But my big issue right now before really jumping into it for some of the larger framework stuff we use is in the namespacing conventions. We have one Stylus framework we call "Inkwell" internally. Structured something like this:

```
/inkwell/index.styl
/inkwell/config.styl
/inkewell/functions/index.styl
```

You get the picture. Anyhow, the two issues are (1) it's really easy to find yourself with duplicate filenames within the individual framework files and (2) you can add to that the possibility of filename clashing with local files.

Off the top of my head, wouldn't a framework scope at the top level solve for that (and for the duplicates within subdirs in fw, enforcing consistent + matching directory paths)?  So instead of importing 'config.styl' like you would right now you'd have to do 'inkwell/config.styl' etc.

I realize it's not a major priority, but it's a little thing that might give the feature some real flexibility and really make it a killer feature. Hell, toss in a command to update a framework's git repo (if it is one) w/ option for either manually or automatically via codekit and it'd be something to die for.

Random thoughts. Back to work.

**Comment by bdkjones** [comment]
Implemented in 2.0.
