### ISSUE TITLE
Possible Bug - Livereload hangs

### ISSUE THREAD

**Issue by mindfullsilence** [bdkjones/CodeKit-1-Old#327]
sometimes when I'm writing the css(less) for my site I'll be working with small nudges in numbers and working pretty quickly changing a single value:

```
margin-left: 200px;

Then:
margin-left: 160px;

Then:
margin-left: 180px;
```

You get the idea. Well, if I do this too quickly, sometimes the browser won't update. If it doesn't, out of habit I alt-tab to the browser (chrome) and hit cmd+r to refresh. About 50% of the time when doing this, both codekit and the browser crash. More specifically, the browser quits and codekit becomes unresponsive until I force quit the app.

**Comment by envex** [comment]
This doesn't help with your issue, but just a tip: When you're fine-tuning your layouts like that it's easier to use the inspector to edit the css values live and then copy the value to your .less/.css file.

**Comment by mindfullsilence** [comment]
Good idea, I'll do that.

**Comment by bdkjones** [comment]
Is this still an issue with the very latest build, 6502 (version 1.2.2)?

**Comment by mindfullsilence** [comment]
Started on a new client about 3 days ago. Once I get to the coding stage I'll let you know.

**Comment by mindfullsilence** [comment]
Just wanted to give you guys an update. It appears this issue has been fixed. After repeatedly trying to move fast enough to kill the app with this method, I failed to do so.
