### ISSUE TITLE
Feature Request: Jade to custom file extension

### ISSUE THREAD

**Issue by Fresheyeball** [bdkjones/CodeKit-1-Old#329]
Title says it all. Just looking to save out Jade to .gsp or .erb or whatever.

**Comment by bdkjones** [comment]
Yea, I'd like to be able to support that as well. But the Jade compiler currently doesn't allow it. I could write some code to work around the issue, but it would slow down the overall compiling time for Jade by a fraction. 

This is definitely on my radar, though.

**Comment by Fresheyeball** [comment]
Oh I would take the fraction in a second for access to the language of my choosing.

**Comment by bdkjones** [comment]
Added in 1.2.4.
