### ISSUE TITLE
Haml filter error

### ISSUE THREAD

**Issue by Fresheyeball** [bdkjones/CodeKit-1-Old#332]
On attempting to use Markdown:

: Can't run Markdown filter; required 'rdiscount' or 'peg_markdown' or 'maruku' or 'bluecloth', but none were found
  Use --trace for backtrace.

**Comment by bdkjones** [comment]
Can you send me an example file that demos the issue? I don't know Haml and don't have any sample files with Markdown in them.

**Comment by hssrrw** [comment]
I got the same error. Also it occurs while using Textile filter:

```
Haml error on line 38: Can't run Textile filter; required file 'redcloth' not found
  Use --trace for backtrace.
```

Is it an error in CodeKit's internal compiler? I have installed redcloth and bluecloth gems but it seems like CodeKit's compiler doesn't use system ruby gems.

You can use this code:

``` haml
!!! 5
%html{:xmlns => "http://www.w3.org/1999/xhtml", :lang => "en"}
  %head
    %title The Title
    %meta(charset="UTF-8")
  %body
    %section#top
      %nav(role="navigation")
        :textile
          * "Who":#who
          * "What":#what
          * "Why":#why
        :markdown
          * [Who]:#who
          * [What]:#what
```

Tanks

**Comment by bdkjones** [comment]
Switch CodeKit to use an external Haml compiler. See the Languages tab of the Preferences window.

**Comment by hssrrw** [comment]
The same errors. Whereas Haml compiler works like a charm directly from terminal.

**Comment by bdkjones** [comment]
Is this now working for you in 1.5.1?

**Comment by hssrrw** [comment]
Yes, now it is working. Thanks for the update!
