### ISSUE TITLE
Coda not noticing complied CSS

### ISSUE THREAD

**Issue by mattclements** [bdkjones/CodeKit-1-Old#333]
This is probably more of a Bug with Coda (and if so I will notify them), but when saving a Less file from Coda which is then complied using CodeKit - Coda doesn't notice a change to the CSS file, and therefore is not marked for publishing.

If you think theres anything you can do that would be great - if not I will pass to Coda and see if they can sort something.

By the way - awesome app for $20 (+4) !

**Comment by bdkjones** [comment]
This is a Coda issue.
