### ISSUE TITLE
Javascript file errors gets output when the file is hidden

### ISSUE THREAD

**Issue by vipickering** [bdkjones/CodeKit-1-Old#336]
Steps to reproduce:

1) Add a site from the route.
2) choose the scripts tabs in code kit and hide each JS file.
3) recompile your code.
4) If there are any errors in your JS they are still fed out by the compiler

**Comment by bdkjones** [comment]
Hiding files means exactly this: Don't show them in the UI.

It does NOT mean, "Ignore these files."
