### ISSUE TITLE
Feature request: Regex for auto reload URL

### ISSUE THREAD

**Issue by tomasz-tomczyk** [bdkjones/CodeKit-1-Old#337]
When working on a Wordpress site, I'd like to have all pages besides the /wp-admin/ to reload when I make changes. Can we have regex or exclude list for the URLs?

**Comment by kmmathis** [comment]
+1 from me. Every time I work on a WP theme, I wish I could exclude URLs with wp-admin in them.

**Comment by bdkjones** [comment]
No longer applicable in 2.0. CodeKit 2.0 is fully customized to deal with Wordpress and host it across multiple devices.
