### ISSUE TITLE
cpu hog

### ISSUE THREAD

**Issue by 1stevengrant** [bdkjones/CodeKit-1-Old#338]
Noticing that CK is quite frequently using 100% of the CPU. Any reason for that?

**Comment by bdkjones** [comment]
Change how frequently projects auto-refresh. CodeKit uses multiple threads to refresh projects quickly, so it's likely to take up a significant amount of CPU when it happens.

The app should never use _any_ CPU when it's not either compiling or refreshing.

**Comment by 1stevengrant** [comment]
cool - I never realised the exclude folders was there as well
