### ISSUE TITLE
Feature request: checkbox to 'Automatically set all imported files as hidden'

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#34]
We talked about this via email but adding it here.

Similar to the ignored option. This might even eliminate my need for per-project hidden files and folders for now.

**Comment by bdkjones** [comment]
mmm, this could prove confusing for users. "Why isn't file X showing up!? I've added this project like 20 times and it never shows up!"

(You'd be surprised at the general stupidity of humanity.)
