### ISSUE TITLE
Javascript/CoffeeScript imports declared in external file as JSON-format

### ISSUE THREAD

**Issue by aripalo** [bdkjones/CodeKit-1-Old#343]
Here's an idea:

Would be sweet to have a possibility of importing JS files from external JSON-formatted file, instead of @codekit-prepend / @codekit-append inside a JS file.

Reason this would be sweet is that many times projects have an server-side or some terminal based build/deploy process for production and in at least in our case we have a json formatted file that have all the JS-files listed for concat+compression. Therefore it is annoying having to manage the JS files from to different places. So as solution one could just reference the JSON-file from project settings and codekit would then import JS files based on that.

Maybe this is just too edge case for codekit, but had to throw the idea out!

**Comment by bdkjones** [comment]
Hi Aripalo,

This is something I might investigate one day, but I have a lot of other stuff I'd like to check off the list first. The idea behind CodeKit is that it _replaces_ server-side build scripts and processes. I will acknowledge that, right now, it's not as powerful or customizable as a server-script, but it will evolve.

It doesn't really make sense to spend a ton of time making CodeKit work with external build scripts when the entire point of the app is to make the use of such scripts obsolete. Thanks!
