### ISSUE TITLE
Feature Request: Renaming of projects

### ISSUE THREAD

**Issue by davidjdixon** [bdkjones/CodeKit-1-Old#344]
In issue #111, it was claimed that double clicking a folder name in the project window allowed renaming the project whilst maintaining the path (allowing multiple projects to be managed that have the same base folder name).

Whether this feature existed in the past or not, it does not seem to be present any longer, as double clicking the project name now simply opens a finder window to the projects parent folder.

Please can this feature be reinstated (not concerened whether dbl click or via context menu), as this would be incredibly useful when managing large numbers of simultaneous projects.

**Comment by davidjdixon** [comment]
noticed it wasnt a "double click", as you'd normally think of it, but the finder-esc click and click again (after a small delay). I think it would still be beneficial to have it as a context menu item (again as per finder and most other OSX apps)

**Comment by bdkjones** [comment]
You click twice, slowly. Just like everywhere else in the OS. It is not difficult.

**Comment by davidjdixon** [comment]
Could you possibly try answering a paying customer request without talking down to them? You do yourself no favours by giving such frustrated responses.

My previous comment also stated this and made an additional observation, which is still valid. Also, this hasn't been the only time it's been noted, so maybe the UI needs something else to make the feature more accessible.
