### ISSUE TITLE
Feature request: sync preferences between multiple macs

### ISSUE THREAD

**Issue by pdesterlich** [bdkjones/CodeKit-1-Old#345]
I know i can manually set specific preferences for a single project, export to file, move file to another mac & import it, but a nice addition would be (pseudo) automatic app preference sync (for example via dropbox file, local network or any other method), in order to keep the same global preferences on all computers

**Comment by bdkjones** [comment]
There's already several apps that do this for you, although I can't recall the names of any of them at the moment. I would recommend that approach. Thanks!
