### ISSUE TITLE
Register CodeKit menu item appears to do nothing when on the Log view

### ISSUE THREAD

**Issue by marblegravy** [bdkjones/CodeKit-1-Old#349]
Super minor issue here, but I felt it was worth listing.

If you are in the Log view and you go to **CodeKit -> Register Codekit**, nothing happens. 
Switching to the Files view shows the Register pane as expected.

It took me all of 30 seconds to figure out what the problem was, but it was confusing. Perhaps add an action to the **Register Codekit** menu item, that will swap the view automatically?

**Comment by bdkjones** [comment]
Fixed. Thanks!
