### ISSUE TITLE
Feature request: 'Compile All' should read 'Compile Selected' unless all files are selected

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#35]

**Comment by bdkjones** [comment]
The latter text doesn't fit in the button. 

Unlike Less.app, CodeKit isn't really designed to have a "Compile All" button. That was a remnant of the old Coda Plugin. Plus, the inspector displays the count of files selected at the top, so I think it's pretty natural to assume that "all" refers to all the files in the selection; not all the files in the app/project.
