### ISSUE TITLE
Feature Request: option to use pre-release version of SASS 3.2?

### ISSUE THREAD

**Issue by kabojnk** [bdkjones/CodeKit-1-Old#350]
Not a big deal, just thought I'd ask because SASS 3.2 supports some pretty neat stuff (like use of @content, which allows for media query mixins).

**Comment by kabojnk** [comment]
It's probably not a scalable solution out-of-the-box, but it would be neat to specify the location of a custom version of SASS/Less/whatever... at least that would be somewhat scalable and it would not require CodeKit to stuff twenty billion different versions of these frameworks into the app.

**Comment by kabojnk** [comment]
Maybe it won't be such a big deal... if this is an edge case I can just swap out the scss binaries in the app package.  Well, as long as it's not code-signed. :)

**Comment by bdkjones** [comment]
Feature added. New release coming soon.

**Comment by kabojnk** [comment]
You are a badass, sir!
