### ISSUE TITLE
Crashed and slow

### ISSUE THREAD

**Issue by harlley** [bdkjones/CodeKit-1-Old#352]
Hi, the Codekit version I bought is getting my mac very slow and it has been crashed a lot. I always need to force it to quit.

**Comment by decodigo** [comment]
Hi, I am also experiencing this. I'm on a Mac Pro With Lion(10.7.4) 6GB RAM and Xeon possessors. When I check activity monitor it say the app is no responding and "Real Mem" is at ~2.5GB with the CPU usage at %44.

I would love to continue using this great app but can't until this is fixed.

**Comment by mattstauffer** [comment]
After the latest update, CodeKit is unusable for me--it starts up with 1.2GB of (Real) RAM usage and 100% CPU usage, and the memory quick ramps up to 3 and 4GB and non-responsive . I have to force quit it every time. 

This is true even when I uncheck all of my projects (at least, the 1.2GB of memory and 100% of CPU at start-up is). However, if all of my projects are unchecked, it never goes beyond 1.2GB, and the 100% CPU stops after its initial scan.

As soon as I check a project again, it rams up to 3-4GB... and then back down after 30 seconds or so.

Then after that, every time I make a change--save a file, etc.--to that project, it ramps back up to 3-4GB for 15-30 seconds, and then back down (although usually it eventually hits the point where it never comes back down from 3-4GB). It's enough to slow my entire computer to a crawl.

I can provide any more details if necessary. Thanks!

**Comment by joelshapiro** [comment]
Hi Bryan

v1.1.4 was working great. I updated today to v1.2.  After a few hours of working, CodeKit stopped compiling my scss and stopped reloading my pages.  Activity Monitor said it was "(not responding)".  I've had to force quit and relaunch a number of times. Now it only compiles for a few saves after relaunch before freezing. Your crash reporter sometimes comes up on relaunch but there are no reports in the /Logs/DiagnosticReports/ folder.  I haven't rebooted yet.

FWIW: I've tried to open v1.1.4 but get "Persistent store migration failed, missing source managed object model" & then "Failed to initialize the store"

MBP 10.7.4

Thanks

**Comment by bdkjones** [comment]
Hi guys,

Hmm, sorry for the trouble. It's possible that the data model has been corrupted. Quit the app and restart it while holding down the shift key. (Or, delete ~/Library/CodeKit before you start the app). Let me know if that resolves the issue.

**Comment by mattstauffer** [comment]
Yes! That did it. Back down to 30MB and snappy. Thank you!

**Comment by decodigo** [comment]
Yep, worked for me too. Thanks!

**Comment by joelshapiro** [comment]
So far so good.  FWIW: I also upgraded to 1.2.1.  Thanks!
