### ISSUE TITLE
Feature Request: Support for windows please!

### ISSUE THREAD

**Issue by Daniel-Hug** [bdkjones/CodeKit-1-Old#354]
Some of us can't afford macs, but I am sure there are _very many windows users_ who would be willing to pay $20 for something like this.

At least consider it.

Thanks man!

**Comment by bdkjones** [comment]
Sorry chief; I don't know the first thing about developing on Windows. I haven't touched a Windows machine in five+ years. That said, if I ever run into anyone who wants to port CodeKit, I'll certainly consider it!
