### ISSUE TITLE
Could not switch to Sass/Compass executable (RVM)

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit-1-Old#356]
I have installed sass and compass via rvm -g, the executables are in ~/.rvm/gems/ruby-1.9.3-p194/bin/ -- executable for all users.
When I try to switch the executable for either sass/compass under Preferences / Languages / Sass / Advanced Compiler Settings I get the error: 

"Failed to Switch Compilers
CodeKit could not switch to the specified external Sass compiler. Make sure that the app is idle and that you are selecting an appropriate executable file, then try again."

The executables are idle and executable :-/

**Comment by bdkjones** [comment]
Hmm...

Is your installed Compass version the pre-release 0.13 version?

If so, it's possible that this is failing because the updated Compass executable has different commands than what CodeKit can currently support. I'll have to look into it.

**Comment by ghost** [comment]
Nope, it is Compass 0.12.1 (Alnilam) and Sass 3.1.19 (Brainy Betty) - should be the same as the included ones. Maybe it is an RVM-issue?

**Comment by bdkjones** [comment]
Yep. It is highly likely that RVM is the culprit. I'm not really a Ruby guy, so I don't know much about it. 

However, if you install Sass/Compass normally into /usr/bin, I believe they should work just fine. (Sass for sure -- I tested it!)

**Comment by oskarrough** [comment]
I've got compass-0.13.alpha.0 installed in /usr/bin and I'm getting the same error.

**Comment by ghost** [comment]
I'm no Ruby-guy either. I just tried using my locally installed compass, to test if this would solve [this bug](https://github.com/bdkjones/CodeKit/issues/297). Copying/symlinking the RVM-installed binary to /usr/local/bin or /usr/bin doesn't help either.

**Comment by bdkjones** [comment]
Please download the version available here: http://incident57.com/codekit/files/beta

It should (hopefully) solve this issue. Let me know!

**Comment by ghost** [comment]
Hm, no luck for me (rvm installed compass/sass) with build 1.2.1 (6461), still the same error-message. Any ideas? Do you need more info?

**Comment by tobaco** [comment]
any news on this?

**Comment by bdkjones** [comment]
Not yet. It's the RVM issue that's mucking things up apparently. Try installing Compass without using RVM, and then switching to that external version.

This is on my list of things to look at for the next update.

**Comment by tobaco** [comment]
ok, thanks!

btw. Sass works fine for me as external compiler: http://cl.ly/1l3b460b0Y1z1o2d1z3x

**Comment by ghost** [comment]
@tobaco Your screenshots says you are on ruby 1.9.2-p290 -- I am on ruby 1.9.3-p194 and i can not choose a custom sass-compiler. Maybe this helps.

**Comment by pnomolos** [comment]
The issue potentially lies in the fact that CodeKit is using the system ruby (even if you set 1.9.3 as the system default via rvm).  You can verify this with a 'throw RUBY_VERSION' statement at the top of your project's config.rb file.  I'm trying to get CodeKit to use the proper ruby specified on the system $PATH but so far have had no luck (tried both the launchctl method and environment.plist method)

**Comment by pnomolos** [comment]
Alright, I've gotten this to play somewhat nicely.  First, using rvm, I had to create a wrapper ruby for codekit (see https://rvm.io/integration/textmate/ for more details).  I then created a wrapper script for compass with the following contents:

```
#!/usr/bin/env /Users/pnomolos/.rvm/bin/codekit_ruby
load `which compass`.strip
```

You'll obviously need to adjust the shebang appropriately.  This worked for compass, but a similar approach didn't work for the sass compiler for reasons still unknown to me (might be loading the file differently).  Anyway, what did work was to pass the path not for the sass wrapper binary, but for the internal ruby script itself, in my case this was:

```
/Users/pnomolos/.rvm/gems/ruby-1.9.3-p125/gems/sass-3.2.0.alpha.261/bin/sass
```

Hopefully this helps sort some of this out.

Do note - while this works, because it's having to build the rvm environment each time things are a bit slower.  Hopefully support for rvm can be baked right in to CodeKit in future :)

**Comment by pnomolos** [comment]
@bdkjones For future releases of CodeKit, would it be possible to specify the ruby binary to use when running custom Sass/Compass executables?  That would go a long way in making it possible for us to use rvm easily.

**Comment by ghost** [comment]
Since it's DECOMMISSIONED anyway, gonna close this issue.
