### ISSUE TITLE
CodeKit quitting unexpectedly during compile

### ISSUE THREAD

**Issue by joshmatz** [bdkjones/CodeKit-1-Old#357]
I've emailed my .crash reports but I figured I'd also post here after playing around with trying to figure it out.

CodeKit is crashing whenever I save a file that needs to be imported and compiled. So if I have styles.scss that is importing other files. If I make changes to styles.scss and save it, no problems happen. But if I edit _variables.scss, which is imported by styles.scss, and save it, CodeKit crashes without compiling (the change doesn't take effect).

**Comment by bdkjones** [comment]
It's possible the model has been corrupted. Please quit and restart while holding shift.

**Comment by bdkjones** [comment]
Also:

check your file to make sure there is not an infinite import loop between two files.

**Comment by joshmatz** [comment]
Unfortunately I tried this after reading another issue submitted here. It
didn't work :/ I've also restarted my computer and tried separate editing
programs.
On Jun 20, 2012 8:57 PM, "bdkjones" <
reply@reply.github.com>
wrote:

**Comment by bdkjones** [comment]
In that case, delete ~/Library/CodeKit with the app not running and then start it again. If the issue persists after that, it's very very likely that you've created an infinite loop with @import statements. That's what the crash log is suggesting.

-Bryan

**Comment by joshmatz** [comment]
I believe it was the infinite loop with imports (I didn't realize I copy/pasted an @import into a file).  

Thank you, Bryan! I appreciate your efforts and am glad to get support after purchasing CodeKit :)
