### ISSUE TITLE
Possible to compile files which are set to not directly compile

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#36]
This may be a feature and not a bug.

I tried to compile all as a lazy way of compiling everything in my project with an output path set, however this tries to compile everything.

I got errors for some files since they were never designed to compile and others were compiled to the directory of the source file.

Same behavior by selecting an individual file.

**Comment by bdkjones** [comment]
Yep. This is intended behavior.

The "do not directly compile" setting applies only to the action the app takes when the file is saved (or when a file that it imports is saved.) If you intend to use the "compile" button in the UI, then the app assumes you've selected the files you want to compile and it compiles them, regardless of whether they're "ignored."
