### ISSUE TITLE
Minifying a script with regex comments out the remainder of script

### ISSUE THREAD

**Issue by jasonvarga** [bdkjones/CodeKit-1-Old#360]
I don't know where the bug lies, whether its a bad coding practice or something wrong with the minifier.
But there is a double slash in the minified version where there is a regex, and it doesn't happen when its uncompressed.

Let me know what other details you need.
Thanks

**Comment by bdkjones** [comment]
Hi Jason,

```
Interesting. This may be a bug with Uglify.js. Please raise an issue on that project's GitHub page. Also: are you sure you've properly escaped the RegEx string? I find it tough to believe Uglify would have a bug like this given how popular regex use is in Javascript.
```

**Comment by jasonvarga** [comment]
I didn't write the JS and I'm wouldn't consider myself qualified enough to fix it.
Everything is working fine until I added the popular jquery.form.js plugin. Thats where it starts to bug out.
http://malsup.github.com/jquery.form.js

See what I mean: http://cl.ly/0F2O460r1u343k291I1S

I'll submit a bug with Uglify anyway.

**Comment by bdkjones** [comment]
Hi Jason,

```
Yea, I see that the regex in the original is not marked with any quotes and the authors added a comment to the end of the same line. So you end up with this:
```

var something = [regex here] //comment here

```
That comment at the end of the line may be tripping up the minifier. Either way, Uglify.js should handle it properly, so it's worth filing a bug report over there. The issue has nothing to do with CodeKit however; the app itself doesn't do any processing when minifying JS. It relies on Uglify.js
```

**Comment by bdkjones** [comment]
Closing this because it's an issue with Uglify.js, not CodeKit.
