### ISSUE TITLE
//@codekit-prepend, // @codekit-prepend and IE

### ISSUE THREAD

**Issue by ddanielou** [bdkjones/CodeKit-1-Old#361]
When loading a concatenated (not uglified) js file in IE8, I get a weird « Expected ';' » at lines which contain an @codekit-prepend comment.

Now, if I type // @codekit-prepend (with a space between // and @), I get no error at all, whereas //@codekit-prepend crashes IE 8.

Obviously, the problem doesn't happen on uglified files.

I realize this is not a bug in CodeKit (might have something to do with conditional compilation? just a wild guess), but maybe you could take it on yourself to add that space if it is missing?

**Comment by bdkjones** [comment]
Does the issue happen if you use this comment syntax:

```
/*@codekit-prepend "someFile.js"; */
```

Does the issue happen in IE9+?

**Comment by ddanielou** [comment]
> Does the issue happen if you use this comment syntax:
> 
>    /*@codekit-prepend "someFile.js"; */

Now this is getting weird. Same error with /_@... */, no error with /_ @… */. But with either, the file is not prepended. Is this expected behaviour?!

> Does the issue happen in IE9+?

Sorry, I don't have IE9.

**Comment by greystate** [comment]
This has probably got to do with IE's "Conditional Compilation" syntax: http://msdn.microsoft.com/en-us/library/121hztk3(v=vs.94).aspx

**Comment by bdkjones** [comment]
This seems like an IE8 thing, rather than an issue on my end.
