### ISSUE TITLE
UTF-16 Encoding

### ISSUE THREAD

**Issue by larryfox** [bdkjones/CodeKit-1-Old#363]
Currently CodeKit doesn't properly handle 16-bit unicode characters (U+10000 to U+10FFFF) in .less files (and likely anything that relies on node) since it's running Node v0.6.19

Node.js added UTF-16LE support in 0.7.9

> 2012.05.28, Version 0.7.9 (unstable)
> * add support for CESU-8 and UTF-16LE encodings (koichik)

Ironically, github doesn't allow those characters in comments, so test code is in this gist:

https://gist.github.com/3078752

**Comment by larryfox** [comment]
Relavent pull requests on node.js:
https://github.com/joyent/node/pull/3223
https://github.com/joyent/node/pull/3210

And in their change log:
https://raw.github.com/joyent/node/v0.7.9/ChangeLog

**Comment by bdkjones** [comment]
Build 6511 updates Node.js to 0.8.2, which should hopefully resolve this issue. It'll be in the next update.

Also, can I just add what a ridiculous joke it is that Node.js has been out for years and the team STILL hasn't hit the 1.0 mark? I get that the "pre-1.0" implies beta, but for the love of God... Node.js is used all over the freaking internet. It's time for them to put on their big girl panties and use proper version numbers.
