### ISSUE TITLE
CodeKit Changing Filenames to Uppercase?

### ISSUE THREAD

**Issue by WolfieZero** [bdkjones/CodeKit-1-Old#364]
I seem to be having an issue where files that I'm currently working with on a local machine are being transformed into uppercase names. This change isn't permanent as at times it will change the files to their original casing. I've had this happen across three machines but never on a remote server (mounted via Transmit).

**Comment by bdkjones** [comment]
What editor are you using to save the files?

**Comment by WolfieZero** [comment]
Sublime Text 2

**Comment by bdkjones** [comment]
Saw this issue from someone else recently. They were using SugarSync, which was the cause of the problem. Are you in the same boat?
