### ISSUE TITLE
@import an empty .less file causes subsequent @imports to be excluded

### ISSUE THREAD

**Issue by darronz** [bdkjones/CodeKit-1-Old#366]
To reproduce:
1. Create a base .less file
2. Inside it, import a few other .less files
3. Make one of the middle .less files empty
4. Compile the main file

Everything after the empty file is not included in the compilation.

... it is a bit edge case, but perhaps this will save someone a few minutes of confusion.

**Comment by bdkjones** [comment]
This is a known issue with Less.js itself. There's nothing I can do about it. Thanks though!

**Comment by rwoody** [comment]
It's kind of not cool how CodeKit has handled this error or just side tabled it. I beta tested the app and brought this bug up to you over twitter 4 months ago.

At least then it didn't fail silently. Took me an hour to find and I'm not new to CSS while I went through the same problem again tonight.

not cool!

**Comment by bdkjones** [comment]
It's not the app; it's the Less compiler.

-Bryan

**Comment by darronz** [comment]
Possibly fixed in a recent version of less https://github.com/cloudhead/less.js/issues/224
