### ISSUE TITLE
Issue: Output Paths

### ISSUE THREAD

**Issue by davidnknight** [bdkjones/CodeKit-1-Old#368]
Editing project settings and then selecting 'Output Paths' and changing javascript to export to '/js/' relative to the project's root folder. I then click the arrow on the right to reveal the files, click a javascript file to check the output path and it hasn't changed. Restarting CodeKit fixes the issue and shows the new path correctly but it won't display correctly without restart.

**Comment by bdkjones** [comment]
Intended behavior.

As the screen says, the default output paths apply to _NEW_ files that you add to the project from that point on. They do magically reset all existing files' output paths, as that would be disastrous.
