### ISSUE TITLE
CodeKit's jsHint considers caret as insecure

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit-1-Old#370]
I have some code containing regular expressions, that use the `^` (caret) character.
When checking the file, codekit and jsHint report it as being invalid due to the use of insecure bitwise operators - which isn't the case, as the caret is in fact inside a regular expression.

The official jsHint does not have this issue, and enabling / disabling bitwise operators in the jsHint settings seems to have no effect.

**Comment by bdkjones** [comment]
Please confirm that the version of JSHint you're using outside of CodeKit is the same as the version that CodeKit is currently shipping with. They may have fixed this problem since CodeKit was last updated.

Also, please confirm that you're using the same options for JSHint in both instances.

**Comment by ghost** [comment]
After looking at the JS**Lint** options, it turns out that this was under the `regexp` option.
It would be nice to add to the option's description that it also concerns insecure `^` and not only the insecure `.`
