### ISSUE TITLE
When output path is the same as the file itself, CodeKit falls into infinite loop

### ISSUE THREAD

**Issue by LeaVerou** [bdkjones/CodeKit-1-Old#371]
It doesn't crash CodeKit per se, but keeps appending and appending and appending until I quit the application.

**Comment by bdkjones** [comment]
Yes. CodeKit does not check to see if a file's output path is the same as its input path every time it goes to compile that file for two reasons:

1) I make it almost impossible to set that output path on the file (by requiring a suffix).

2) It would slightly slow down compiling speed.

The answer is fairly simple: don't do this.
