### ISSUE TITLE
Compiling js multiple times

### ISSUE THREAD

**Issue by jamesrampton** [bdkjones/CodeKit-1-Old#374]
Hi.

I'm working on a fairly large js file (3854 lines). I've set the file to minify to a folder above that of the source file. Whenever I save the file, CodeKit attempts to minify four or more times. Growl notifies me four times and four minify operations are recorded in the log. 

This doesn't happen when I hit the process button, only on saving the document. The same behaviour is exhibited whether checking syntax with JSHint, JSLint, or none at all. The js file throws errors in syntax checking, but none that affect its operation. 

I'm using MacVim with swapfiles and backups disabled and the project is getting its settings from the codekit-config.json. I'm also using git. 

Smaller files do not exhibit this behaviour. 

If you need any more detail, I'll provide what I can.

Thanks.

**Comment by bdkjones** [comment]
Does this JS file append/prepend any others?

Does the behavior show up if you use a modern editor, such as Sublime, TextMate, Coda, etc?

**Comment by jamesrampton** [comment]
Hi,

There are no prepend/appends on this file. I don't have a wide selection of modern editors but:

TextEdit, Xcode and a git checkout -- <file> don't produce the behaviour, and minify just once. 

Just for kicks, I tired Nano, which caused the file to be minified 19 times every time I wrote the file.

**Comment by matthiasbreuer** [comment]
Possibly this has something to do with the way the editor saves/outputs the file.

**Comment by jamesrampton** [comment]
Indeed, the behaviour suggests Vim writes from the buffer to the file in chunks, which is causing CodeKit to respond to changes multiple times (if the file is big enough).

**Comment by bdkjones** [comment]
Please see the note on the help page http://incident57.com/codekit/help.php for some tweaks you need to make if you're using Vim. Thanks.

**Comment by jamesrampton** [comment]
Hi, 

My .vimrc already sets no backup, nowritebackup, and noswapfile. If there are any other options I need to set, I'd be glad to know. 

Thanks.
