### ISSUE TITLE
Slim Support

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit-1-Old#375]
Would be delighted if my favorite preprocessor offered support for my favorite templating language.

http://slim-lang.com

Thanks for consideration!
- Kevin

**Comment by bdkjones** [comment]
Coming soon.

**Comment by ghost** [comment]
:) !!!!

On Jul 23, 2012, at 5:06 PM, bdkjones reply@reply.github.com wrote:

Coming soon.

---
