### ISSUE TITLE
Project settings doesn't close right sidebar

### ISSUE THREAD

**Issue by joshmosh** [bdkjones/CodeKit-1-Old#376]
I recently was looking at the compiler options for a specific file and then realized I needed to change project settings and when I clicked on project settings the right sidebar remained open.

http://d.pr/i/KwWV

**Comment by bdkjones** [comment]
Super irritating. The lesson here is that you should not rely on KVO notifications for animations that are only fractions of a second apart. 

Fixed in 1.2.4. Thanks for the report.
