### ISSUE TITLE
Crash on Less Compile

### ISSUE THREAD

**Issue by Leenug** [bdkjones/CodeKit-1-Old#378]
Hi, 

I'm getting a crash whenever I try to compile less files, at first i thought my IDE (phpstorm) was causing the problem, however when trying to compile from other IDEs / Editors the same issue exists, please see my attached error log:

https://gist.github.com/3205866

Thanks, 
Lee

**Comment by bdkjones** [comment]
This is not a problem with the app. You have an infinite import loop in your code: File A imports File B which imports File A. 

Fix that and you'll be all set.

**Comment by Leenug** [comment]
I just spotted the loop! I feel rather stupid!

Thanks for the reply all the same!

Lee
