### ISSUE TITLE
Request: Please bring back the old status bar icon {+}

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit-1-Old#380]
Personal opinion: Please bring back the old status bar icon {+}, the new one is to busy.

**Comment by bdkjones** [comment]
Sorry, it had to be Retina-fied and I didn't have the original artwork.

Plus, the old one looked a bit too much like a first-aid symbol for me. The gear gets at the idea of a "compiler" much better. And I plan to animate it in the near future as well, like the Time Machine icon.
