### ISSUE TITLE
Bug in Codekit 1.2.3 with Less 1.3.0

### ISSUE THREAD

**Issue by jvsummeren** [bdkjones/CodeKit-1-Old#384]
HTML5 boilerplate's [image replacement](https://github.com/h5bp/html5-boilerplate/commit/aa0396eae757) technique uses the following declaration:

``` css
font: 0/0 a;
```

Since I upgraded to Codekit 1.2.3 Less compiles this into

``` css
font: a;
```

resulting into elements with width and height, which is obviously unwanted behaviour. As a workaround I 'escaped' the value by adding ~"".

**Comment by bdkjones** [comment]
This is an issue with Less itself, not CodeKit. Please open a bug on the Less.js GitHub page; there's nothing I can do to solve this problem.

**Comment by jvsummeren** [comment]
I downgraded Codekit to v1.2.2 (build 6502) to make sure my assumption was wrong, but actually this version compiles it right.

Both v1.2.2 and v1.2.3 use the same Less version, which haven't been updated in a while (1.3.0).

I installed the Less command line compiler (also v1.3.0) and my file also compiles correctly.

Can you reopen this ticket to investigate this matter?

**Comment by bdkjones** [comment]
CodeKit 1.2.2 uses an older build of Less.js 1.3.0. 

CodeKit 1.2.3 uses a newer build with commits from just a week ago. This build is also "officially" listed as 1.3.0, although it's actually a bleeding-edge release. The behavior you're seeing must have been introduced with this newer version of Less, so it should be fairly easy for the Less guys to track down the change that caused it.

**Comment by jvsummeren** [comment]
Fixed in Less now: https://github.com/cloudhead/less.js/commit/be74f9a8373de666942c97668c7b6ad6b409bcec

**Comment by bdkjones** [comment]
Excellent. This will make it into the next release of CodeKit then.

**Comment by jvsummeren** [comment]
This problem is still present in Codekit 1.2.6. Is the fix in Less.js incorrect?

**Comment by bdkjones** [comment]
Ah, I forgot to upgrade Less.js when I released the last build of CodeKit. Will do it for the next one.
