### ISSUE TITLE
Hang on concat and minify

### ISSUE THREAD

**Issue by Gidgidonihah** [bdkjones/CodeKit-1-Old#39]
I've been using basically 1 file broken up into a handful to test the app. It has been working great until today. Whenever I save the file CodeKit attempts to concat & minify, but it hangs. It will eventually recover and the file will be happily processed, but it takes forever. If I save several times while codekit is unresponsive, I will get the same number of growl notifications saying it completed, all at once, when it is finished.

I'd love to give more info for a better diagnosis, but I don't know what that info would be.

**Comment by bdkjones** [comment]
Which build are you running? (CodeKit > About)

The latest builds have a ton of fixes and changes to the javascript and coffeescript workflows. The current build is 3558, although only two people are running that one.

**Comment by Gidgidonihah** [comment]
Currently running 3065.

**Comment by bdkjones** [comment]
Yea, we need to get you testing the latest build. What's your email address?

**Comment by Gidgidonihah** [comment]
Sent.

**Comment by bdkjones** [comment]
Have you been able to reproduce this issue with the newest build? I cannot over here.

**Comment by bdkjones** [comment]
I can't reproduce this on my end, and haven't heard back, so I'm closing it for now.
