### ISSUE TITLE
notifications not working

### ISSUE THREAD

**Issue by matthacksteiner** [bdkjones/CodeKit-1-Old#393]
Hi,

the new "Mountain Lion notifications" are not showing up. 
I can see Codekit in the system preferences and it's assigned to banner...
version 1.2.5  OSX 10.8

**Comment by bdkjones** [comment]
Is the "Show Notifications" checkbox in CodeKit's preferences window enabled?

**Comment by matthacksteiner** [comment]
yes, checkbox enabled. Still having the same issue with 1.2.6

**Comment by bdkjones** [comment]
Hmm, you're the only person reporting this issue so I have to assume right now that there is something unique about your machine that's causing the behavior.

Can you try creating a new user account and running the app from there? Alternately, delete ~/Library/Preferences/com.incident57.codekit with the app not running. Then relaunch it and see if that helps.

**Comment by bdkjones** [comment]
Also: do you have Growl installed on your system?

**Comment by matthacksteiner** [comment]
yep. tried to disable codekit in growl preferences - still the same

**Comment by matthacksteiner** [comment]
deleting the preferences files didn't do the trick either... strange.
I have the same issue with my personal Mac and my Mac at work.

**Comment by matthacksteiner** [comment]
it's working now! don't now why but I don't care ;)

BTW. Preferences to switch from NC to Growl would be great!

Thanks
