### ISSUE TITLE
Please remove trailing whitespace when importing coffee files during compilation

### ISSUE THREAD

**Issue by bfricka** [bdkjones/CodeKit-1-Old#394]
First of all, thank you for CodeKit.  I love it.

So this is a minor quip.  When I import coffee files to compile out to a single JS file, CodeKit divides the code into commented sections based on the name of the coffee file.  While I don't mind this, it does introduce a trailing whitespace at the end of the first two lines.  And by default, JS Hint linting checks for trailing whitespace and will always throw an error.  

Thus, the default behavior in CodeKit when importing coffee files is to throw a linting error.  This seems like it should be fixed.  Of course I can disable trailing checks, and it's not going to occur if the output is minified, but that's not really the point.

Could you remove the trailing whitespace from the output?  Thanks!

Example where the underscore represents the trailing space:

```
/* --------------------------------------------_
     Begin directives.coffee_
--------------------------------------------
*/
```

**Comment by bdkjones** [comment]
Done and done. 

This will ship in the next update. Thanks for the report.
