### ISSUE TITLE
LESS compiler not working v1.2.6

### ISSUE THREAD

**Issue by rickblackdog** [bdkjones/CodeKit-1-Old#398]
Latest version appears to have killed the LESS compiler (OS 10.8, codekit v1.2.6). completely.

**Comment by mcmillion** [comment]
I've noticed this as well.  Compilation is successful, but the output files are blank.

**Comment by bdkjones** [comment]
Hi guys,

It's almost certain that the problem is in your code. I can definitely attest that the Less compiler is working in 1.2.6. Can you replicate the issue with ALL Less files that you try?

**Comment by mcmillion** [comment]
Nope, just found the cause.  It's an issue related to the import chaining (which is discussed in another thread), and most definitely isn't my Less code.
