### ISSUE TITLE
Changing items in the hidden folders/files lists doesn't remove/add those items from/to existing projects

### ISSUE THREAD

**Issue by mishunov** [bdkjones/CodeKit-1-Old#4]

**Comment by bdkjones** [comment]
After lots of thought, I've decided to mark this "behaves as intended."

In general, the preferences regarding output paths and hidden/ignored items apply only to projects that you add from that point forward. This is so we don't undo any specific changes you've made to existing projects.

If I re-evaluated all the hidden/ignored items in EXISTING projects every time the user changed the preferences, I would potentially un-hide or un-ignore files that the user individually set to hide or ignore. (And vice versa.) Not good.

I'm open to changing this behavior in the future, if most folks expect it to work differently.
