### ISSUE TITLE
CodeKit chokes on Twitter Bootstrap's .hide-text mixin

### ISSUE THREAD

**Issue by httpster** [bdkjones/CodeKit-1-Old#400]
CodeKit 1.2.6 (6708) is not correctly compiling Twitter Bootstrap's .hide-text mixin. Specifically the short-hand font property. The compiled css is missing the font-size and line-height.

Twitter Bootstrap's .hide-text font property:

font: 0/0 a;

CodeKit's compiled css:

font: a;

**Comment by bdkjones** [comment]
This is not a CodeKit issue; this is an issue with Less.js. I _think_ they recently fixed it in a new build, so hopefully it will be resolved in the next CodeKit update when I update the Less components.
