### ISSUE TITLE
Exclude Files and Directories (or .gitignore)

### ISSUE THREAD

**Issue by parisholley** [bdkjones/CodeKit-1-Old#401]
It becomes very useful when doing node.js development as a node_modules directory is in my project root and i'd like to just exclude it all together as it ads tons of files I need to weed through. Even better kudos if codekit could look at .gitignore and use that to ignore files.

**Comment by bdkjones** [comment]
Preferences > Skipped Items

You'll need to add the entry to the skipped items list before adding the project with the folder that you want to skip.

**Comment by parisholley** [comment]
That is problematic as many languages/frameworks will randomly be adding folders/generated content on the go, there needs to be a way to exclude them after the fact.

If I am exporting my settings to disk and try to reimport the project, will it read that setting and update my settings? It isn't feasible to go in and customize your project (ie: don't directly compile on tons of files) and have to throw it away because in the future you have new folders you want to exclude.
