### ISSUE TITLE
Import/Extends not working on jade

### ISSUE THREAD

**Issue by parisholley** [bdkjones/CodeKit-1-Old#402]
I am unable to drag imports/extends into the boxes on the right. I assume this would allow me to edit a parent template without having to retouch all of the children (which I have to do currently)

**Comment by bdkjones** [comment]
Jade files do not support drag/drop imports. This is because Jade has official statements that you use in the files themselves to include another file or to indicate that a file extends another.

The drag/drop approach is for languages that lack those types of statements: Javascript & CoffeeScript.

**Comment by parisholley** [comment]
Correct, but in my case, I am using codekit and jade for simple html templating, it isn't being parsed by a web service (ie: node). It would be nice if I could optionally tell codekit to detect when "extends" i specify is updated so it will reprocess the child pages that use them, as right now, I have to touch every file when editing a parent that is extended

**Comment by bdkjones** [comment]
Have you updated to the latest version? One of the new features was support for the "extends" keyword. The app will not detect "extends" statements and establish links between the relavent files so that everything gets recompiled correctly when a change occurs.

**Comment by parisholley** [comment]
Yes, I am on 1.2.6 and I don't see that behavior. I have to touch the child jade file to see a refresh.

**Comment by parisholley** [comment]
appears to work now, not sure what was causing the issue
