### ISSUE TITLE
Multiple Codekit windows

### ISSUE THREAD

**Issue by ghettosoak** [bdkjones/CodeKit-1-Old#405]
Would there be any way that you could have multiple codekit windows open at once? I'm always jumping between projects, and, now that I'm integrating everything into codekit (thereby making everything sexier), it would be great to have an individual codekit window dedicated to the project at hand, versus dragging it around from project to project like a punkass nephew at the mall.

A million thank yous for the awesome program! : )

**Comment by bdkjones** [comment]
Unfortunately, given the way the app is built, this is not possible without a (pretty much) ground-up re-architecting. Sorry!
