### ISSUE TITLE
Project config doesn't update unless project is reimported?

### ISSUE THREAD

**Issue by parisholley** [bdkjones/CodeKit-1-Old#409]
This may be a "feature request", but unintended behavior currently. I swap between a laptop and desktop and keep my code stored in git. If the codekit-config.json is updated I have to delete and reimport the project on another computer to get the new changes in, I would expect the settings to be automaticly sync up.

**Comment by bdkjones** [comment]
Implemented in 1.3.1.

**Comment by parisholley** [comment]
thanks for getting this in there! much appreciated..
