### ISSUE TITLE
Feature Request: Detect imports on modifications (LESS)

### ISSUE THREAD

**Issue by parisholley** [bdkjones/CodeKit-1-Old#411]
When project auto-refresh is disabled (or hasn't ran yet), if I modify a less file and add new imports, codekit should detect new imports were added. Currently it does not, so if I modify the child file, the paren't doesn't get triggered unless a refresh on the parent has happened after I added the import statement.

**Comment by bdkjones** [comment]
Something isn't right. CodeKit scans for new @import statements each time you save the file. Please send me the project that's not working so I can take a look over here.

**Comment by parisholley** [comment]
wasn't able to reproduce on a clean project
