### ISSUE TITLE
freezes or becomes unresponsive

### ISSUE THREAD

**Issue by simply-simpy** [bdkjones/CodeKit-1-Old#415]
I am having frequent issues with CK freezing, becoming unresponsive, or taking 2-3 minutes to compile (maybe it is trying to compile during these freezing episodes). I have been using CK for approximately 2-3 months. It seems this issue is more prevalent on the current release.

**Comment by bdkjones** [comment]
Have you tried resetting the app by quitting it and then relaunching it while holding down shift?

**Comment by simply-simpy** [comment]
I did today for the first time. I will let you know if that helps. I am not sure if it is related or not, but Chrome crashes a fair amount for me as well. I am up-to-date on software.

**Comment by bdkjones** [comment]
Are you running any extensions in chrome? If so, try disabling them.

**Comment by simply-simpy** [comment]
It seems to be fine today -- probably an extension in Chrome. Thanks!
