### ISSUE TITLE
JS is being run through JSHint/JSLint

### ISSUE THREAD

**Issue by leepowelldev** [bdkjones/CodeKit-1-Old#417]
JS is being run through JSHint/JSLint even though in the preferences I have set all javascript not to be...

**Comment by bdkjones** [comment]
I'm assuming that since you closed this, you discovered that the preferences window simply sets the initial options for files in projects. Changing the preferences does not update files that are already in the app.

**Comment by leepowelldev** [comment]
Yeah, schoolboy error...
