### ISSUE TITLE
Is there a way Codekit can use Less's new debug mode with line numbers?

### ISSUE THREAD

**Issue by sciascia** [bdkjones/CodeKit-1-Old#418]
https://github.com/cloudhead/less.js/pull/955

I can see `"lessOutputStyle" : 0,` in the project json file but am not really sure what to do - looks like the new modes are:

```
  window.less.dumpLineNumbers = 'comments'; // Comments mode
  window.less.dumpLineNumbers = 'mediaquery'; // Media query mode
  window.less.dumpLineNumbers = 'all'; // Both mode
```

I manually updated codekit's less version but don't really understand how to configure the output manually sorry.

Any pointers in the right direction would be much appreciated.

Cheers

Ben

**Comment by bdkjones** [comment]
Hi Ben,

```
It will be available in the next update.
```

-Bryan

**Comment by sciascia** [comment]
Awesome mate - cheers
