### ISSUE TITLE
slim files with utf8 encoding and umlauts

### ISSUE THREAD

**Issue by jweidler** [bdkjones/CodeKit-1-Old#420]
Hi Bryan,

slim files that are encoded in utf8 and contain umlauts as in »persönlich« compile to, in this case, »persÃ¶nlich«. Once I save my file with ISO 8859-1 encoding it works as I would expect it to work with utf8 encoding. I am using Sublime for editing. Who or what is wrong?

Kind regards and good luck with your campaign :-), 
we're crossing our fingers over here.
Jonas

**Comment by bdkjones** [comment]
Hi Jonas,

```
You'd need to contact the Slim developer. CodeKit simply runs the Slim compiler, and this is an issue with that compiler itself. Thanks for your support!
```

-Bryan

**Comment by jweidler** [comment]
Hi Bryan,

thanks for your quick reply. Makes sense, will get in contact with those guys then.

Good day!
Jonas
