### ISSUE TITLE
Feature Request: Concatenate + minify in two distinct files

### ISSUE THREAD

**Issue by matthiasbreuer** [bdkjones/CodeKit-1-Old#423]
It would be really cool to have the option to save both the concatenated and the then minified file separately so one can debug with the concatenated version and use the concatenated+minified version for deployment.

For example:
input and imports: **file.js, file2.js ...**
concatenate: **file.cnct.js**
concatenate + minfiy: **file.min.js**

**Comment by blaircam** [comment]
I would totally agree with this. I currently do this for our css using two distinct 'sass --watch' calls through the command-line.

Although the file saving spec in the example would be too specific to make this feature truly awesome. If you could choose the compile spec for each of the multiple locations you want to save the file into - that would be awesome.

**Comment by bdkjones** [comment]
Oh, I wouldn't worry about it. Something awesome this way comes...

**Comment by blaircam** [comment]
What a guy … :)  I look forward to the awesomeness.
Great to hear from you directly.

=) B

**Comment by bdkjones** [comment]
You won't need two files. I've spent many, many hours deciphering sourcemaps to solve this very issue.

Essentially, you'll check one box in CodeKit and one box in Chrome, and then you'll be able to see your UNMINIFIED javascript in the console within Chrome, but have only the minified file in your website's folder. It's really freaking sweet now that I've got it working.

**Comment by bdkjones** [comment]
Also, if you want to do this with Sass, you just need to create two "master files" that import all the others for a given stylesheet. Set one master file to minify, set the other to not minify. Then, whenever you change an imported file, CodeKit will recompile both master files automatically.

Finally, Sass has introduced sourcemap support, which will be coming to CodeKit.

**Comment by blaircam** [comment]
Ahhh ... that bit makes sense. An easy work around with Sass. Like it.

Thanks!

**Comment by matthiasbreuer** [comment]
Wow, this is great news!

Am 18.01.2013 um 04:04 schrieb bdkjones notifications@github.com:
