### ISSUE TITLE
Unable to figure out how to remove an imported js file

### ISSUE THREAD

**Issue by b00y0h** [bdkjones/CodeKit-1-Old#425]
after realizing that it's not a good idea to import a minified js file, I find no way to remove this file from the import box.

http://d.pr/i/tnGe

**Comment by b00y0h** [comment]
fixed. had used 

``` javascript
  // @codekit-prepend
```

in my application.js file instead of drag/drop. :/

**Comment by bdkjones** [comment]
Right-click the file and choose "remove". Thanks for the feedback!
