### ISSUE TITLE
UI bug: Scrollbar covers checkboxes

### ISSUE THREAD

**Issue by pietvanzoen** [bdkjones/CodeKit-1-Old#426]
A small UI annoyance. When I go to check/uncheck a project just after scrolling the scrollbar interferes with clicking the checkbox.

Screenshot: http://cl.ly/KT1Y

**Comment by bdkjones** [comment]
Yep. There's nothing I can do about it though; this was Apple's decision on how to implement the overlay scrollers. This ticks me off in a lot of other apps that I use, so I feel your pain.

**Comment by pietvanzoen** [comment]
Well balls. Apple strikes again.
