### ISSUE TITLE
Chrome stops reloading, then reloads every second consecutively

### ISSUE THREAD

**Issue by elado** [bdkjones/CodeKit-1-Old#427]
Happens with .slim/.coffee files, when the browser needs to reload the page.

CodeKit "loses" control over chrome for a while (so I reload manually), and then it reloads the page several times in a row. Sometimes it gets the reload control back, sometimes it doesn't. When it doesn't, restarting CodeKit helps, but that behavior may return not long after that.

OS X 10.8, tried with latest release of Chrome and also Chrome Canary, same behavior.

**Comment by bdkjones** [comment]
Do you have any extensions installed in Chrome? If so, disable them. This is the leading cause of issues with reloading.

**Comment by bdkjones** [comment]
Haven't heard back on this, but several reload-related improvements were introduced in 1.3.1. Let me know if this is still an issue.

**Comment by elado** [comment]
It's less frequent but still happens. Next time it is, is there anything I can do to help detect it the problem?

I have many extensions, and since this problem is not consistent it would require me to disable all extensions for an unknown period.

**Comment by bdkjones** [comment]
Start by disabling any extensions that manipulate the DOM. Things like Adobe Edge Inspect, etc. Those are frequently the ones that cause trouble. Extensions such as adblockers, 1Password, Ghostery, and so on are not a problem.

**Comment by elado** [comment]
I don't use Adobe Edge. I don't see any extension that changes the DOM except adblock/lastpass (which are disabled on localhost).

In a full work day it happened once or twice.
