### ISSUE TITLE
CSS Inject via ?now=

### ISSUE THREAD

**Issue by michaelprobst** [bdkjones/CodeKit-1-Old#428]
The live CSS reload via ?now=[timestamp] does not check whether the existing url for a stylesheet already has a query string. A dynamic stylesheet generated via query parameters breaks when CSS Injection is enabled.

**Comment by bdkjones** [comment]
I'm on it. Will fix in the next update.

**Comment by bdkjones** [comment]
Fixed in 1.4. Will be released soon. Thanks!
