### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by jackdent** [bdkjones/CodeKit-1-Old#432]
In certain folders, CodeKit won't compile. However, if you copy the same exact file to your Desktop, or sometimes even the parent directory, it compiles successfully.

http://cl.ly/image/1N1x2y09200y

**Comment by bdkjones** [comment]
This isn't an issue with the app; this is an issue with permissions on your machine. You should ensure that the user account you're running under has read/write access to the project folder AND all subfolders/files in that tree.

**Comment by bdkjones** [comment]
Right click on the folder, choose "get info". At the bottom is a permissions area. Set read/write and then apply to all enclosed items with the button.
