### ISSUE TITLE
Advanced Usage of &/reverse nesting with tabs

### ISSUE THREAD

**Issue by alexroper** [bdkjones/CodeKit-1-Old#435]
I get a ParseError when using & to reverse the ordering of a mixin when there is a tab between the ampersand and the curly brace.

So this works:

```
.child, .sibling {
    .parent & {
        color: black;
    }
}
```

But this results in a ParseError:

```
.child, .sibling {
    .parent &   {
        color: black;
    }
}
```

Spaces between the ampersand and curly brace don't seem to affect it, just tabs.

This example was take from the LESS documentation:
[`http://lesscss.org/#-advanced-usage-of-&amp;`](http://lesscss.org/#-advanced-usage-of-&amp;)

**Comment by bdkjones** [comment]
Should be resolved with an imminent update that brings along Less 1.3.1.
