### ISSUE TITLE
Advanced Usage of &  with adjacent sibling combinator

### ISSUE THREAD

**Issue by alexroper** [bdkjones/CodeKit-1-Old#436]
The following code results in a ParseError when trying to use ampersands to reverse nesting and the adjacent sibling combinator. This code is taken from the LESS documentation:

[`http://lesscss.org/#-advanced-usage-of-&amp;`](http://lesscss.org/#-advanced-usage-of-&amp;)

```
.child, .sibling {
    & + & {
        color: red;
    }
}
```

**Comment by bdkjones** [comment]
Should be resolved with an imminent update that brings along Less 1.3.1.
