### ISSUE TITLE
CodeKit assumes rgba() to be a mixin in some cases

### ISSUE THREAD

**Issue by lmazurek** [bdkjones/CodeKit-1-Old#437]
Hi there,

Lets assume I have the following variables:

<pre>
@linkColor: #D67719;
@linkColor-R: red(@linkColor); // value of red channel in linkColor
@linkColor-G: green(@linkColor); // value of green channel in linkColor
@linkColor-B: blue(@linkColor); // value of blue channel in linkColor
</pre>

If I want to display link Color as RGB like this:

<pre>
@tableBackgroundHover: rgba(@linkColor-R, @linkColor-G, @linkColor-B, 0.1);
</pre>

CodeKit shows an error:

> RuntimeError: error evaluating function `rgba`: color functions take numbers as parameters in ...

I'm not sure if I'm doing this the right way, maybe the error is on my side. Hope you can check where the problem lies

Cheers
Lukasz

**Comment by bdkjones** [comment]
Hi Lukasz,

This isn't an issue with CodeKit; this is an issue with Less itself. Please update to CodeKit 1.3 and see if the new version of Less included with that update resolves this issue. If not, you'll want to file a bug report on the Less.js page. Thanks!
