### ISSUE TITLE
Missing space after 'function' annoying warning with new update

### ISSUE THREAD

**Issue by hectorfhurtado** [bdkjones/CodeKit-1-Old#438]
Hi, with this new update it keeps throwing that warning. I'm writing CoffeeScript files, so the spacing is taken care of Codekit itself. Even it compiles as usual, it's really annoying.

Thanks in advance, Codekit is great, you've made a great tool

Hector

**Comment by bdkjones** [comment]
Which tool are you using to check the output -- JSHint or JSLint?

CoffeeScript's compiler is not set up to generate JS code that passes EITHER of those tools completely. Instead, CS checks its output with "JavascriptLint", a different tool. I'll be implementing that in the next update.

**Comment by hectorfhurtado** [comment]
Hi, I tried with both.

**Comment by ingowennemaring** [comment]
I can confirm that and I would love to see it fixed. :-)

**Comment by masterful** [comment]
just sent a tweet about it - but saw that you prefer issues in Github - glad to see I'm not the only user with this issue.

I believe it's a relatively straightforward fix? (hopefully)

we just need to enable the "white" relaxation option in JSHint as well - I tried switching to JSLint and enabling the option though - and that didn't seem to do the trick. So not sure what's going on there ...

**Comment by moomadcow** [comment]
I'm seeing the same thing. It's telling me I'm missing space after every function, (), .. etc... it's super annoying and there's no way to turn it off.

**Comment by bdkjones** [comment]
It's a bug in JSHint, I believe. You can add a JSHint comment to the top of the file to set the "white" option until I can update CodeKit with a fixed version of JSHint. See the JSHint site for more details.

**Comment by bdkjones** [comment]
Fixed in 1.3.1
