### ISSUE TITLE
Unhelpful Less error messages

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#44]
See [this screenshot](http://db.tt/P33NA4t).

**Comment by bdkjones** [comment]
Can you send me the file that is producing this error?

-Bryan

**Comment by paulyoung** [comment]
As usual it's under NDA but I'll recreate something.

Possibly related - I just re-opened the app after this and it appears to be stuck on the initial refresh. The progress bar has been going for a while now with no change.

**Comment by paulyoung** [comment]
[Here's](http://db.tt/p1jQdFr) an example.

Now I'm seeing something really screwy. Going to reproduce and create a new issue.
