### ISSUE TITLE
codekit-config.json: Keep it in the app and option to export it?

### ISSUE THREAD

**Issue by ialphan** [bdkjones/CodeKit-1-Old#441]
With 1.3 CodeKit started creating "codekit-config.json" in the project root folder. I understand the idea behind and it's great. 
But... it's another file in my directory that can be kept to the application. Is there anyway we can have the option to keep these settings in the app (perhaps be able to export it later)?

**Comment by bdkjones** [comment]
Of course. All you need to do is right-click the project, choose "Edit Project Settings". In the general tab, uncheck the "update automatically" option below the config file section. Then, delete the configuration file.

**Comment by ialphan** [comment]
Great, thanks.
