### ISSUE TITLE
Codekit adding ?ck=xxxx to url after save

### ISSUE THREAD

**Issue by Braveatom** [bdkjones/CodeKit-1-Old#444]
Before the recent update it didn't. It has turned this URL

http://dev.myurl.com/#/

to this

http://dev.myurl.com/#/?ck=374501539.915961

The old way worked better - now in my AJAX site it requires me to manually remove the extra characters to test

**Comment by bdkjones** [comment]
This is a cache buster that forces the browser to reload the page from disk rather than the cache so that your latest changes are always displayed. 

I realize some folks need to disable that, so the option to do so will be available in the next update, which should be out in a week or two. Thanks!

**Comment by Braveatom** [comment]
Awesome, thanks for the update
