### ISSUE TITLE
LESS compiles very very slow.

### ISSUE THREAD

**Issue by ericbae** [bdkjones/CodeKit-1-Old#445]
Unlike previous versions of CodeKit, it now seems that LESS files are compiled far slower. So editing different less files and saving them frequently causes machine CPU to spike.

**Comment by michaelprobst** [comment]
I have also noticed that with this version is appends at query string to the URL i.e. ?ck=[timestamp]

I am also experiencing the long delay between SASS compile and browser update/ CSS transition.

**Comment by bdkjones** [comment]
It's possible that you guys have a corrupt model file. Try quitting the app and relaunching it while holding down the shift key. This will clear everything out and give you a fresh start. Let me know if that resolves the issue. Thanks!

**Comment by michaelprobst** [comment]
that appears to have resolved the issue for me once I added all my projects back in.

**Comment by ericbae** [comment]
Hm. I tried that, but I'm not sure how much that helped. LESS compilation I believe still takes considerably longer than the previous CodeKit versions.

**Comment by bdkjones** [comment]
Ok. Can you send me the files that demonstrate the issue so I can test over here?

**Comment by ericbae** [comment]
Hi

I've attached a zipped file of my CSS folder.

Thanks.

**Comment by bdkjones** [comment]
Github strips attachments. You'll need to email me directly or upload it and send me a link.

**Comment by ericbae** [comment]
Oops. sorry. here. https://dl.dropbox.com/u/33161452/css.zip

**Comment by bdkjones** [comment]
I'm showing a compile time of about 0.5 seconds, which is just about as fast as it gets. How long is it taking on your machine? What hardware and OS version are you on? Which editor are you using? Have you tried a full reboot of your Mac to see if that helps free up system resources?

Are you sure the _compiling_ is what's slow, or is CodeKit slow to refresh your browser? If the latter, are you running any browser extensions? If so, disable them. Not all are compatible with the injection that CodeKit performs.

**Comment by ericbae** [comment]
I've got an average time of 10 seconds. This never used to happen.

I've got pretty much the latest Macbook air, Mountain lion. I'm editing the
less files through Eclipse.

I'm not refreshing the browser automatically. So it's the compiling that's
taking time.

That's strange. I've got CodeKit 1.3.1 (7839).

**Comment by bdkjones** [comment]
Can you try a different editor and see if the problem persists? Eclipse is Java-based, and those are not really compatible with modern APIs on OS X. 

Also, a system reboot -- have you tried that?

**Comment by ericbae** [comment]
Just tried editing the file via VIM. same thing - 9-10 seconds.

Rebooted my Mac and it's the same.

I also tried downloading the CodeKit again fresh, but it's still taking
awhile.

**Comment by bdkjones** [comment]
What about if you select "main.less" in CodeKit and click the "Compile" button? How long does that take?

Also, what apps are running on your system?

**Comment by ericbae** [comment]
ok. I went through each of my ".less" files and found out that
"content.less" was causing the slow down.

I went through the styles, but didn't find anything troubling. Does "deep"
nesting of elements cause long delays?

I guess I can re-organize the elements and remove redundant ones.

Strange how this particular less file is causing it though.

**Comment by ericbae** [comment]
In one of my style elements, I had something like this..

ul#list1, ul#list2, ul#list3, ul#list4 {

  ....

  li.list1, li.list2, li.list3, li.list4 {
  ...
  }
}

So I removed all those redundant ones and it seems like everything is back to how it should be.... is there a particular reason that CodeKit can't handle above cases?

**Comment by bdkjones** [comment]
Huh. I'm glad you got it working.

It sounds like the issue was not CodeKit's fault. CodeKit just runs the standard Less compiler, which you can run at the command line as well. Did you try compiling the original files from the command line directly to see how long that took? My guess is that you'd find it took the same amount of time.

It is interesting that the original files compiled so quickly when I tested over here, but that may be due to my hardware.
