### ISSUE TITLE
Can't open file for writing...

### ISSUE THREAD

**Issue by geoffoliver** [bdkjones/CodeKit-1-Old#446]
I don't know what happened, but all of a sudden, I can't save a file when CodeKit is watching the project folder. I'm using...

MacVim
OS X 10.8.2
CodeKit 1.3.1

The error I'm getting when I save is `E212: Can't open file for writing`. If I uncheck the project in CodeKit, I can save the file, but CodeKit doesn't see what I've done to it when I re-check the project. It also throws an error compiling the file and the only thing in it is an `@import` for elements.less. 

There's an error in Console.app...

`CodeKit[699]: Unable to open file for @import linking.
No links established for: /path/to/my/project/less/site.less`

So I have no clue what is going on here. Any ideas?

**Comment by bdkjones** [comment]
Have you changed MacVim's settings as specified on the CodeKit Help page? http://incident57.com/codekit/help.php

You'll need to do that. Also, have you verified that you have read/write access to all folders and files in the project? This may be a permissions issue with OS X.

**Comment by geoffoliver** [comment]
MacVim settings were set. It was some weird permissions issue. Sorry about that.

**Comment by bdkjones** [comment]
No worries; glad you got it sorted out!
