### ISSUE TITLE
CodeKit and Rails

### ISSUE THREAD

**Issue by elado** [bdkjones/CodeKit-1-Old#447]
What are the steps required to make CodeKit work with a Rails project? Not for compiling (Rails does that) but for live reloading.

I get this error message when saving a file, and I'm not sure how to include compass etc.

```
Syntax error: File to import not found or unreadable: compass/reset.
              Load path: /
        on line 1 of /[***]/app/assets/stylesheets/app.css.scss
  Use --trace for backtrace.
```

Thanks.

**Comment by bdkjones** [comment]
Unfortunately, there's no way to accomplish this currently because if CodeKit doesn't handle the compiling, it doesn't have any idea when to reload browsers. Sorry!

**Comment by elado** [comment]
Update: I used Tincr for chrome in order to live reload CSS changes.

Would be awesome to have CodeKit do that, and also watch for HTML/Slim changes and reload those.
