### ISSUE TITLE
Feature Request: Display JSLint/Hint Conflicting Rule-Definition on Error Log Instance(s)

### ISSUE THREAD

**Issue by jrodl3r** [bdkjones/CodeKit-1-Old#449]
It would be awesome to see which jslint/hint rule (title) is being enforced on each individual error log message. nice to have, but would be very useful for some. Thx.

**Comment by bdkjones** [comment]
_Great_ idea. I'll see if I can make that happen. Might take some additions to JSHint/JSLint.

**Comment by jrodl3r** [comment]
Awesome. If there's anything I can do to help/dig on this, fire away..

**Comment by bdkjones** [comment]
I've filed a request with both JSHint and JSLint to add support for this. When they do it, it'll be in CodeKit.
