### ISSUE TITLE
Feature request: Compress/Minify HTML

### ISSUE THREAD

**Issue by ialphan** [bdkjones/CodeKit-1-Old#451]
It would be nice to have an option to minify/compress html files. Thanks.

**Comment by wresin** [comment]
+1

**Comment by degenhard** [comment]
+1

**Comment by rictorres** [comment]
+1

**Comment by bdkjones** [comment]
Not able to do this because every HTML minifier I find has edge cases where it fails and breaks code. When the tools evolve to a better state, I'll put one in CodeKit!
