### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by Cantusstar** [bdkjones/CodeKit-1-Old#453]
I have purchased CodeKit but with the last update (20/11/12) I get the Invalid License popup. I tried to delete the codekit.incident57.codekit.plist file but it doesn't show up in my Preferences Folder. Any ideas?

**Comment by benfrain** [comment]
The com.incident57.codeKit.plist is actually in the user/USERNAME/Library/Preferences/ folder but removing it doesn't negate the issue. It still won't launch for me as of the latest update.

**Comment by bdkjones** [comment]
Hi Ben,

My apologies. Something appears to have been corrupted. Quit the app and delete the preference file as before, then delete the folder ~/Library/CodeKit as well. (You can use the Finder's "go" command from the menu bar to quickly jump to that folder. Make sure you delete the whole folder!)

Then fire up the app and enter your license information. You should be good to go. Sorry for the trouble!

-Bryan

**Comment by benfrain** [comment]
Hi Bryan, that fires up the app (cheers). However, as I'm now on 1.3.5 the licence I'm entering doesn't seem to be valid. Should I try rolling back the app on Time Machine?

**Comment by bdkjones** [comment]
No, send me an email directly at bryan at incident 57 dot com and I'll re-send your license information. It would appear that your original serial number is incorrectly formatted (this sometimes happens with Gmail's web interface --- it adds a bunch of WBR characters)

**Comment by benfrain** [comment]
All sorted now Bryan, thanks for the prompt help.
