### ISSUE TITLE
:hover in less

### ISSUE THREAD

**Issue by john-klungers** [bdkjones/CodeKit-1-Old#454]
I think I found a little bug in CodeKit.
this code in less 

.knopje {
  ...
  line-height: 1.7em;
  :hover{
   .hovereffect(0, @groen + #252525, 40%, @groen + #171717, 60%, @groen + #010101, 100%, @groen + #151515,);
 }

produce this css

.knopje :hover {
...
}

this doesn't do the job
.knopje:hover { 
...
}
does.

workarround: open .css file and replace " :hover" with ":hover"

regards 
J. Klungers

**Comment by opb** [comment]
Looking on the front page of Less (I don't use it myself) they give this example:

#header {
  h1 {
    font-size: 26px;
    font-weight: bold;
  }
  p { font-size: 12px;
    a { text-decoration: none;
      &:hover { border-width: 1px }
    }
  }
}

Note the '&'. I think that makes it 'a:hover' instead of 'a :hover'

**Comment by bdkjones** [comment]
Opd is correct. This is expected behavior.
