### ISSUE TITLE
Feature Request: Don't change codekit-config.json regularly

### ISSUE THREAD

**Issue by nickcatal** [bdkjones/CodeKit-1-Old#455]
I store some of my projects in dropbox and have noticed that codekit is modifying codekit-config.json constantly, causing a huge number of sync events when just leaving the app open.

Not sure if there is a way to prevent that from happening on every check.

**Comment by bdkjones** [comment]
Open the project settings area and look in the general tab. There is a checkbox to disable automatic syncing of this file. Be aware that you'll need to manually export a new one any time you make changes, otherwise those changes won't be synced.

**Comment by nickcatal** [comment]
Noticed that feature literally moments after filing the issue.

Thanks :)
