### ISSUE TITLE
Feature Request: Add "Both" Option to General > "Show App in The:" Dropdown

### ISSUE THREAD

**Issue by jrodl3r** [bdkjones/CodeKit-1-Old#457]
(Low Priority) This will provide a little more visibility/accessibility, with the ability to navigate with CMD-Tab as well as by engaging the Status Bar icon. 
Thx.

**Comment by bdkjones** [comment]
Unfortunately, this isn't currently possible. An app can't run in both the Dock and Menubar at the same time. Apps that provide that functionality are actually two different apps --- one "main" one in the Dock and then a "helper" process that runs in the menubar.
