### ISSUE TITLE
Lots of freezes

### ISSUE THREAD

**Issue by simply-simpy** [bdkjones/CodeKit-1-Old#458]
Am I the only one who has LOTS of freezes with CK? Generally It happens like this: All of my browser windows refresh, and CK has locked. I have reinstalled CK and  reinstalled Chrome, deleting Chrome preference files. I am running 10.8.2 and the latest version of CK. I am to the point of giving up on CK.

**Comment by bdkjones** [comment]
Are you running any browser extensions in Chrome? If so, disable them. They are THE leading cause of problems.

**Comment by simply-simpy** [comment]
The only extension turned on was 'developer mode'. I will turn that off.

**Comment by bdkjones** [comment]
You may also have a corrupt model file. Quit CodeKit and relaunch it while holding down the shift key to clear everything out and get a fresh start. 

Finally, make sure none of your files have infinite import loops AND that your page files are 100% valid. Forgetting to close a p tag, for example, can cause issues during CSS injection.

**Comment by simply-simpy** [comment]
I still have issues.
1. CK Randomly refreshes browsers.
2. CK is then locked.
3. Chrome still works, but I am unable to quit Chrome.
4. I have to force quit both.

I have reinstalled chrome and deleted preference files.

How would I know if I had an infinite import loop? I don't think this is the problem though, because I experience these issues across multiple projects.

**Comment by bdkjones** [comment]
What browser extensions are you running in Chrome?

**Comment by simply-simpy** [comment]
no extensions, 
and the only plugins are:

Chrome PDF Viewer
Native Client
WacomTabletPlugin
