### ISSUE TITLE
Crash when setting output path during refresh

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#47]
I've seen this a couple of times now so thought I better mention it.

This most recent time I only lost a few of the output paths I'd set but previously I think everything was gone and I had to start over.

Might be an edge case as my project is huge.

**Comment by bdkjones** [comment]
Do you mean you're trying to manually set the output path of a file while the app is refreshing?

Or do you mean the refresh process itself tried to set an output path and that caused a crash?

If the first, you should NOT be able to do this during a refresh. I'm working to disable the various commands at appropriate times now.

If the second, I'll need a crash log.

**Comment by paulyoung** [comment]
The first, although maybe 'refresh' is the wrong word. My project is huge so when I first add it, it takes a few minutes for the progress bar to stop, imports to be set up etc. During that time I was setting the output path for .less files.

**Comment by bdkjones** [comment]
Yea... bad user!

The "choose output path" option is now appropriately disabled while the app is busy refreshing or adding new projects/frameworks. 

The reason is a bit complex; but suffice it to say that the model does not expect to be changed externally while it's refreshing.
