### ISSUE TITLE
Failed to initialize the store

### ISSUE THREAD

**Issue by tkane2000** [bdkjones/CodeKit-1-Old#470]
I get 2 alert windows when trying to open the app:
"Multiple validation errors occurred."
then
"Failed to initialize the store"

the main window never opens, but I can get to preferences, etc.  I tried deleting the app, downloading and reinstalling, but no luck.  I get the same errors when i hit 'new project' under the File menu.

Any thought on what this could be?

thanks!

**Comment by bdkjones** [comment]
Quit the app and relaunch it while holding down the shift key. You'll be all set.

**Comment by tkane2000** [comment]
thanks, that did it!
