### ISSUE TITLE
Fatal error with JSHint and JSLint when using accents in strings

### ISSUE THREAD

**Issue by benoitchantre** [bdkjones/CodeKit-1-Old#471]
The check syntax function doesn't work in CodeKit (fatal error) if you have a string containing a letter with an accent.

The online version of JSLint doesn't report any errors when using accents.

**Comment by bdkjones** [comment]
Are you sure the file is UTF-8 encoded? Attempting to use a different encoding, such as UTF-16 or specifying a BOM in the encoding will fail.

**Comment by benoitchantre** [comment]
The file wasn't encoded in UTF-8. When it's encoded in UTF-8, there's no more error. Thanks for your quick answer.
