### ISSUE TITLE
First js import being ignored

### ISSUE THREAD

**Issue by bokkagroup** [bdkjones/CodeKit-1-Old#475]
We had to recompile an older project and it seems the first js file in the list is always ignored.

//HTML5 Forms Polyfil
//@codekit-prepend "jquery.HTML5Support.js";

//TW Boot 2.1 scripts
//@codekit-prepend "bootstrap-collapse.js, bootstrap-modal.js, bootstrap-dropdown.js, bootstrap-alert.js, bootstrap-transition.js, bootstrap-tab.js";

//Flexslider
//@codekit-prepend "jquery.flexslider-2.0.js";

In this case, bootstrap-collapse.js is being ignored. Doesn't even show up on the import list within CK. I've fixed it by making all imports on one line and making the first file "faux.js" that's empty. Working for now but wanted to let you know.

I confirmed the files exist and confirmed it happens regardless of what file is first.

**Comment by bdkjones** [comment]
Thanks Dallas, I'll take a look at this.

**Comment by bdkjones** [comment]
This is a syntax error. You can either wrap each filename in quotes OR not use quotes at all:

```
//@codekit-prepend "someFile.js", "nextFile.js", "thirdFile.js";
//@codekit-prepend someFile.js, nextFile.js, thirdFile.js;
```

What you can't do is wrap all three files into a single set of quotes, as you do now. That's pretty standard across every web language. Remove the quotes and you'll be all set.

**Comment by bokkagroup** [comment]
Interesting. That definitely hasn't changed since the site was originally
built. I think it's the same on a recent site launch as well.

Guess I was getting away with something I shouldn't have. I really
appreciate you looking into it. Sorry it was my mistake.

Sent from my iPhone

On Dec 20, 2012, at 11:24 PM, bdkjones notifications@github.com wrote:

This is a syntax error. You can either wrap each filename in quotes OR not
use quotes at all:

//@codekit-prepend "someFile.js", "nextFile.js", "thirdFile.js";
//@codekit-prepend someFile.js, nextFile.js, thirdFile.js;

What you can't do is wrap all three files into a single set of quotes, as
you do now. That's pretty standard across every web language. Remove the
quotes and you'll be all set.

—
Reply to this email directly or view it on
GitHubhttps://github.com/bdkjones/CodeKit/issues/475#issuecomment-11603872.
