### ISSUE TITLE
Output directory for less files being reset

### ISSUE THREAD

**Issue by icambron** [bdkjones/CodeKit-1-Old#478]
I have a less file I want compiled to a randomish place.

I right click on it and select "Set Output Path". I navigate to where I want it and click "select". The path I selected shows up underneath the less file, so everything looks cool.

But now I edit the file and save it. The file gets built to the default location "/css/myfile.css" and not where I selected. And now when I look at CodeKit, it's got the default location as the output path.

**Comment by bdkjones** [comment]
Are you using Vim? If so, read the section on the help page about it.

**Comment by icambron** [comment]
Ah, I am. I hadn't even thought to look for that kind of thing. Even looking at the help section, though, it's not obvious that my situation qualifies as "you might find that CodeKit is not automatically compiling your files when you save them." It is compiling them, just to the wrong place. So you might want some better docs there.

Anyway, I think I'll pass on getting rid of swap files. Thanks though.
