### ISSUE TITLE
Compass config in subdirectory

### ISSUE THREAD

**Issue by kevinsperrine** [bdkjones/CodeKit-1-Old#484]
I have a build folder where I store my compass config.rb file, and then use relative paths to reference the scss, css, etc., directories. Which seems to work fine at first, but when I try to compile codekit kept giving the error:

```
Compass was unable to compile one or more files in the project: 

You must compile individual stylesheets from the project directory.
```

However, once I moved the config.rb to the project root, codekit was able to compile everything just fine.

**Comment by bdkjones** [comment]
Yea, this is a limitation of Compass and to be quite honest, I've never really understood what it means.

**Comment by kevinsperrine** [comment]
Yeah, I agree. It's a very vague error message. Maybe related to this?

https://github.com/chriseppstein/compass/issues/1004

**Comment by joshuahiggins** [comment]
Anyone have a workaround for this? It drives me nuts not having CodeKit compile my SASS on save. My SASS is in a structure of "/resources/css" while my CSS output is in "/_site/resources/css" and my config files are at the base "/" level.

When I start a new project, usually it compiles just fine with this structure for a while, then randomly it stops working and starts throwing this error.
