### ISSUE TITLE
Modifying new files during launch causes infinite refresh

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#49]
I added some new files to my project and then launched CodeKit. While it was doing the initial refresh I modified the files.

The app now never gets past the initial refresh on launch (the progress bar never stops)

Could be total coincidence so I'll try to reproduce.

**Comment by paulyoung** [comment]
I've tried this a couple of times and the only adverse thing that happened was a crash on next launch, but it wasn't reproducible.

**Comment by paulyoung** [comment]
OK, I stand corrected. I reproduced more accurately by making sure that the new / modified file imported other files in the project.

Infinite refreshing there and then, and on subsequent launches.

**Comment by paulyoung** [comment]
Updated the title of the issue.

**Comment by bdkjones** [comment]
Going to need more specific steps to reproduce.

What did you modify in the files? Did you remove an @import? Did you simply save the file without making any changes, etc.

**Comment by paulyoung** [comment]
I added some @import statements to a less file which already contained @import statements and then saved the file.

I can do a video if that will help.

**Comment by richstandbrook** [comment]
I have had infinite refresh a number of times and the only way I've been able to clear it is removing the codekit file in ~/Library/CodeKit. This mean all my settings, import etc. get wiped. Is there a way to clear the refresh without deleting the data?

**Comment by bdkjones** [comment]
Files can no longer be modified during a refresh. Issue closed.
