### ISSUE TITLE
CSS injection stops working after first save

### ISSUE THREAD

**Issue by dougkulak** [bdkjones/CodeKit-1-Old#490]
Here are my settings:

![Screenshot_1_11_13_10_31_AM](https://f.cloud.github.com/assets/1026183/60719/2485e6b2-5c1d-11e2-9585-a3327b3432fd.png)

The first time I open CodeKit and save an SCSS file, it CSS is generated and successfully injected into both Safari and Chrome. However, subsequent saves are successfully recompiled into CSS but nothing gets injected into the browsers. I do see the requests to load the new CSS files in the browser's "Network" console tab, but only for the first save. The rest of the saves do not appear to be triggering anything on the browsers at all. There are no errors in either the browser console or CodeKit's log. The only way to get it working again is to quit and reopen CodeKit, then refresh the browsers. At this point the CSS injection will work the very first save only again. 

Any ideas?

**Comment by bdkjones** [comment]
This is always caused by one of two things:

1) Browser extensions. If you're running any, disable them.

2) Errors in the DOM. Make sure your page validates as 100% correct HTML. A missing tag, etc will throw things off.

**Comment by dougkulak** [comment]
Just had a couple validation errors and it seems to be fixed now, thanks! There weren't any missing tags or anything, but I had a couple unsupported meta tags.
