### ISSUE TITLE
10 Day Trail Reset

### ISSUE THREAD

**Issue by rohmann** [bdkjones/CodeKit-1-Old#491]
Been using this for a while now and haven't paid up for a license yet... Planning on it soon, but just to let you know, everytime you release an update the 10 day trial starts over. And because you're constantly releasing new versions, it's like an unlimited free trial. Just thought I'd send the heads up - I'm probably not the only one taking advantage of this. (although I really just goof around with less on the weekends, if I was profiting from this app I'd definitely to purchase a license.)

Best Regards,

**Comment by bdkjones** [comment]
Thanks! This is intentional so that folks who try an earlier version but don't like it can come back and try a new one later on.
