### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by soulrider911** [bdkjones/CodeKit-1-Old#494]
I have been using Code kit since the day it came out and I LOVE it, I ran into a problem today I have never seen. All of the sudden code kit stopped compiling? The progress bar just hums along, and it says "compiling" but to no end? would love any help Im using compass and sass.

**Comment by bdkjones** [comment]
The first thing to try is resetting the app. To do that, quit CodeKit and then relaunch it while holding down the shift key. If the issue is due to a corrupt model file, this will fix that.

**Comment by soulrider911** [comment]
Thanks for the reply, ya I had tried that it seems to work temporarily and then it will do this never ending compiling again. Its really weird, I noticed If I just change a few things, it wont dot, then it will come back super frustrating cant figure it out. Very sporadic.

**Comment by soulrider911** [comment]
I think this might be part of the problem, I get this error every now and then, but dunno how to resolve it
![Screen Shot 2013-01-17 at 11 13 49 AM](https://f.cloud.github.com/assets/1074696/75881/5dff0a60-60da-11e2-8aae-85c346e011fe.png)

**Comment by bdkjones** [comment]
Hmm, it might be. I'm not very familiar with how the caching system works in Compass/Sass. @Chriseppstein can you give me a brief overview?

**Comment by soulrider911** [comment]
Ok I think I figured it out, I was trying to use @extend inside a media query, and for some reason this was breaking code kit. I think this is a saas issue as when I compiled through the terminal I got an error for every line in my .scss file I attempted to use the @extend inside a media query.

**Comment by bdkjones** [comment]
Nice. That's my favorite kind of bug: one that isn't my fault!
