### ISSUE TITLE
Feature request: control auto-refresh of project

### ISSUE THREAD

**Issue by nixstrom** [bdkjones/CodeKit-1-Old#498]
Once in a while, CK will attempt to refresh your project, in case you've added or removed some files, that it didn't notice. That's pretty rad.

However, if you are one of those wretched souls whom are working remotely, and you've lost the connection to the server for whatever reason, CK will still attempt to refresh a folder which just isn't available – and therefore crash.

It would be neat to control the interval at which CK will attempt to refresh the project, or simply disable the feature altogether.

**Comment by bdkjones** [comment]
It's literally item 3 in the first pane of the preferences. :)

**Comment by bdkjones** [comment]
Scratch that; it's item 2.
