### ISSUE TITLE
CSS output folder path doesn't update

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#5]
Specifying the output folder path in a LESS project for individual files has no effect.

The UI doesn't update and the CSS compiles to the incorrect location.

**Comment by paulyoung** [comment]
Updated issue with accurate info. Initially thought that only the UI wasn't updating but the new path is completely ignored.

**Comment by paulyoung** [comment]
Unchecking 'Automatically set the output path for all CSS files...' has no effect.

**Comment by bdkjones** [comment]
Hi Paul,

I can't duplicate this issue. It's working as expected over here: the UI shows the selected output folder and the CSS compiles to the correct location.

Note that you can't set output paths for "missing" files.

Can you do a screencast with Quicktime to record the problem? And which beta build are you running?

**Comment by paulyoung** [comment]
[Screencast](http://db.tt/9JoE3zy)

Build 2343

Notice that it doesn't work the first time but does the second.

**Comment by bdkjones** [comment]
Fixed in build 2388.

Right-clicking a row that's not part of the current selection will now select that row so that it updates correctly when the "choose output folder" panel returns.
