### ISSUE TITLE
Constant refreshing of projects

### ISSUE THREAD

**Issue by gilesbutler** [bdkjones/CodeKit-1-Old#506]
Codekit seems to be refreshing projects very frequently which stops it from compiling & building.

Its very frustrating and slowing me down as im having to wait for Codekit to refresh its projects before I can view my changes.

**Comment by bdkjones** [comment]
Which editor are you using to save your files?

**Comment by gilesbutler** [comment]
Im using Sublime Text 2.

**Comment by bdkjones** [comment]
First, make sure you've got the auto-refresh option disabled (or set to 5 minute intervals) in the preferences window.

Secondly, make sure you have not asked Sublime to save files atomically.

Thirdly, it's possible that your model file has been corrupted. To fix that, quit the app and relaunch it while holding down the shift key. That will clear everything out and give you a fresh start.

**Comment by gilesbutler** [comment]
Thanks for your help.

The auto refresh was already set to 5 minute intervals.
Sublimes auto save is set to false.
I've cleared everything out so will see how it goes, hopefully that'll fix it.

Thanks again.
