### ISSUE TITLE
Feature Request: "Minify only" option for scripts (don't concatenate)

### ISSUE THREAD

**Issue by caleb531** [bdkjones/CodeKit-1-Old#511]
Hi, I have recently started using CodeKit, and so far, I am loving it.
## Introduction

I like how CodeKit can minify my CSS without concatenating my selected stylesheets into one. I prefer this because some stylesheets only apply to certain pages, and therefore, I would not like to combine stylesheets which should not be associated with each other.
## Problem

_However_, all of the output options for my JavaScript files force me to concatenate my scripts. Given the reasons stated above, I do not like this, and I would prefer to minify (compress) each of my JavaScript files without combining any of them.
## Proposal

Therefore, I propose that, in addition to the **Concatenate & minify** option for scripts, that you please add a option that only minifies the selected scripts, without any concatenation.

Thanks,
Caleb

**Comment by bdkjones** [comment]
As long as your JavaScript file does not import others, all you'll get is the minified file. Just don't use any @codekit-prepend/append or drag/drop import links.

**Comment by caleb531** [comment]
Excellent, thanks!
