### ISSUE TITLE
Ignore file/folder per-project

### ISSUE THREAD

**Issue by fform** [bdkjones/CodeKit-1-Old#514]
I need to ignore files/folders configured on a per-project basis.

My specific use-case is a node.js express app. It has /app.js and /routes/_.js. I don't need these concatenated or minified. It'd be nice to lint them, but not essential. I then have some javascript in /src/js/_.js that I do want lint/minified/concat/copied to /public/js/*

CodeKit doesn't seem to have a boundary of what's behind the public folder. It sort of assumes that everything in the folder should be handled by CK. My src folder and tasks folder are in the same level, but they completely differ in how CK should treat them. I do not want to manually mark every new file that's added to a non-compiled folder (and I believe this destroys the reason to use CK in the first place.)

I'm specifically asking for per/project ignores. I realize there is a global setting. That is not what I want.

**Comment by bdkjones** [comment]
Coming in 2.0. 

It required a massive, massive overhaul of how CodeKit organizes files internally, so that's why I've never added this to 1.x. But it's front and center in 2.0 and already working in my early alpha builds.
