### ISSUE TITLE
Feature request: Prevent Actions on git branch switch

### ISSUE THREAD

**Issue by oomlaut** [bdkjones/CodeKit-1-Old#519]
As I usually leave CodeKit running almost all the time, when I switch branches in git, the application will sense that the file has changed and recompile the source code. This usually leads to me cursing, resetting the head in git, and going about my business.

While I'm not generally opposed to cursing, if there's anything that can be done to prevent that middle part, it would sure make my workflow a bit smoother.

Thanks in advance!

**Comment by bdkjones** [comment]
Yep. This is precisely why each project has a checkbox next to it. Uncheck the project before performing any Git actions other than a commit. 

See the help page for a full explanation of why this is needed.

**Comment by tenfef** [comment]
I understand I can do this, but it is a pain to have to remember to uncheck between branches, or forget to and find that CodeKit has crashed. 
There should be a way to detect if thousands are files are changing at once then to stop the project from refreshing/processing?
