### ISSUE TITLE
Feature request: disable button or checkbox

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#52]
Like the checkbox in Less.app to temporarily disable everything without quitting.

I can explain why in further detail if necessary. I wrote out a whole spiel already only to have it not submit properly!

**Comment by paulyoung** [comment]
It would also be _awesome_ if there were separate commands to enable and disable via terminal.

That way I could set up an alias for git pull to "disable" CodeKit first, then pull.

**Comment by bdkjones** [comment]
Hmmm, gonna need the full explanation for why this would be useful.

**Comment by paulyoung** [comment]
I'm using Git (and often Git SVN) and when I do a "git svn rebase" (basically a pull) if files CodeKit is watching are modified then CodeKit tries to compile which halts the whole thing (git says I have unsaved changes and wants to abort).

In Less.app I uncheck the box before a pull "just in case". With CodeKit I have to quit the app "just in case" and since my projects are huge, the initial refresh is time consuming. If I could disable and then pull, if watched files had changed the I would do a manual refresh.

**Comment by paulyoung** [comment]
I now badly need this for another reason.

As you know the project I'm working on is a large one. Some less files are imported in < 10 places, so saving them and having everything compile is not an issue.

Some less files however are imported in 100+ places. If I'm working on a particular page and need to change some code in one of those files, I have to wait 30-60s every time I save for everything to compile. My computer also sometime becomes unresponsive during this time.

Ideally I would disable auto compile and then use "compile selected" on the individual file I need until the end when I would turn auto compile back on and let the changes cascade.(refreshing the project along the way if needed).

Right now I'm simulating this by quitting CodeKit and invoking lessc from terminal with a long and ugly command.

**Comment by bdkjones** [comment]
Just consolidating issues. This one is now open under #189.
