### ISSUE TITLE
Auto-refresh interrupts project setup

### ISSUE THREAD

**Issue by mannieschumpert** [bdkjones/CodeKit-1-Old#521]
This has happened to me a few times now: when setting up a Compass project, I'll be nearing the end of setting all my preferences, and CodeKit will auto refresh, which for some reason triggers the closing of the Compass project setup pane, and there doesn't seem to be a way to get back to that window.

It'd be great if CodeKit could tell if the project setup window was open, and if so, pause refreshing until it's safe to do so without interrupting anything the user is doing.

**Comment by bdkjones** [comment]
Agreed. Will fix!

**Comment by bdkjones** [comment]
Implemented in 2.0.
