### ISSUE TITLE
codekit-config.json always changes when refreshing even without modification to the project

### ISSUE THREAD

**Issue by dismory** [bdkjones/CodeKit-1-Old#539]
This is so annoying for git based project. 

I can not just ignore the `codekit-config.json` file for syncing CodeKit configurations, however, I have to commit each time it changes.

**Comment by CWSpear** [comment]
I agree that this is annoying. bdkjones said he's aware of the issue and that you can have git treat it as a binary in the meantime (see http://stackoverflow.com/questions/11162267/how-do-i-make-git-treat-a-file-as-binary).

As far as I can tell, you can't do something like this in Mercurial. And of course, the project that it's the biggest annoyance for me is an hg project.

**Comment by dismory** [comment]
If `codekit-config.json` file is treated as an binary file by git, does it mean that I **still** have to commit the file every time since it always changes when CodeKit refreshing the project?

**Comment by maebert** [comment]
I think that may be solved with #482

**Comment by dismory** [comment]
@maebert That would be great!
