### ISSUE TITLE
Symlinks Cause an Infinite Number of Files to Be Added to CodeKit

### ISSUE THREAD

**Issue by CWSpear** [bdkjones/CodeKit-1-Old#541]
I have successfully be able to recreate this issue. With this file structure as a CodeKit project:

```
/
/style.css -> css/style.css
/css/
/css/style.css
/sass/
/sass/style.scss
```

where that `style.css` in the root is a symlink created with the command `ln -s css/style.css style.css`.

Every time I refresh that project, it shows a duplicate entry for `/css/style.css`. This seems to continue infinitely. I started getting the error that CodeKit couldn't track more than 10,000 whatever items, and I couldn't figure out why, because it shouldn't be tracking more than 150 files. I found several _thousand_ duplicate files like this in several projects.

I've tried restarting CodeKit, unchecking the projects, but nothing short of removing the projects and re-adding them seems to do anything. And it's just a ticking time bomb before it happens again.

I'm using Version 1.5.1 (8248).

Screenshot of the project used in this example after about a half dozen refreshes:

![There should only be one /css/style.css in this project.](https://f.cloud.github.com/assets/495855/212576/c888312e-8310-11e2-9e64-c04f4f4b8e74.png)

**Comment by bdkjones** [comment]
Yep. For technical reasons, CodeKit does not currently support symlinks. (Not all the tools that CodeKit exposes can work with them). You'll see undefined behavior if you try to use them.

**Comment by CWSpear** [comment]
They couldn't at least be ignored instead of ruining the app, making it pop up so many unnecessary errors it's difficult to use without having to periodically reset projects?

**Comment by daangeerdink** [comment]
This is still very much an issue.
