### ISSUE TITLE
CodeKit 1.6 update causes infinite loop of "refreshing..." / "importing"

### ISSUE THREAD

**Issue by ohokay** [bdkjones/CodeKit-1-Old#545]
CodeKit 1.6 update causes infinite loop of "refreshing..." / "importing" on an existing project with only a few sass and jade files. The described behavior causes CPU usage to raise above 100%.

Thanks!

**Comment by bdkjones** [comment]
Hi Jeff.

Looks like a corrupt model file. To fix, quit the app and relaunch it while holding shift. This clears everything and resets.

-Bryan

**Comment by ohokay** [comment]
Hey Bryan,

I tried that, but it doesn't seem to fix the issue. I also tried removing and reinstalling the app, but the problem persists. Let me know if there is more I can provide to resolve the issue.

Jeff

**Comment by bdkjones** [comment]
In that case, there's likely something wrong with one or more files. Please send me the project so I can test over here.

**Comment by ohokay** [comment]
Seems as though it may have actually been an issue with the project being on Dropbox. Not sure if you know anything about that, but as soon as I pulled it off Dropbox it's been working fine.

**Comment by mettamyron** [comment]
I've got this issue as well. My project is not in dropbox. Shift+ open seems to stop the infinite refresh but as soon as a change is made and saved, it starts up again. I'm using PHPStorm as my editor, but I'm not watching file via this. 
Can confirm that this issue started after I upgraded to 1.6.

**Comment by bdkjones** [comment]
Please send me the project showing the issue so I can test over here. Let me know which files you're saving.

**Comment by mettamyron** [comment]
Hi there,
I have attached the folder being watched in CK. The SCSS and CSS files are
in their respective folders in \library.

Cheers,
Myron

**Comment by mettamyron** [comment]
Ok I deleted a file called "codekit-config.json" and did a SHIFT+ and that
seems to have stopped the refresh loop.

**Comment by bdkjones** [comment]
It's highly likely that you had an infinite import loop set up somehow. Glad you got the issue resolved, though!
