### ISSUE TITLE
Center items in overlay badge

### ISSUE THREAD

**Issue by bdkjones** [bdkjones/CodeKit-1-Old#55]
When you drag items onto the CodeKit window, I'd like the little badge (grey rectangle that comes up in the middle of the window) to center the image and text in the rectangle.

BUT, I'm not _really_ sure if I want this. So I've logged this issue for now.

**Comment by greystate** [comment]
Just go for it man :-)

— and maybe check your back for angry birds coming at you... :-)

Seriously, this CodeKit thing will have my money from day one - awesome stuff!

**Comment by bdkjones** [comment]
Fair enough. I did it.
