### ISSUE TITLE
Feature Request: Reorder project list in sidebar

### ISSUE THREAD

**Issue by oomlaut** [bdkjones/CodeKit-1-Old#550]
I know it's just a cosmetic "nice-to-have" but I'd like to be able to sort and reorder the project list in the sidebar. Is there a different way to do this?

**Comment by bdkjones** [comment]
Coming soon!

**Comment by brendanfalkowski** [comment]
Any word on sorting? My project list is getting a little long in the tooth. Even just alphabetical would be a step up. Folders would be even better.

I could do without Frameworks in the sidebar also, but maybe others use this. I use Compass for everything.

**Comment by bdkjones** [comment]
It's in 2.0, which will be out later this year.
