### ISSUE TITLE
Compile error pops CodeKit window

### ISSUE THREAD

**Issue by henriqueboaventura** [bdkjones/CodeKit-1-Old#553]
Under MacOSX 10.8, everytime that there is a compile error, it keeps showing the CodeKit main window, even if I choose to use desktop notifications under preferences. 

If I check Notifications I guess that it should use it to show de messages, not open the main window everytime.

**Comment by bdkjones** [comment]
You need to uncheck the "bring CodeKit window to the front on error" option in the preferences. That'll do it.
