### ISSUE TITLE
Compiled JS file not working properly on IE8.

### ISSUE THREAD

**Issue by ericbae** [bdkjones/CodeKit-1-Old#556]
I am not sure if this is related to the latest update to CodeKit.

But one of my compiled JS file from CoffeeScript in CodeKit isn't working in IE8 any more.

I've tried to dig through IE Developer Tool and found that the error was being reported in the following lines.

``` javascript
      this["default"] = function() {
        return AlertExplorer.prototype.default.apply(_this, arguments);
      };
....
      this["export"] = function() {
        return ExportAuth.prototype.export.apply(_this, arguments);
      };
```

I've looked at other function declarations and they all do

``` javascript
  this.functionName = function() {
  };
```

So it seems IE8 doesn't like function declarations with square brackets []? Does that even make sense?

For now, I just simply commented the above lines and it worked ok. Does this have anything to do with the latest updated coffeescript in CodeKit?

**Comment by bdkjones** [comment]
This is something you'll have to ask the CoffeeScript guys. CodeKit just runs CoffeeScript, it doesn't actually translate the code itself.
