### ISSUE TITLE
App hangs re-adding a project after 'reached max files' warning

### ISSUE THREAD

**Issue by joshuapaling** [bdkjones/CodeKit-1-Old#559]
I add a project, and get the error message about too many files being watched. I click OK, remove some past projects, and re-add the one I tried to add earlier. The app hangs. Tested three times. If I restart CodeKit after getting the "too many files" message, then I can add the new project fine fine.

Also, what's your suggested workflow for many projects? I want to have many projects in CodeKit, and just check/uncheck the ones that I'm currently working on. But it seems even unchecked projects add towards the count of watched files. Is the only solution to have only a few projects in CodeKit at any time, and completely add / remove projects from CodeKit in order to keep below the watched count?

Seems a hassle for situations when you just want to make a few updates to a site you've done in the past. Any chance of some kind of 'archived projects' feature, so you can keep a list of them, but they don't count towards the watched file count?

**Comment by bdkjones** [comment]
Yep, in 1.x, the best bet is to keep the total number of projects you have in the app at any one time to a minimum. The way I originally envisioned CodeKit was for a web developer who was likely working on just a handful of projects at once. He would work on one and, when it was complete, remove it from the app and add the next website.

Keeping all your projects in the app greatly increases the memory footprint and decreases the responsiveness of the application. This is something that I have optimized in 2.0 and you'll find it's much better. No word on when that will be coming out yet, though!
