### ISSUE TITLE
Imported JS files with no syntax check do get their syntax checked when "host" file is saved

### ISSUE THREAD

**Issue by ddanielou** [bdkjones/CodeKit-1-Old#56]
Tried to make the title as descriptive as I could. If I have some imported files in a JS file with syntax checking activated, these imported files get checked even though they're set not to be checked in the file list. Thus, I keep getting warnings because of some library or other… such as, jquery…This doesn't seem to happen in your video demo, is it a bug or am I the bug?

**Comment by bdkjones** [comment]
Yea... this is an issue that I've gone back and forth on several times.

Currently, it works like this: 

Let X be a JS file that imports Y and Z. We select X in CodeKit and click "Process". CodeKit will look at what syntax checker you've selected for X and will apply that checker to X, Y and Z.

Previously, it worked like this:

When you clicked "Process", CodeKit would look at the syntax checker setting for EACH file, X, Y, and Z and apply that setting to the respective file. So if you had X and Z set to check syntax with JSHint but you had no checker selected for Y, then CodeKit would only check the syntax for X and Z.

The trouble with this second approach is that to disable syntax checking for an import chain, you had to select each individual file in the chain and change the checker setting. This was slow. So I adopted the first method, where we simply use whatever checker you've selected for the base file and apply that to the whole chain.

I am beginning to think a simple "Check imported files" checkbox would solve this issue nicely.

**Comment by ddanielou** [comment]
Hey, thanks for your answer.

A "Check imported files" checkbox would help in the basic "append libraries" scenario, but still…

I'm already experimenting with a "main.js" file whose sole purpose is to put together a bunch of separate scripts, and which basically goes like this:
//@codekit-prepend library1, 2, …
//@codekit-prepend ajax, notifications, animations, you name it…

Not sure about it, it might prove hard to maintain on the long term, I don't know. It could obviously open the door to a whole lot of scoping problems and what not, but right now, it made my code a bit more organized, which I like. Since everyone of these blocks is wrapped into a closure, I don't see much trouble coming up anyway…

Looking some more into this… Let X import Y. Syntax checking is deactivated for X (importer), activated for Y(imported). When we save Y, it checks syntax for both X and Y. When we save X, it doesn't for either. However slower it might be, wouldn't it be more predictable to observe each file's setting?

At the moment, the easiest seems for me to disable syntax checking for all files, and then check them manually. Surely there must be a better way?

**Comment by bdkjones** [comment]
I changed this behavior exactly 20 minutes before I took the app live! All through the private betas it followed the "respect each file's syntax-checking setting" rule. 

I believe I might go back to it; it seems like the simplest solution here.

**Comment by bdkjones** [comment]
I've reverted CodeKit to the previous behavior as of build 3990.

Now I'm gonna have to re-record the damn video... ugh.
