### ISSUE TITLE
Won't compile .less when it contains the filter attribute "saturate"

### ISSUE THREAD

**Issue by Sheraff** [bdkjones/CodeKit-1-Old#561]
Here's the bug report:

undefined_methodError: error evaluating function `saturate`: Object #<Object> has no method 'toHSL' in /Users/Flo/Sites/florianpellet.com/epistolaire/less/polaroid.less:84:12
83 .vintage2{
84  filter:             saturate(200%) sepia(50%);
85  -webkit-filter:     saturate(200%) sepia(50%);

Here's the css file (the one I wanted to convert to .less):
http://florianpellet.com/epistolaire/css/polaroid.css

**Comment by bdkjones** [comment]
Filter statements are not valid CSS and must be escaped in Less in order to compile correctly. Please see the Less.js docs for more details. Thanks!
