### ISSUE TITLE
Not injecting scss styles into browser on save

### ISSUE THREAD

**Issue by wilkesvb** [bdkjones/CodeKit-1-Old#562]
First, love the app. Thanks!

I'm not getting refreshes/injections when I save scss or css files like I used to. Only when saving html files. I'm sure this issue has been had before. Yes, Codekit is aware of all my files and they are linked up properly. Will load new styles when I save index.html but not the scss that I write the new styles in. I disabled all extensions in Chrome as well. Thinking of reinstalling...

Mac OSX, Sublime Text 2, Regular Chrome/Safari

**Comment by bdkjones** [comment]
I'd need to see your project's code to tell you what's going on. For starters, verify that your Link tags to the CSS files are 100% valid. Next, make sure you're not running any Javascript that would interfere with the injections. (Prefix-free.js is the leading offender here.)

**Comment by wilkesvb** [comment]
Yeah I'm not sure what happened but it "fixed itself" or I did something to fix it and didn't realize. I started working right after I created a scss file to import into the global scss. Thanks. 

Vincent Wilkes | Web Design
www.vincentwilkes.com
Twitter Facebook LinkedIn
