### ISSUE TITLE
Always tries to compile js when files are set to 'not compile'

### ISSUE THREAD

**Issue by firedev** [bdkjones/CodeKit-1-Old#565]
I am using CodeKit for compiling Compass/SASS, but every time I save a js file it tries to compile it as well.

I have set all javascript files to 'not compile directly', hid them, removed javascript folder from Compass' config.rb, nothing helps.

It is really annoying and breaks the workflow. Please fix, thank you.

**Comment by bdkjones** [comment]
You can tell CodeKit to skip Javascript files by adding *.js to the Skipped Items list in the preferences window before adding your project to the app.

Alternately, you can set the starting defaults for how Javascript files should be treated in the Preferences section and disable syntax-checking and minification. Those defaults will be applied to new projects added to the app from then on.

Finally, for projects already in the app you can select the JS files and change their settings in the right sidebar.

**Comment by firedev** [comment]
I don't think this should be immediately dismissed, especially considering that it seems impossible to remove all processing for javascript, you can disable JSLint, but you can't disable concatenate and minify:
![](http://d.pr/i/RCTG+)

In the end the settings somehow snapped, but I can guarantee there is an issue there, I am not sure still what finally made Codekit to ignore JS files. I did everything and then maybe restarted codekit before it finally agreed to not do anything with js.

**Comment by bdkjones** [comment]
Earlier versions of the app originally had a "do nothing" option for the "then" field, but this was redundant --- if you don't want CodeKit to do anything with Javascript files, then you simply select "concatenate imported files" and as long as you don't import JS files into each other, CodeKit won't do anything. (If you're importing JS files into each other, you can ONLY do that with CodeKit, so it wouldn't make sense to have CodeKit do nothing in that case.)

However, the removal of the "nothing" option has confused a few folks, so I'm clarifying the situation in 2.0. Thanks!

**Comment by firedev** [comment]
Here is what I don't understand. Here is my project, I just added it. Ok Codekit found a bit of javascript, there are actually 66 js files in that folder but only 4 were found:

![](http://d.pr/i/v5Lu+)

Yet it tries to process application.js that wasn't even auto-detected in project:

![](http://d.pr/i/1tMG+)

**Comment by bdkjones** [comment]
Please send me the project so I can take a look at it over here.

**Comment by firedev** [comment]
Hmm when I started to pack the project, I peeked into codekit-config. Turns out most of the javascript files are actually hidden and ignored in `codekit-config`. Not sure how/when I did that, but I am willing to take the blame.

However `application.js` is set as hidden and ignored as well:

```
  "\/javascripts\/application.js" : {
  "ignoreWasSetByUser" : 1,
  "ignore" : 1,
  "hidden" : 1,
  "outputPathIsSetByUser" : 0,
  "inputAbbreviatedPath" : "\/javascripts\/application.js",
  "outputStyle" : 1,
  "syntaxCheckerStyle" : 1,
  "outputAbbreviatedPath" : "\/javascripts\/application-ck.js",
  "fileType" : 64
},
```

And yet every time I save it, Codekit tries to JSLint the file.

**Comment by bdkjones** [comment]
Glad you figured out the issue!

**Comment by firedev** [comment]
No, sorry, I didn't, the file is clearly set on `ignore` and `hidden` and yet Codekit tries to JSlint it.

**Comment by bdkjones** [comment]
In that case, choose the project in CodeKit, right-click the project and choose "unhide all files", then select "application.js" in the list and change its syntax-checking style in the right-hand pane that pops in.

**Comment by firedev** [comment]
I did unhide all the files and `application.js` is set to not compile directly:
![](http://d.pr/i/Nqwo+)

**Comment by bdkjones** [comment]
Sure, but that doesn't mean CodeKit won't syntax-check it. 

When you check the "do not compile directly" box, what you're telling CodeKit is, "Hey, this file is meant to be imported into others, so you don't need to create an output file when it changes --- instead, go find the file(s) that import this one, and create output files for THOSE files."

The setting you want to change is the next one down: "Check Syntax With".

**Comment by firedev** [comment]
I see, thanks,some global [x] Ignore forever checkbox would really help.
