### ISSUE TITLE
ParseError on Less file when using IE specific @media

### ISSUE THREAD

**Issue by fmarques** [bdkjones/CodeKit-1-Old#566]
The compiler is not allowing to have any of the following blocks:

@media screen\9 {}

@media screen and (min-width:0\0) {}

**Comment by bdkjones** [comment]
This is not an issue with CodeKit; this would need to be opened on the Less.js GitHub page, as it's an issue for the Less compiler itself. Thanks!

**Comment by fmarques** [comment]
Ok i will, thanks!
