### ISSUE TITLE
Codekit is running at 100% of CPU

### ISSUE THREAD

**Issue by fabiozc** [bdkjones/CodeKit-1-Old#570]
Hi! My codekit is refreshing the projects without stops and it is getting 100% of CPU usage

![Screen Shot 2013-04-07 at 6 45 52 PM](https://f.cloud.github.com/assets/1430317/349534/fd3e4272-9fcc-11e2-92fd-95f42b12b898.png)
![Screen Shot 2013-04-07 at 6 47 56 PM](https://f.cloud.github.com/assets/1430317/349535/fd592ec0-9fcc-11e2-8271-42304ac30397.png)
![Screen Shot 2013-04-07 at 6 48 24 PM](https://f.cloud.github.com/assets/1430317/349536/fd5d5888-9fcc-11e2-8283-66662d7c9306.png)

How I can help u to solve this issue?

Thanks

**Comment by bdkjones** [comment]
This is likely caused by a corrupt model file. To fix, quit the app and relaunch it while holding down the shift key. This will clear everything out and give you a fresh start.
