### ISSUE TITLE
Feature Request: Simple if statements in the Kit language

### ISSUE THREAD

**Issue by csoutham** [bdkjones/CodeKit-1-Old#571]
Absolutely love CodeKit, been using it for quite a while for LESS stuff and would recommend to anyone to buy a Mac just to use CodeKit.

Recently had the opportunity to use the Kit language on a very basic HTML website build and there was only one caveat I couldn't do which would have been brilliant.
I had the metadata, footer and a settings include file but I couldn't move the header/navigation to an include file as it needed class=active on the relevant li in the navigation.

As I had the Page name var set up at the top of each page I could have easily done a quick
class="active"

Any chance that could be a feature?

**Comment by bdkjones** [comment]
Basic conditionals are definitely on my to-do list for Kit. Thanks!
