### ISSUE TITLE
Codekit just lost all the project files

### ISSUE THREAD

**Issue by firedev** [bdkjones/CodeKit-1-Old#572]
I didn't do anything, just noticed that the scss is not complied anymore. So I went to check what is wrong and this is what I am left with:

http://d.pr/i/gGBY

This is the same project from #565 

In fact all my projects lost their files. Some are totally empty in codekit, some have a file or two.

So I restarted Codekit and everything got back. Go figure.

**Comment by bdkjones** [comment]
Sounds like a corrupt model file. Quit app, relaunch while holding shift. Then re-add the project.

**Comment by firedev** [comment]
Restarting the app helped.
