### ISSUE TITLE
Feature Request: Activate/Deactivate Frameworks

### ISSUE THREAD

**Issue by csoutham** [bdkjones/CodeKit-1-Old#578]
As each framework file has to have a unique name it makes working with, say, Bootstrap and Flatstrap https://github.com/littlesparkvt/flatstrap (or any Bootstrap variant) on client projects more complicated than perhaps it needs to be.

Although I suspect this is more difficult than I know of, would it be possible to have a tickbox (like Projects) to make a Framework active and get around the unique filenames problem?

**Comment by csoutham** [comment]
Would dearly like to see this become reality - especially now I'm juggling old builds with Bootstrap v2 and newer work with v3.

**Comment by bdkjones** [comment]
Built-in to 2.0.
