### ISSUE TITLE
Is it possible to prevent _*.scss files from being compiled?

### ISSUE THREAD

**Issue by firedev** [bdkjones/CodeKit-1-Old#579]
Hi,

Is it possible to prevent Codekit from compiling files with a certain pattern? `_*.*` for example.

The thing is - when I am switching branches it manages to compile `_files.scss` to `_files.css` and then I have to remove the leftovers manually.

Thanks.

**Comment by stef-rausch** [comment]
Try using the CodeKit > Preferences > Skipped items box.

**Comment by firedev** [comment]
Right, I have used it before, just forgot about it. Thanks!

**Comment by bdkjones** [comment]
You should always uncheck the project in CodeKit's sidebar before you switch branches in Git. This tells CodeKit to ignore all changes in the project until you re-check the project in the sidebar. Cheers!

**Comment by firedev** [comment]
That's too much, I'd rather had a global hotkey that would pause Codekit for all the projects.
