### ISSUE TITLE
Feature Request: Make project-level settings option more visible

### ISSUE THREAD

**Issue by erikwoods** [bdkjones/CodeKit-1-Old#581]
I started to write this long feature request to save and share project settings and to have project-level settings separate from app-level settings - and then I found out that you already have these options. That's great!

So my feature request is for you to make it more obvious. I've been using CodeKit for a few weeks now and it wasn't really obvious to me that you could do this. I know you probably have details about this on your site somewhere but honestly.... I didn't have to use the site a whole lot to learn how to use CodeKit - it's pretty intuitive. Save for this one feature. Maybe you could just add it as an option under File or... add a note about the ability to do so in the generic preferences or something?

Overall feedback on CodeKit: it's pretty awesome. I think on your site, you sort of focus a lot on the auto-refresh feature of it... when, for me, that is not the major selling point. It's a nice feature but I think your biggest selling point should be everything else that it does.

**Comment by bdkjones** [comment]
Thanks! Project-level settings are front and center in the next major release. The whole workflow has been overhauled to emphasize them.

**Comment by erikwoods** [comment]
That is fantastic. Thanks so much for your time and dedication to this project. :-)

**Comment by erikwoods** [comment]
You surely delivered on this in CodeKit 2.0. I upgraded today and I'm loving the updates. Thanks again Bryan.
