### ISSUE TITLE
Vote for App Rename

### ISSUE THREAD

**Issue by lowell** [bdkjones/CodeKit-1-Old#59]
Was the name was chosen because of the Mac convention of using *Kit after a codebase? On Mac OS X, a "kit" refers to a framework or SDK; this has been a convention since it was called NeXTSTEP, with the Foundation Kit and the Application Kit _(for reference, it's been 22 years)_. Referring to an application as a framework can cause confusion; it may even be passed up by someone looking for an app like this because of its name. It's also inaccurate. Further, it's a really cool-looking app, it deserves a better name; hold a competition for one, maybe. Finally, there's already an existing library named [CodeKit](http://www.webbysoft.com/codekit/) that places higher in Google searches for the word _codekit_.

**Comment by bdkjones** [comment]
Nope; I like the name.
