### ISSUE TITLE
Feature Request: Rearrange and Organize Projects

### ISSUE THREAD

**Issue by callaginn** [bdkjones/CodeKit-1-Old#590]
I would like to be able to Rearrange Projects into groups by dragging and dropping. Something very similar to the Favorites sidebar in the latest version of Mac OS X.

**Comment by mikezahno** [comment]
+1

**Comment by rictorres** [comment]
+1

**Comment by bdkjones** [comment]
Implemented in 2.0.

**Comment by rictorres** [comment]
awesome!
