### ISSUE TITLE
CodeKit crashing frequently

### ISSUE THREAD

**Issue by ericbae** [bdkjones/CodeKit-1-Old#594]
I'm not sure how to pinpoint the problem on this one.

CodeKit worked fine until yesterday. But I'm not exactly sure what I did to make it crash constantly. 

So far, it seems to happen each time I refresh my Chrome to see any changes I've done. 

e.g.

I have a project, and I change either JS file or LESS file, and I reload my browser to see the change. I come back to CodeKit and I see "loading" icon and very soon I see CodeKit taking up 99% of my CPU and I have to close it.

Any ideas?

**Comment by ericbae** [comment]
I've done the following test.

I have SublimeText2, CodeKit, Chrome and ActivityMonitor open.
- I edit a CoffeeScript file in SublimeText2, watch CodeKit compile it - all ok.
- I refresh Chrome to see the change - then CodeKit CPU spikes up to 99%

**Comment by ericbae** [comment]
Only happens in one of the projects I have. Happens on Firefox too.

**Comment by bdkjones** [comment]
Are you running any browser extensions? If so, disable them.

**Comment by ericbae** [comment]
Tried on Safari - which has no browser extension - and the same thing happens.

**Comment by ericbae** [comment]
CPU spikes die down after awhile. Not entirely sure what the issue is here. Looks like it happens when a browser is loading a JS file (mine was around 120KB).

**Comment by bdkjones** [comment]
Have you tried clearing/reseting CodeKit by quitting the app and relaunching it while holding down the shift key? If there's something corrupted in your model file, this will fix that.
