### ISSUE TITLE
Saving javascript causes log window to go to top and make error sound

### ISSUE THREAD

**Issue by kplates** [bdkjones/CodeKit-1-Old#595]
As per title. Unchecking 'Bring CodeKit to the front when there's an error' stops said behavior. This isn't and error so I wouldn't expect this type of alert.

![screen shot 2013-05-09 at 11 23 44 am](https://f.cloud.github.com/assets/4381769/480640/5fddee88-b836-11e2-9012-58da8ef81540.png)

**Comment by bdkjones** [comment]
More fine-grained control of this is coming in 2.0. What's going on here is that you've got syntax issues with this file (they appear above the "successfully minified" message) and those warnings are what's triggering the beep and pop-to-front action.
