### ISSUE TITLE
Delete and reinstall

### ISSUE THREAD

**Issue by sethburtonhall** [bdkjones/CodeKit-1-Old#596]
Codekit is a bit slow and buggy on my Machine.

Late 2009 MBP
Lion OSX

I would like to delete, re-download and re-install.

What is the best way to  re-download and re-install?

I assume I would just download the trial and re-activate?

**Comment by bdkjones** [comment]
Quit the app and then relaunch it while holding down the shift key.

**Comment by sethburtonhall** [comment]
ok, thanks. that did it.
