### ISSUE TITLE
Ability to point Bourbon at custom executable (Bourbon currently out of date)

### ISSUE THREAD

**Issue by benfrain** [bdkjones/CodeKit-1-Old#597]
At time of writing Bourbon is compiling from CodeKit (v1.6.1) with an older version - pre 3.1.2 (e.g. linear-gradients aren't compiling with the correct W3C syntax).

Could we get a custom button in CodeKit as with Sass and Compass to choose a custom executable? That way users can keep their Bourbon up to date without reliance on CodeKit updates.

**Comment by bdkjones** [comment]
There was a reason I couldn't do this, but I don't remember what it is now.

If you need a newer version of Bourbon, just install it at the command line and then use the CLI to install the Bourbon files in your project. They will automatically override the ones that are built-in to CodeKit, giving you the very latest version. Bourbon itself is just a collection of stylesheets; there is no need for the executable once you put the sheets in your project.
