### ISSUE TITLE
Do nothing with Javascript files

### ISSUE THREAD

**Issue by dubiousdavid** [bdkjones/CodeKit-1-Old#598]
I have a Sass/Compass project, but don't want CodeKit to do anything with my Javascript files.  The settings for Javascript seem to indicate that it will always concatenate Javascript files.  Is this true?  If not, maybe the drop down should be more clear, since there isn't an obvious noop.

Thanks,
David

**Comment by bdkjones** [comment]
Hi David, 

You can add *.js to the Skipped Items list in preferences before you add your projects to CodeKit. The app will then completely skip over all your javascript files. Alternately, as long as you leave the "then" setting set to "concatenate imported files" and you don't use any of CodeKit's JS-importing abilities, there will be nothing to do when those files are saved and CodeKit will only reload your browser for you. 

Cheers!

**Comment by dubiousdavid** [comment]
Perfect.  Thanks so much.
