### ISSUE TITLE
CSS Auto-reloading

### ISSUE THREAD

**Issue by thomashermant** [bdkjones/CodeKit-1-Old#60]
My Css is not reloaded automaticaly in my safari window.

If I create a new parapgraph in my html file, the auto reload work : I see the new paragraph.

But for the css, I need to refresh manualy my window to see css modifications.
(The checkbox do not compile directly is not checked for my less file)

**Comment by thomashermant** [comment]
By the way when I save my less file, I see the loading icon on my tab but the old css is persistant

**Comment by bdkjones** [comment]
Enable the Develop menu in Safari and choose "disable cache." This will solve the issue 99% of the time. 

However, I know from personal experience that there are still times when the CodeKit refresh doesn't apply new CSS until you switch to Safari and press command+R.

Behind the scenes, Safari refreshes differently based on how a user invokes the action. I've filed a bug with Apple and hope to have them fix it soon.

**Comment by bdkjones** [comment]
Haven't heard back about this, so I'm assuming that the latest updates have fixed the issue. Don't see it on my end any more.

**Comment by dperrera** [comment]
I'm still having this issue with build 4072 in Safari 5.1.1 even after disabling the caches. The auto-refresh works fine still works great in Chrome.

**Comment by thomashermant** [comment]
For me it's ok on safari 5.1.1 !

**Comment by dperrera** [comment]
It's weird. Safari refreshes but it seems to do that before the .less or .sass files are compiled.
