### ISSUE TITLE
bug: Codekit renamed Javascript files to uppercase

### ISSUE THREAD

**Issue by rictorres** [bdkjones/CodeKit-1-Old#600]
I was working on a project earlier today and everything was running ok. Then I quit Codekit and restarted the OS. When I reopened Codekit that's what happened to the active project:

http://d.pr/i/YcSE

If I go to the project's folder in Pathfinder the file names seem to be ok: http://d.pr/i/gcEW
But if you look at the Inspector you'll see that the path has changed.

After uploading the files to production: http://d.pr/i/8Ve0

Thanks!

**Comment by bdkjones** [comment]
Ah, yes. There was a guy that had this same problem about a year ago. I forget exactly what caused it, but it turned out not to be related to CodeKit. I think the issue is still on GitHub in the "closed" section.

**Comment by rictorres** [comment]
Found it: https://github.com/bdkjones/CodeKit/issues/364
Yeah, I'm also using Sublime Text 2 and SugarSync :( Anyway, gonna start using Cubby from now on.
Thanks
