### ISSUE TITLE
Non-stop refreshing making CPU run time 107%

### ISSUE THREAD

**Issue by vincentchan** [bdkjones/CodeKit-1-Old#601]
![screen shot 2013-05-22 at 11 36 57 am](https://f.cloud.github.com/assets/229261/546370/e077d45a-c290-11e2-97cb-8abc643f94a8.png)

Suddenly have this bug in the past few days. Whenever I start CodeKit, it will keep refreshing my project even I didn't make any changes. Please help. Thanks.

**Comment by bdkjones** [comment]
You've likely got a corrupt model file. To fix this, quit the app and then hold down the shift key while re-launching it. This will clear everything out and give you a fresh start. Cheers!

**Comment by vincentchan** [comment]
Awesome! Fixed it. Thanks.
