### ISSUE TITLE
Abilitiy to configure compile output order for Espresso CSS overrides, @imports

### ISSUE THREAD

**Issue by danawhittle** [bdkjones/CodeKit-1-Old#602]
I am using (and loving) Codekit to do WordPress theming with Bootstrap/Compass/SASS and I use Espresso as my editor and CSS style previewer. All works pretty well except that if I write $variables in my SCSS file, when it compiles to WordPress's default style.css, the compile starts with the @import statements and is then followed by the Espresso @override, which breaks the possiblity of previewing in Espresso's nifty web preview window. 

Any possiblity of somehow allowing this as a config option? It messes with my otherwise fabulous workflow and makes Codekit slightly less wonderful...

Screenshots below showing my setup and the variations mentioned.

What Codekit compiles it to (notice no texture background in hero-unit at right)

![espresso_after_compiling](https://f.cloud.github.com/assets/3432470/549124/d6e5474e-c2f2-11e2-8768-5fca37cedf88.png)

What it should be compiled to (if preview is to work, note textured background at right)

![espresso_correct_preview](https://f.cloud.github.com/assets/3432470/549136/2a9caab2-c2f3-11e2-8b41-d0246c96202b.png)

What my SCSS looks like (note bg not previewing at right)

![espresso_scss_preview_not_working](https://f.cloud.github.com/assets/3432470/549139/3c5fc52c-c2f3-11e2-88ce-a6bd752a1cbf.png)

**Comment by bdkjones** [comment]
This is not an issue with CodeKit. This is the Sass compiler and it's definitely not a bug. According to the W3C spec for CSS, @import statements _must_ be the absolute first thing in a file. They _must_ be at the top and all other content comes after them.

The Sass compiler is doing things correctly, but you could try asking them to support this sort of scenario. Cheers!

**Comment by danawhittle** [comment]
Thanks Bryan; I understand that it's not a bug but it is an "issue" from my point of view since it affects my workflow; didn't realize it was a SASS feature, though, so I apologize for taking up your time... I have emailed Espresso developer to see if they are planning a workaround since your app is definitely the wave of the future (near at least!). : )

**Comment by bdkjones** [comment]
Yea, I definitely understand your frustration. Unfortunately, I don't think the Sass guys are going to break the W3C spec to accomodate Espresso comments. Sorry!

**Comment by danawhittle** [comment]
thanks for the reply bryan; will put the pressure on Espresso to somehow accommodate this! it's so hard to change workflows...
. . . . . . . . . . . . . . . . .

DANA WHITTLE
400 rang St-Joseph
Ste-Béatrix, Québec 
Canada J0K 1Y0
450.883.3342 vox
450.750.5498 mobile
802.552.4298 GoogleVoice
http://vizou.com
dana@vizou.com

http://twitter.com/vizou
http://facebook.com/danawhittle
http://dentdelion.net
