### ISSUE TITLE
v1.6.2 - Jade - Filters are broken

### ISSUE THREAD

**Issue by bobbylee** [bdkjones/CodeKit-1-Old#606]
Hi there,

This issue is similar to the previous post.
Just updated CodeKit to the latest version and my Jade files with filters (:markdown, :stylus or :coffeescript) fails to compile and throw errors: "object is not a function"

You can test with this simple jade file. CodeKit only successfully compiles when all Jade filters are removed.

```
!!! 5
html(lang='en')
  head
    title Test

  body
    :markdown
      # Title
      Description

    :coffeescript
      console.log 'Hello'
```

**Comment by bdkjones** [comment]
I'm aware.

Jade completely changed how it handles filters in its latest update and it's a big mess. For now, to get filter support you'll have to install both Jade AND the associated type of compiler you need at the command line. So you'd need Jade plus Markdown. Then, switch CodeKit to use the external Jade compiler in the Languages tab of the preferences window. 

I hope to get an update out this week that resolves this issue by working around Jade's overall retardedness. Until I get that out, however, this is the only workaround.
