### ISSUE TITLE
V 1.6.2 still has Coffee 1.6.1

### ISSUE THREAD

**Issue by thomasf1** [bdkjones/CodeKit-1-Old#607]
It seems CodeKit 1.6.2 still compiles with Coffeescript 1.6.1 (contrary to the release notes)? 

PS: The 1.6+ Coffeescript range has a [bug](https://github.com/jashkenas/coffee-script/issues/2781) that makes it unusable for me, which is now finally fixed in 1.6.2

Also the About in it states 1.6.1 as coffee Version...
![screen shot 2013-05-27 at 15 42 06](https://f.cloud.github.com/assets/937467/568300/a33ca7ea-c6d3-11e2-84e9-cdff1832adea.png)

**Comment by bdkjones** [comment]
The CoffeeScript guys forgot to update their version number in their latest release and they're being super lazy about fixing that. 

CodeKit is currently running CoffeeScript 1.6.2, even though the CS binary returns the wrong version string. See here:

https://github.com/jashkenas/coffee-script/issues/2989
