### ISSUE TITLE
Bug in image compression

### ISSUE THREAD

**Issue by c-topher** [bdkjones/CodeKit-1-Old#613]
i tried the compression feature. The images were not be visible online. After downloading them ad a try to open then in PS I get the following:
![bildschirmfoto 2013-06-10 um 11 07 26](https://f.cloud.github.com/assets/1702676/630684/338f8990-d1ae-11e2-8f05-bb0232db04a8.png)

**Comment by bdkjones** [comment]
....

I literally have no idea what's going on here. It seems to me that the image file must have been corrupt to begin with. Have you been able to duplicate this behavior every time you attempt to optimize an image? If you download a random image from Google and optimize it, does it exhibit the same issue? Is the image in question a PNG or JPG?

**Comment by paulstraw** [comment]
Brendan's an idiot. Can you fix that?

**Comment by bdkjones** [comment]
Via @fanquake on Twitter: http://www.moonmac.com/Macking90.html

**Comment by c-topher** [comment]
Macking90.html is a Photoshop plugin I read and I don't know or use it. The error accured with several images which I compressed inside CodeKit
