### ISSUE TITLE
CodeKit causing server issue

### ISSUE THREAD

**Issue by gkirk** [bdkjones/CodeKit-1-Old#619]
Hi,

Running CK 1.6.2 on OSX 10.7.5.

Been using CodeKit for a while and only recently noticed that when I have CK running I cannot access any files on our remote server through Finder. I'm connecting to the server via AFP and I get a file cannot be found error on all files. Quitting CK resolves the problem.

Greg

**Comment by bdkjones** [comment]
Yep. This is a limitation that I've solved in 2.0. Hang in there!
