### ISSUE TITLE
Feature request: bulk setting of output paths

### ISSUE THREAD

**Issue by samalone** [bdkjones/CodeKit-1-Old#62]
I'm just getting started with CodeKit. Imported a project where I had been using Less.app, and immediately discovered that all of the output paths were wrong.

I found the default output path setting in the preferences, but that only applies to new projects. It would be nice to have a command (probably a contextual menu command) to reset output paths to the default in the preferences. That way, I could have changed the preferences, selected all the .less files in my project, and reset all of their output paths at once.

**Comment by bdkjones** [comment]
The simpler solution is to remove the project from CodeKit, set the correct default output paths and then add it again, no?

**Comment by samalone** [comment]
Perhaps, but in honesty that didn't occur to me, at least not at first.

I can also see situations where you've made other changes to the project that you want to keep before you noticed the problem, and removing and adding the project would lose those changes.

Clearly this is not a case of making something possible, but of making something easier. You'll have to judge whether the benefit is worth the effort.
