### ISSUE TITLE
Bourbon imports twice?

### ISSUE THREAD

**Issue by bob-van-der-bibs** [bdkjones/CodeKit-1-Old#621]
Hi 
i want to use Bourbon on a project . When i choose 'install/update bourbon files on this project' i can choose  afolder where to put the bourbon files.
when i do so a folder named  'Bourbon' is created there. But also another folder 'Bourbon' within the first folder 'bourbon'.
Doesn't seem right.

**Comment by bdkjones** [comment]
Interesting. Bourbon may have altered something in their latest release; I'll take a look.

In the meantime, it's entirely unnecessary to install the Bourbon files into your project. Just add

```
@import "bourbon";
```

to the top of your main stylesheet and save. CodeKit will do the rest.
