### ISSUE TITLE
Automatic reload/injections no longer working...

### ISSUE THREAD

**Issue by Veraxus** [bdkjones/CodeKit-1-Old#622]
As of today, CodeKit is not longer reloading changed webpages or injecting CSS. It just stopped interacting with my web browsers altogether (both Safari and Chrome seem to be affected).

My first thought was extensions, so I removed ALL of them and restarted. No luck, there.

Next, I disabled everything else I had running in the Status bar... Splashtop, Evernote, etc. Still no luck.

I tried deleting CodeKit and reinstalling. Still no luck.

The only other thing I can think of is that I just removed CS6 and installed the new suite of  Adobe CC apps. I'm currently uninstalling **_everything**_ Adobe CC to see if something there is conflicting (most suspect are the some of the new Edge tools).

Are there any troubleshooting or debugging tricks I could try to narrow down the culprit? Not having CodeKit working it's auto-reload/injection magic is seriously putting a damper on my productivity.

**Comment by Veraxus** [comment]
Two more things I've tried... changing CodeKit preferences (checking and unchecking browsers, change reload target tab, toggling injection options, etc) and trying again. No dice.

I also tried a "Repair Permissions" in Disk Utility (which solves most bizarre, unexplainable OSX issues). Also no dice. Still uninstalling Creative Cloud software.

**Comment by Veraxus** [comment]
It doesn't appear that Adobe CC is at fault. Everything has been uninstalled and Adobe Cleaner run. CodeKit still isn't updating Chrome _or_ Safari. :-(

**Comment by Veraxus** [comment]
Adobe Edge Code is able to inject changes directly into my browsers, so whatever the problem is, it's localized to CodeKit.

I've already tried deleting and reinstalling the CodeKit app, and deleting the CodeKit directory in `~/Library` as well as `~/Library/Preferences` and `~/Library/Caches` ... that didn't work either... what else is there?

Just installed Google Chrome Canary. Same issue.

**Comment by bdkjones** [comment]
Hi Matt,

```
Have you tried rebooting your computer?
```

-Bryan

**Comment by Veraxus** [comment]
Hey Bryan,

Yup. I've tried restarting as well as resetting my MacBook's SMC and PRAM. No dice.

**Comment by bdkjones** [comment]
In that case, please send me the project demoing the issue.

**Comment by Veraxus** [comment]
I just emailed you a simple sample project which includes exported project settings. The project settings should be a simple duplicate of my general CodeKit settings (btw, _all_ of my projects are affected... not just one).

Let me know if there's anything else I can provide.

**Comment by Veraxus** [comment]
Thanks for all the help, Bryan!

You were right, it was definitely an OSX problem. Something must have gone wrong with my OS update last week.

For anyone else running into this or similar problems the future... I solved this (without reformatting) by **reinstalling OSX right on top of itself.** Boot into your recovery partition and select "Reinstall OSX"... from there you will be able to select your current partition and reinstall without losing your data.

The specific error I was getting in the OSX Console was: `Error in Chrome reload: GoogleChromeApplication did not respond to the selector 'windows'. Reload aborted.`
