### ISSUE TITLE
How to add .kit imports in HAML files?

### ISSUE THREAD

**Issue by vincentchan** [bdkjones/CodeKit-1-Old#623]
My compiling setup right now:

_footer.haml > _footer.kit > _footer.html

Then in my regular HAML page (e.g. test.haml), I tried to add the followings:

In the complied "test.html", it simply shows those @include as regular HTML comments.

How can I make this work? Thanks a lot.

**Comment by bdkjones** [comment]
It is not possible to use Kit files in Haml files.
