### ISSUE TITLE
Single files that import no other files are not acted upon unless minified

### ISSUE THREAD

**Issue by fatso83** [bdkjones/CodeKit-1-Old#626]
I have a Web Workers file that needs to be in its own file. We use CodeKit to copy it to an output folder along with the rest, but after the latest update this no longer happens if we choose not to minify it (as is common when in development).

When I now press "Process" all I get is this message:
 "This file imports no others and is not set to minify. Therefore, there is nothing to do (unless you would like to minify the file)." 

Changing the file results in nothing, unless choosing minify.

**Comment by bdkjones** [comment]
CodeKit has always worked this way; nothing changed in the last release that would affect this.

Why not just put the Web Workers file into the output folder to begin with?

**Comment by fatso83** [comment]
Of course you are right. I just never did this in a previous version. I just assumed it was possible to achieve the same workflow for independent files as for files that include others.

The reason putting it in the output folder to begin with does not appeal to me, is that this file should usually be processed by CodeKit. It has always been minified up until now. But now I need it not to be minimized in order to be able to debug a problem. Manually copy-pasting the file from the development folder to the output folder on each change is a chore. That's usually where people opt for a build tool.

When I am finished debugging the problem, I will turn minimize on. Screwing around with the location of the file while I am fixing the issue seems unnecessary.

**Comment by fatso83** [comment]
Could I open some kind of feature request for a "Copy Only" action? The reason for wanting something like this should be apparent from my last comment.

**Comment by bdkjones** [comment]
Yep. I've got 2.0 configured to work that way already.

**Comment by fatso83** [comment]
Oooh, can't wait :+1:
