### ISSUE TITLE
@import JS, not working properly

### ISSUE THREAD

**Issue by Lefthandmedia** [bdkjones/CodeKit-1-Old#627]
Hi,
I've got  a script.js that starts with
// @codekit-prepend "../bootstrap/bootstrap-dropdown.js";
The result is that 'script-ck.js' only contains the copyright statements from dropdown.js but not the code.

**Comment by bdkjones** [comment]
Please send me a demo project that shows the issue.

**Comment by Lefthandmedia** [comment]
this is the js folder in question

**Comment by bdkjones** [comment]
There's nothing attached. You'll need to upload a zip somewhere.

**Comment by Lefthandmedia** [comment]
its here

http://staging.pinkribbon.nl/_js.zip

**Comment by bdkjones** [comment]
Just tested over here and the output file I get when I process "script.js" includes the code from the bootstrap file. Can you show me the output file you're getting when you compile "script.js" over there?
