### ISSUE TITLE
Nice file browser

### ISSUE THREAD

**Issue by madesign** [bdkjones/CodeKit-1-Old#63]
Because thats all what i can do with it. And yes it says refresh complete. And it shows nice images on the right site but no possibility to edit any file, html, js or CSS.
(iMac i7, Lion)

Regards, Michael

**Comment by bdkjones** [comment]
...Not sure what you mean. CodeKit is not an editor. It's designed to work in concert with any editor you'd like, such as Coda, Espresso, Textmate etc.

**Comment by madesign** [comment]
Read the title..
