### ISSUE TITLE
Compilation error in a Bootstrap's LESS file

### ISSUE THREAD

**Issue by nutedigital** [bdkjones/CodeKit-1-Old#634]
In version 1.7 I now get compilation errors in Bootstrap LESS files (at least in mixins.less). I haven't touched the mixins.less file. This is annoying as I use Boostrap for many of my projects :)

ParseError: Unrecognised input in /Users/anders/Sites/BitBucket/blisslegacy/bliss-content/themes/rivendell2014/css/mixins.less on line 527, column 7:
526     .spanX (@index) when (@index > 0) {
527       (~".span@{index}") { .span(@index); }
528       .spanX(@index - 1);

(This action was triggered by a change to mixins.less)

**Comment by bdkjones** [comment]
Are you running the very latest version of Bootstrap?

**Comment by mvantassel** [comment]
I am also seeing the same error with Bootstrap v2.3.0

**Comment by bdkjones** [comment]
Talked to the Bootstrap team. This issue is fixed in the latest version, so you just need to update bootstrap and you'll be set.

**Comment by mvantassel** [comment]
Great stuff. Thanks!
