### ISSUE TITLE
1.7 not seeing framework files

### ISSUE THREAD

**Issue by papalozarou** [bdkjones/CodeKit-1-Old#635]
My set up is that I have a number of framework less files including a library.less containing a  number of mixins.

Now, having updated to 1.7, when I compile project/less/my-less-file.less it says it can't find the library.less file (which is obviously stored elsewhere in my framework folder).

Moving a copy of library.less into  project/less/ fixes the issue – but obviously that's not what I want to be doing for all my projects.

Everything was working perfectly yesterday with 1.6.x

**Comment by nissicreative** [comment]
Same here, exactly. Double-clicking the [FW] file under "Imports" in the right column of the CodeKit window will properly reveal the framework file in the Finder, so I know it's there.

**Comment by bdkjones** [comment]
I'm aware of the issue and looking into it. Less 1.4 has been a bit of a nightmare so far.

**Comment by bdkjones** [comment]
Fixed in 1.7.1
