### ISSUE TITLE
Preferences > Compass > Advanced Compiler Settings > *clicking* Choose causes crash

### ISSUE THREAD

**Issue by pmeissner** [bdkjones/CodeKit-1-Old#637]
Preferences > Compass > Advanced Compiler Settings > _clicking_ Choose causes a application crash every time.

![screen shot 2013-07-09 at 1 16 44 pm](https://f.cloud.github.com/assets/392386/769694/683a9d96-e8bb-11e2-9555-6db74eb32811.png)

**Comment by pmeissner** [comment]
Of course after trying ten times and failing I write this issue and then it works.

**Comment by bdkjones** [comment]
You're seeing a bug in OS X. You've got an SMB or Samba drive connected to your system and when you click choose to bring up the file choosing dialog sheet (a system component) OS X tries to scan the remote disk and fails and crashes the process, which brings down the associated app.

It's hugely annoying and I've yelled at Apple repeatedly about it. There's nothing I can do until they decide to fix it!
