### ISSUE TITLE
Going crazy Less+Scss at same time

### ISSUE THREAD

**Issue by shanimal** [bdkjones/CodeKit-1-Old#638]
I was delighted to find that when I first installed CodeKit I could import Less files into my Scss files?!!! I just installed the update and this doesn't seem to be the case anymore.

Maybe I was imagining things, but if I was... my imagination is brilliant!

**Comment by bdkjones** [comment]
... Nope. That should definitely _not_ be possible and would be a large bug. Please send me an example that demos the issue.

**Comment by shanimal** [comment]
Large bug, should definitely not be possible? That's not right. Come on. 

Maybe I'm asking for the impossible? Fair enough.

The use case is pretty straight forward. I want to add twitter bootstrap (Less) in my project (Sass)

It would look something like this...

```
    $purple: rgb(99,50,126);
$linkColor:rgba($purple,80);
$linkColorHover:$purple;
@import "variables.less";

// import bootstrap
// @import "bootstrap/less/variables.less";
@import "bootstrap/less/accordion.less";
@import "bootstrap/less/alerts.less";
...

hr {
    color:$purple;
}
```

I'm convinced I'm not alone when people have taken the time to build github projects to port Less->Sass / Sass->Less. I can't seem to find one that isn't deprecated/defunct.

**Comment by bdkjones** [comment]
Sorry, pal. I don't have control over the compilers and they would flip the hell out if you tried to pass them this.

**Comment by shanimal** [comment]
No troubles scooter. That's what I figured.
