### ISSUE TITLE
LESS compiling breaks on Bootstrap

### ISSUE THREAD

**Issue by ryanmac** [bdkjones/CodeKit-1-Old#639]
LESS no longer compiles Twitter Bootstrap LESS files.  See below.

ParseError: Unrecognised input in /path/to/site/html/assets/less/mixins.less on line 552, column 7:
551     .spanX (@index) when (@index > 0) {
552       (~".span@{index}") { .span(@index); }
553       .spanX(@index - 1);

(This action was triggered by a change to mixins.less)

**Comment by ryanmac** [comment]
It looks like this is due to using a new LESS compiler (v1.4.0) instead of the supported v1.3.3.  Can you recommend a strategy to use LESS 1.3.3 to compile instead?

**Comment by bdkjones** [comment]
Please update to the latest version of twitter bootstrap and close the issue. Thanks!

**Comment by ryanmac** [comment]
I suppose.  I can do that easily with some repositories but not for others.  Can you recommend a way to choose v1.3.3 as the default compiler?  Perhaps using "Advanced Compiler Settings"?

**Comment by ryanmac** [comment]
Updated to Bootstrap and problem was resolved.  Closing this issue.

**Comment by bdkjones** [comment]
It's not possible to use an older version of a compiler than the one that ships with a given version of CodeKit. 

Unfortunately, less is simply marching on.

**Comment by ryanmac** [comment]
Thanks for the quick support.  Still a huge fan of your app.
