### ISSUE TITLE
Less not compiling after updating

### ISSUE THREAD

**Issue by hvgeertruy** [bdkjones/CodeKit-1-Old#642]
I use less pattern matching. This compiled perfectly up untill last update. Now I get following error:

`SyntaxError: Cannot mix ; and , as delimiter types in [somefile] on line [n], column [n]`

According to less.css documentation, I should still be able to use that syntax.

```
Now let’s say we want .mixin to behave differently, based on the value of @switch, we could define .mixin as such:

.mixin (dark; @color) {
  color: darken(@color, 10%);
}
.mixin (light; @color) {
  color: lighten(@color, 10%);
}
.mixin (@_; @color) {
  display: block;
}
```

Any ideas how to fix this?

**Comment by hvgeertruy** [comment]
It seems to be a problem originating from the less compiler itself.
I posted a thread on less on this as well, see (https://github.com/less/less.js/issues/1417#issuecomment-20877324)
_update:_ they can not reproduce the problem so it should not be version related..?

I switched CodeKit's less compiler with my own, the problem went away.
Still not ideal, though. 

You can switch the lessc compiler in Codekit's user preferences > less tab > advanced compiler settings (bottom right)

**Comment by bdkjones** [comment]
Less 1.4 introduced new syntax. It's likely that you need to tweak your code to be compliant with 1.4+.
