### ISSUE TITLE
Configure/Add a "Copyright Notice" in minified css files

### ISSUE THREAD

**Issue by shanimal** [bdkjones/CodeKit-1-Old#643]
I'd like to add a copyright notice, and optionally append any Licenses from other files I incorporate on a per file basis.

Is this possible I couldn't find it anywhere

**Comment by bdkjones** [comment]
You use a special comment delimiter in your Sass or less file to tell the compiler to preserve a comment in the compiled CSS. See the docs for your language for more details.

**Comment by shanimal** [comment]
thanks! i found the reference in the sass documentation as prescribed.

"When the first letter of a comment is !, the comment will be interpolated and always rendered into css output even in compressed output modes. This is useful for **_adding Copyright notices**_ to your generated CSS." 
http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#comments

/*! Copyright © 2001 Good Company, All Rights Reserved */
