### ISSUE TITLE
Lastest release of codekit doesnt recognize inputs

### ISSUE THREAD

**Issue by Clegacy** [bdkjones/CodeKit-1-Old#644]
Hi, 
I had a project using less that compiled fine in a previous build of codekit. I recently did the latest update and now codekit no longer understands or compiles the following. 

.spanX (@index) when (@index > 0) {
       (~".span@{index}") { .span(@index); }
      .spanX(@index - 1);
}

**Comment by bdkjones** [comment]
You need to update your code to be compatible with Less 1.4+ syntax. See lesscss.org for details. 

The newest version of Less introduced some backwards-incompatible syntax changes.

**Comment by Clegacy** [comment]
Thanks! Figured it out

On Jul 16, 2013, at 6:34 PM, bdkjones notifications@github.com wrote:

You need to update your code to be compatible with Less 1.4+ syntax. See
lesscss.org for details.

The newest version of Less introduced some backwards-incompatible syntax
changes.

—
Reply to this email directly or view it on
GitHubhttps://github.com/bdkjones/CodeKit/issues/644#issuecomment-21079312
.
