### ISSUE TITLE
Auto-Reload causing WordPress reauth on every save

### ISSUE THREAD

**Issue by NicoleGeissinger** [bdkjones/CodeKit-1-Old#648]
I've never encountered this until today (updated to 1.7.1 maybe a day or two ago), but I'm buildout some admin pages in WordPress in Less/Bootstrap, and when I have the options to auto-reload my browsers, WordPress tosses me a to the login screen with the query string "reauth" in it meaning I need to verify my credentials that I can be in the admin area.

If I turn off the auto-reload, I no longer get it. Not sure what's happening and what broke but that was driving me nuts. I don't mind manually refreshing but having auto-reload going is awesome :)

I'm running the latest version of CodeKit on Mac OS X 10.7.5 15" late 2011, and WordPress 3.6-RC1 on MAMP 2.1.3 (since I am running a version of WP that is technically under-dev, this might be an issue on their end too but running on trunk I have the latest updates...).

**Comment by bdkjones** [comment]
Hi Cole,

```
What I recommend is opening the Wordpress Admin page in one browser (say, Safari) and then using Chrome to preview your website (outside of the admin area). Then, set CodeKit to auto-reload only Chrome and not Safari. This will prevent the issue. Thanks!
```

-Bryan

**Comment by markjaquith** [comment]
Try logging out, then logging back in and checking the "Remember me" checkbox.
