### ISSUE TITLE
[UI Tweak] Add padding around uglify/lint parameter table views

### ISSUE THREAD

**Issue by cocoahero** [bdkjones/CodeKit-1-Old#65]
I could just be a sticker for UI design, but I think having the table views bump up right with the edge of the window looks a bit cramped.

**Comment by bdkjones** [comment]
Yea... that whole section is a temporary thing. 

I want to create a styled tableView that looks like the explanation page at JSHint's website. With full text explanations so users don't have to go to the website anymore. It's on my list.

**Comment by bdkjones** [comment]
Build 5076: These tables are now deliciously awesome. Completely revamped them so that people who are not Javascript gods can actually understand what the hell all the options do.
