### ISSUE TITLE
Dynamic LESS variables failing since version 1.7.1

### ISSUE THREAD

**Issue by tomyates** [bdkjones/CodeKit-1-Old#650]
On updating to version 1.7.1 I have the following problem:

```
// Layout
@maxContainerWidth:     1240px;
@numberColumns:         10; 
@colWidth:              @maxContainerWidth / @numberColumns;
@width1:                @colWidth*10;
```

If I use the varible @width1 in a media query such as:

```
@media (max-width: @width1) {
```

The result is

```
@media (max-width: 1240px / 10*10) {
```

Rather than the expected:

```
@media (max-width: 1240px) {
```

**Comment by bdkjones** [comment]
Hi Tom,

Please see lesscss.org --- there are some syntax changes for math operations in Less 1.4+ and you'll need to tweak your code to be compatible. Cheers!

-Bryan

**Comment by tomyates** [comment]
Thanks!
