### ISSUE TITLE
fieldset parameters

### ISSUE THREAD

**Issue by john-klungers** [bdkjones/CodeKit-1-Old#655]
fieldset(data-role="fieldcontain", data-type="horizontal", data-role="controlgroup"  )

should precompile to:
<fieldset data-role="fieldcontain"  data-type="horizontal" data-role="controlgroup">
is does
<fieldset data-type="horizontal" data-role="controlgroup">

**Comment by bdkjones** [comment]
Hmm. First, there appear to be things missing from the report above. Secondly, you'd need to open this issue with the appropriate compiler for the language you're using. CodeKit just runs the compilers; it does not compile code itself.
