### ISSUE TITLE
CSS inject doesn't work in Chrome on OSX

### ISSUE THREAD

**Issue by lucacioria** [bdkjones/CodeKit-1-Old#658]
in the chrome console, the error I get is:
![screen shot 2013-08-14 at 12 14 57 pm](https://f.cloud.github.com/assets/554092/961101/b2594ca8-04ca-11e3-86b2-587168dd5daa.png)

**Comment by bdkjones** [comment]
What browser plugins are you running? I assure you, CSS injections work just fine in Chrome for many thousands of people.

**Comment by lucacioria** [comment]
solved the issue, tags were mismatched and although the browser renderer didn't complain, codekit couldn't access the DOM in the right way.
sorry
