### ISSUE TITLE
Error compiling bootstrap v3

### ISSUE THREAD

**Issue by mattclegg** [bdkjones/CodeKit-1-Old#659]
ParseError: Unrecognised input in /bootstrap/less/mixins.less on line 561, column 7:
560     .spanX (@index) when (@index > 0) {
561       (~".span@{index}") { .span(@index); }
562       .spanX(@index - 1);

**Comment by bdkjones** [comment]
This is not a CodeKit issue. They mistyped line 561. The error is in Bootstrap.

**Comment by mattclegg** [comment]
Yes, your right.
https://github.com/twbs/bootstrap/commit/042bb9b51510573a9a1db6bc66cb16311d0d580b#less/mixins.less
