### ISSUE TITLE
Prepend/Append JS libraries to the output of a CoffeeScript file

### ISSUE THREAD

**Issue by mbrio** [bdkjones/CodeKit-1-Old#66]
I would love to see the ability to add an @import-prepend or @import-append directive to my CoffeeScript files which will allow me to combine JavaScript libraries to the final JS output by coffee. This could work exactly how it does in regular JS files within CodeKit. An example would be to combine jquery.js to the beginning of the output for script.coffee so that the final script.js file has  jquery.js first then the final output of script.coffee.

**Comment by nocksock** [comment]
I second this. 

I run into "not defined" warnings all the time because i currently cannot import JavaScript into my CoffeeScript. This is really crucial if working with jQuery, Crafty… or any other library.

**Comment by xenocid** [comment]
I'd really like to see this feature implemented. I use some JS libraries from within my CS scripts and now I either have to turn off JSLint/JSHint or get annoying warnings - both options are equally bad.

**Comment by bdkjones** [comment]
So I've given this a lot of thought and I'm just not sure that introducing this level of complexity is a good idea.

The more robust, error-proof way to handle this situation is:

1) Compile a CoffeeScript file (someFile.coffee) into Javascript (someFile.js)

2) Create another JS file (master.js) and, in it, do this:

```
@codekit-prepend "jQuery.js";
@codekit-append "someFile.js";
```

3) Now, whenever you save the coffeescript file, CodeKit will see a change to the someFile.js file, calculate that master.js needs to be recompiled to capture those changes, and it will do so.

This allows you to automatically put Javascript and CoffeeScript files together without introducing all the complexities of actually being allowed to drag a JS file into a CoffeeScript file within CodeKit. 

To put this another way: We wouldn't allow a user to import a SASS file into a LESS file that he then imports into a STYLUS file. It would be a nightmare trying to handle that!
