### ISSUE TITLE
Codekit freezing up, never finishing compile of LESS file

### ISSUE THREAD

**Issue by parisvega** [bdkjones/CodeKit-1-Old#671]
Got the spinning wheel of death, and an everlasting progress bar in CodeKit when trying to compile a LESS file. 

I checked my activity Monitor and there were 2 processes called "node" taking up most of up computers resources. After killing those processes my computer performed better.

![screen shot 2013-09-17 at 1 06 26 pm](https://f.cloud.github.com/assets/247841/1159522/ad150698-1fc7-11e3-9a05-95d45c9f0df7.png)

**Comment by bdkjones** [comment]
There are several possibilities:

1) A corrupt data file. To fix this, quit CodeKit and then relaunch it while holding down the shift key. This will clear out all existing projects and give you a fresh start.

2) An infinite import loop in your Less file. That is, File A imports File B, which imports File A. Make sure that's not going on here.

3) Browser plugins / conflicting apps: are you watching a folder in CodeKit that's being managed by a service like SugarSync or Dropbox?

**Comment by parisvega** [comment]
Infinite import loop! (face palm) Fixed.

Would be awesome if there was a notification of some kind when/if that happens.

Thanks for the advice!
