### ISSUE TITLE
Chrome not refreshing

### ISSUE THREAD

**Issue by cinnamonrowles** [bdkjones/CodeKit-1-Old#672]
Hi, 

When I save my css files, and sometimes the main HTML file, chrome does not always show the changes.  I'm using the most up to date version of chrome and codekit.  I can't find a pattern yet for when this happens.  I'm not using LESS or SASS when this happens.  

Thanks!

**Comment by bdkjones** [comment]
I'm afraid I'll need a lot more information. What browser plugins are you running? Can you send me the project demoing the issue?

**Comment by cinnamonrowles** [comment]
Hi, thanks for getting back to me so quickly!

I am running chrome with no plugins, but I almost always have the developer tools window open.  I put the entire project on my github.  Please let me know if you have any issues viewing it - I just started using github today.

Thanks,

Rebecca

**Comment by cinnamonrowles** [comment]
One more thought - I had to add this script to the end of my files because Chrome was acting strangely on refresh (refreshing without saving through codekit):



```
    <script type="text/javascript">document.write('<link rel="stylesheet" type="text/css" media="screen" href="/Style%20Library/package/css/mainfile.css?v=' + Math.floor((Math.random()*1000)+1) + '"></' + 'link>');</script>
```

When refreshing without codekit, chrome would continually apply less and less of my css to the page.  I googled the issue, found that other people have had the same problem, and that they have had success using the script above.

Hope that helps!

**Comment by cinnamonrowles** [comment]
And one MORE thought - I've noticed this happens more often when deleting styles rather than adding them.

**Comment by bdkjones** [comment]
Hi Rebecca,

```
First, you didn't send me a link to the GitHub page.

Secondly, wow --- that is one ugly hack there. That's almost certainly the issue, because you've essentially got a script that's reloading CSS files as CodeKit tries to reload CSS files. I can virtually guarantee that's the cause of the problem. However, I've never heard of Chrome "applying less and less" of stylesheets. Can you send me a link to that discussion?
```

-Bryan

**Comment by asumaran** [comment]
This also happens to me. Codekit successfully refreshes HAML files but when I update SASS files, compiles and tries to refresh Chrome but without success

In the console says this error:
Uncaught NotFoundError: An attempt was made to reference a Node in a context where it does not exist.
r.refreshStylesheets
(anonymous function)
(anonymous function)

I'm running Codekit 1.8.1 (8326) with the latest Chrome (Versión 29.0.1547.76) with all plugins disabled.

Happens the same with the latest Chrome Canary

Console error:

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'ContainerNode': The node before which the new node is to be inserted is not a child of this node. VM28:1
r.refreshStylesheets VM28:1
(anonymous function) VM28:1
(anonymous function)

Related file: https://gist.github.com/asumaran/6759450

UPDATE:

Forget it. My html was invalid. Now it's fixed. My bad. 
I'm leaving the comment in case help someone

**Comment by bdkjones** [comment]
You're likely running a Javascript library on this page that's incompatible with CSS injections. Prefrixfree.js is a big offender, for example.

**Comment by asumaran** [comment]
I've updated my previous comment. My html was invalid. Something like:

```
<html></html>
<head>
 ...
</head>
<body>
...
</body>
```

**Comment by cinnamonrowles** [comment]
Hi again,

I removed the script above but I am still having the issue.  Usually what happens is I will remove some code in the CSS file (usually the file called 'og-styles.css') and when I hit save the changes are not made in the Chrome browser.  

Here is the link to my project:
https://github.com/cinnamonrowles/surflombok

Thanks
