### ISSUE TITLE
Various bourbon keyframes freezing codekit

### ISSUE THREAD

**Issue by thomasplevy** [bdkjones/CodeKit-1-Old#675]
I've been noticing some strange behavior using bourbon's keyframes mixin.

Using various mixins inside of the keyframe mixins is causing codekit to freeze when compiling the scss files -- I can't determine a definite pattern and I've been trying to hold off submitting this until I have better data, but I'm really at a loss to exactly what's causing the issue.

Example sccs that works:

@include keyframes(ANIMATE-GROW) {
    0% {
        opacity: 0.1;
        @include transform(scale(.5));
    }
    100% {
        opacity: 1;
        @include transform(scale(1));
    }
}

Example scss that causes codekit to hang:

@include keyframes(INPUT-ERROR) {
    0% {
        @include transform(translateX(0));
    }
    25% {
        @include transform(translateX(-.5em));
    }
    75% {
        @include transform(translateX(.5em));
    }
    100% {
        @include transform(translateX(0));
    }
}

I've tried variations methods to narrow down where the issue occurs. Interestingly enough, if I have only one stop with a transform in it eg:

@include keyframes(INPUT-ERROR) {
    0% {
        @include transform(translateX(-.5em));
    }
}

If will compile fine.

I've also tried using "from" & "to" instead of percentages, but the same things seem to occur.

& of course Thanks for the awesome product!

**Comment by bdkjones** [comment]
This doesn't seem like a CodeKit issue. It sounds like the sass compiler is hanging on the supplied code and CodeKit just sits and spins while waiting for the sass compiler to finish running.

To verify, please try compiling the file from the command line directly using the latest stable (NON-beta) release of Sass.

Thanks!

**Comment by thomasplevy** [comment]
Thanks for the quick reply and sorry for taking so long to respond.

I've compiled a few times using v 3.2.5 (Media Mark) on the command line. It seems like you're right.

I am getting a _ton_ of warnings from SASS on the command line. They all seem to be associated with Bourbon's @keyframe mixin. 

EG:

WARNING: Unrecognized prefix: ms
         on line 29 of bourbon/addons/_prefixer.scss, in `prefixer'
         from line 3 of bourbon/css3/_transform.scss, in`transform'
         from line 25 of _keyframes.scss, in `@content'
         from line 20 of bourbon/css3/_keyframes.scss, in`keyframes'
         from line 23 of _keyframes.scss
         from line 22 of style.scss

WARNING: Unrecognized prefix: o
         on line 29 of bourbon/addons/_prefixer.scss, in `prefixer'
         from line 3 of bourbon/css3/_transform.scss, in`transform'
         from line 25 of _keyframes.scss, in `@content'
         from line 20 of bourbon/css3/_keyframes.scss, in`keyframes'
         from line 23 of _keyframes.scss
         from line 22 of style.scss

WARNING: Unrecognized prefix: spec
         on line 29 of bourbon/addons/_prefixer.scss, in `prefixer'
         from line 3 of bourbon/css3/_transform.scss, in`transform'
         from line 25 of _keyframes.scss, in `@content'
         from line 20 of bourbon/css3/_keyframes.scss, in`keyframes'
         from line 23 of _keyframes.scss
         from line 22 of style.scss

WARNING: Unrecognized prefix: webkit
         on line 29 of bourbon/addons/_prefixer.scss, in `prefixer'
         from line 3 of bourbon/css3/_transform.scss, in`transform'
         from line 28 of _keyframes.scss, in `@content'
         from line 20 of bourbon/css3/_keyframes.scss, in`keyframes'
         from line 23 of _keyframes.scss
         from line 22 of style.scss

etc....

I tried messing with Bourbon to "fix" the mixin and prevent the error but I can't.

The weird thing is that I do get a fully compiled .css file despite the warnings on the command line. But codeKIT hangs.

Additionally, it's strange that I can compile without a problem when there is only 1 transform mixin inside the keyframe mixin, but as soon as I add a 2nd transform into the mixin the issues pops up.

Ultimately I can acceptably work around this issue. I feel like it's probably a combination of issues, but if you have any additional feedbacks or suggestions I'd love to hear them -- or if you need me to run any additional tests I'm happy to.

Thank you!

**Comment by bdkjones** [comment]
Hi Thomas,

```
I'd open an issue on the Bourbon GitHub page so that team can take a look. Cheers!
```

-Bryan
