### ISSUE TITLE
Feature Request: PHP Code Sniffer

### ISSUE THREAD

**Issue by Veraxus** [bdkjones/CodeKit-1-Old#677]
After having spent (i.e. wasted) the afternoon trying to set up PHP CodeSniffer on my MacBook (gah, hat horrible, useless documentation!) I found myself wishing/dreaming that CodeKit had the option baked right in.

Mind you, I am willing to wait for the next version of CodeKit, and I will happily throw money at you for it. I mean, I'd throw money at you for the next version of CodeKit anyway... but please consider this feature, nonetheless.

Sidenote: The ultimate goal is to simply get live feedback of PSR compliance, a-la JSHint/JSLint... without the esoteric and labyrinthine setup process that currently must be followed. Cheers :-)

**Comment by bdkjones** [comment]
What is PHP CodeSniffer?

**Comment by Veraxus** [comment]
It's basically JSLint... but for PHP.

It's a pear package allows you to select a coding standard (PSR-0, PSR-1, PSR-2, Zend, WordPress, etc) which it uses to validate your code, presenting you with a list of errors any time you violate one of those standards. It's spectacularly useful, and woefully underused by the PHP development community at large... primarily because getting it set up is nightmare.

This is the official site: http://pear.php.net/package/PHP_CodeSniffer/

**Comment by bdkjones** [comment]
Looks interesting, but it's written in PHP. 

It would need to be ported to C or Javascript in order for me to integrate it into CodeKit.

**Comment by Veraxus** [comment]
Darn. Thanks for looking into it, Bryan.
