### ISSUE TITLE
Support for snow leopard

### ISSUE THREAD

**Issue by bleeppurple** [bdkjones/CodeKit-1-Old#68]
support for SL 10.6.8

**Comment by bdkjones** [comment]
Not happening. CodeKit relies on new APIs introduced in 10.7 — specifically in Grand Central Dispatch and Core Data.

Lion is $29. End of story.

**Comment by bleeppurple** [comment]
Its not the fact that lion is $29
We're not upgrading right now because we're in the middle of some projects
I posted the issue because i'm sure some other developers will have the same question.
First line of your answer would of been sufficient to get your point across
