### ISSUE TITLE
Feature request: Better image optimization

### ISSUE THREAD

**Issue by jkbktl** [bdkjones/CodeKit-1-Old#680]
I love using CodeKit for compiling LESS and CoffeeScript files, but it's useless for image optimization. It's just not working as well as expected.

I did a test with random images. I compared some services for image optimization.

Here are the results: 
![test-results](https://f.cloud.github.com/assets/520927/1322016/fc08ed6a-3407-11e3-8271-9748454bd72a.png)

Optimized images from Kraken.io and tinyPNG are unrecognizable from originals, so there are some options to improve this feature. (Here are all images in ZIP to see image quality: http://goo.gl/z4xEEg)

So I would love to see some better algorithm for image optimization. 

Please don't get me wrong, it's not important, it's just nice-to-have.

**Comment by bdkjones** [comment]
It's really unfair to compare lossy and lossless optimizations. Of course lossy is going to win!

That said, I do intend to provide some more options for the image optimizers in the future. It's just a little lower on the priority list than shipping 2.0.

**Comment by ialphan** [comment]
Maybe you can look into adding ImageOptim (http://imageoptim.com/)?
