### ISSUE TITLE
Having problem hiding entire folders from codekit

### ISSUE THREAD

**Issue by jrdn91** [bdkjones/CodeKit-1-Old#681]
I'm tried using both /assets and just straight assets to hide an assets folder from codekit but nothing seems to work. Hoping someone can help me as there are often quite a bit of files in there that will never make it into the final project and are only places to put downloaded files and things from clients.

**Comment by bdkjones** [comment]
I assume you’re talking about the Skipped Items list in the preferences? As the note next to it explains, changes don’t affect projects that are already in CodeKit. Simply remove and re-add the project after editing the list to have it applied.

-Bryan

**Comment by jrdn91** [comment]
Thank you...
