### ISSUE TITLE
ruby: illegal switch in RUBYOPT: -E (RuntimeError)

### ISSUE THREAD

**Issue by bradt** [bdkjones/CodeKit-1-Old#685]
Just upgraded to 1.9.1 and now I'm getting the following error:

![screen shot 2013-10-23 at 10 52 02 pm](https://f.cloud.github.com/assets/190095/1396038/ef45cf36-3c4e-11e3-9b9a-5219dde91704.png)

I'm using CodeKit's internal Sass and Compass compilers.

> $ ruby -v
> ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

**Comment by bradt** [comment]
Just Time Machined back to 1.7.1 (8317) and all good again.

**Comment by bdkjones** [comment]
Hi Brad,

```
Run the update check again. 1.9.2 resolves the issue.
```

-Bryan

**Comment by nathanielks** [comment]
Hey man,

I just got this and I'm having the same issue. 1.9.2.

**Comment by primsi** [comment]
> I just got this and I'm having the same issue. 1.9.2.

Same here:

> Compass was unable to compile one or more files in the project: 
> 
> />System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: illegal switch in RUBYOPT: -E (RuntimeError)

**Comment by bdkjones** [comment]
What version of OS X are you running?

**Comment by nathanielks** [comment]
I'm 10.9 but I was able to resolve this by updating the systems version of compass ( using external binary )

**Comment by primsi** [comment]
> What version of OS X are you running?

System version: 10.9. Compass version: 0.12.2

> I'm 10.9 but I was able to resolve this by updating the systems version of compass ( using external binary )

Thx for the hint. I am using the system Compass executable (because of Singularity GS). When I use the 
internal Compass compiler it works.
