### ISSUE TITLE
Avoid loading all files on open

### ISSUE THREAD

**Issue by ddellostritto** [bdkjones/CodeKit-1-Old#689]
Just updated and so far have spent 20+ minutes with codekit using whatever js checker it uses to go through all of the plugins I have setup my framework folders. The app is locking up my machine and I can't set the preferences back to not use the js checker until it finishes - however long that's going to take. 

If updating is going to reset the preferences, perhaps you could disable loading all of the files again in order to avoid this problem.

**Comment by bdkjones** [comment]
Hi Drew,

You've got a corrupt data file. Quit the app and relaunch it while holding down the shift key to clear everything out and start fresh.
