### ISSUE TITLE
"Check Output With" is reset from time to time.

### ISSUE THREAD

**Issue by nocksock** [bdkjones/CodeKit-1-Old#69]
I usually set "Check Output With" to "Nothing". But from time to time (couldn't yet figure out when exactly - or if there's some concrete "when" at all) it's reset to JSHint and bugging me with warnings. Which is nasty, because CK takes focus and I'm im getting pulled out of the flow.

**Comment by bdkjones** [comment]
Haven't been able to reproduce this. Can you give me some clearer steps to get the behavior?

**Comment by nocksock** [comment]
In fact I can't really. I'm not doing anything special, I just let CodeKit run in the Background… it takes some time to happen though. :/ But I'll keep an eye on it. I'm going to use it heavily this week.

**Comment by bdkjones** [comment]
Is this issue still manifesting?
