### ISSUE TITLE
New project doesn't show any file

### ISSUE THREAD

**Issue by minimalart** [bdkjones/CodeKit-1-Old#692]
Hi,
I've using Codekit for a while with several projects, and today, first time after updating to Maverick and Codekit 1.9.2 when I create a new project the files (jade and scss) doesn`t appear in main window.
I refreshed the project once and again, removed project, removed codekit-config.json, re-added project and files still missing. Then I downloaded and installed a fresh copy of Codekit with no luck.
Also, I tried to add files to another (old) project, and they're working fine there.
Is it a bug or I'm doing something wrong?

This is my project folder tree:
- project
-            /source
-                        /jade
-                                 /index.jade <--- this files is missing in Codekit
-                       /sass
-                                 /main.scss <---- missing
-           /public

And this is my codekit-config-json
{
  "CodeKitInfo" : "This is a CodeKit project configuration file. It is designed to sync project settings across multiple machines. Modifying the contents of this file can be a poor life decision if you don't know what you're doing. This file is not useful unless accompanied by the project that created it in CodeKit. For more information, see: http:\/\/incident57.com\/codekit",
  "creatorBuild" : "8376",
  "files" : {

  },
  "manualImportLinks" : [

  ],
  "projectSettings" : {
    "hamlNoEscapeInAttributes" : 0,
    "kitAutoOutputPathStyle" : 0,
    "lessOutputStyle" : 0,
    "hamlAutoOutputPathReplace2" : "",
    "draggedImportConcatenationStyle" : 1,
    "jadeAutoOutputPathStyle" : 1,
    "hamlEscapeHTMLCharacters" : 0,
    "javascriptAutoOutputPathStyle" : 0,
    "hamlOutputFormat" : 2,
    "stylusAutoOutputPathReplace1" : "stylus",
    "lessStrictImports" : 0,
    "sassAutoOutputPathStyle" : 1,
    "stylusAutoOutputPathReplace2" : "css",
    "lessAutoOutputPathStyle" : 2,
    "lessIECompatibility" : 1,
    "genericWebpageFileExtensionsString" : "html, htm, shtml, shtm, xhtml, php, jsp, asp, aspx, erb, ctp",
    "lessStrictUnits" : 0,
    "lessStrictMath" : 0,
    "coffeeMinifyOutput" : 1,
    "javascriptOutputSuffix" : "-ck",
    "jadeOutputStyle" : 0,
    "coffeeAutoOutputPathStyle" : 0,
    "autoSyncProjectSettingsFile" : 1,
    "lessAutoOutputPathReplace1" : "less",
    "jadeAutoOutputPathReplace1" : "",
    "lessAutoOutputPathRelativePath" : "..\/css",
    "hamlAutoOutputPathRelativePath" : "..\/",
    "jsCheckerReservedNamesString" : "",
    "javascriptOutputStyle" : 1,
    "stylusDebugStyle" : 0,
    "hamlUseCDATA" : 0,
    "hamlAutoOutputPathStyle" : 2,
    "sassDebugStyle" : 0,
    "hamlOutputStyle" : 0,
    "stylusAutoOutputPathRelativePath" : "..\/css",
    "jsCheckerIndent" : 4,
    "kitAutoOutputPathRelativePath" : "",
    "lessAutoOutputPathReplace2" : "css",
    "jadeAutoOutputPathReplace2" : "",
    "shouldRunBless" : 0,
    "stylusAutoOutputPathStyle" : 2,
    "coffeeCheckOutputStyle" : 0,
    "slimOutputStyle" : 1,
    "javascriptSyntaxCheckerStyle" : 1,
    "sassAutoOutputPathReplace1" : "sass",
    "slimAutoOutputPathReplace1" : "",
    "sassOutputStyle" : 0,
    "coffeeAutoOutputPathRelativePath" : "",
    "slimCompileOnly" : 0,
    "slimLogicless" : 0,
    "uglifyIndent" : 4,
    "jadeAutoOutputPathRelativePath" : "public",
    "hamlUseUnixNewlines" : 0,
    "hamlAutoOutputPathReplace1" : "",
    "javascriptAutoOutputPathReplace1" : "",
    "stylusOutputStyle" : 0,
    "javascriptAutoOutputPathReplace2" : "",
    "sassAutoOutputPathRelativePath" : "public\/css",
    "coffeeAutoOutputPathReplace1" : "",
    "hamlUseDoubleQuotes" : 0,
    "coffeeAutoOutputPathReplace2" : "",
    "kitAutoOutputPathReplace1" : "",
    "uglifyReservedNamesString" : "",
    "coffeeOutputStyle" : 0,
    "slimAutoOutputPathRelativePath" : "",
    "jsHintFlags" : {
      "latedef" : 1,
      "newcap" : 1,
      "curly" : 1,
      "trailing" : 1,
      "nonew" : 1,
      "es3" : 0,
      "freeze" : 1,
      "yui" : 0,
      "mootools" : 0,
      "proto" : 0,
      "boss" : 0,
      "funcscope" : 0,
      "jquery" : 1,
      "esnext" : 0,
      "camelcase" : 0,
      "dojo" : 0,
      "strict" : 0,
      "devel" : 0,
      "wsh" : 0,
      "nonstandard" : 0,
      "asi" : 0,
      "moz" : 0,
      "rhino" : 0,
      "smarttabs" : 0,
      "lastsemic" : 0,
      "noempty" : 0,
      "eqnull" : 0,
      "eqeqeq" : 1,
      "couch" : 0,
      "evil" : 0,
      "expr" : 0,
      "immed" : 0,
      "globalstrict" : 0,
      "undef" : 1,
      "iterator" : 0,
      "prototypejs" : 0,
      "noarg" : 1,
      "supernew" : 0,
      "node" : 0,
      "unused" : 1,
      "debug" : 0,
      "bitwise" : 1,
      "notypeof" : 1,
      "white" : 0,
      "browser" : 1,
      "worker" : 0,
      "laxcomma" : 0,
      "multistr" : 0,
      "shadow" : 0,
      "sub" : 0,
      "plusplus" : 0,
      "scripturl" : 0,
      "forin" : 0,
      "loopfunc" : 0,
      "laxbreak" : 0
    },
    "jsLintFlags" : {
      "white" : 0,
      "unparam" : 0,
      "regexp" : 0,
      "nomen" : 0,
      "vars" : 0,
      "sub" : 0,
      "stupid" : 0,
      "continue" : 0,
      "bitwise" : 0,
      "newcap" : 0,
      "sloppy" : 0,
      "closure" : 0,
      "browser" : 1,
      "properties" : 0,
      "plusplus" : 0,
      "debug" : 0,
      "forin" : 0,
      "eqeq" : 0,
      "evil" : 0,
      "node" : 0,
      "rhino" : 0,
      "devel" : 0,
      "ass" : 0
    },
    "uglifyFlags" : {
      "no-mangle-functions" : 0,
      "no-mangle" : 0,
      "no-copyright" : 0,
      "no-dead-code" : 0,
      "inline-script" : 0,
      "ascii" : 0,
      "unsafe" : 0,
      "mangle-toplevel" : 0,
      "no-seqs" : 1,
      "beautify" : 0,
      "lift-vars" : 0,
      "consolidate-primitive-values" : 0,
      "no-squeeze" : 0
    },
    "sassAutoOutputPathReplace2" : "css",
    "slimAutoOutputPathReplace2" : "",
    "jadeCompileDebug" : 1,
    "slimRailsCompatible" : 0,
    "kitAutoOutputPathReplace2" : "",
    "lessRelativeURLS" : 0,
    "lessDebugStyle" : 0,
    "javascriptAutoOutputPathRelativePath" : "",
    "slimAutoOutputPathStyle" : 0
  },
  "projectAttributes" : {
    "bourbonEnabled" : 1,
    "displayValue" : "educabot",
    "displayValueWasSetByUser" : 0,
    "compassEnabled" : 0
  }
}

Thanks in advance for any help

**Comment by minimalart** [comment]
Wrong indent, sorry.
Correct folder tree

```
project
project/source
project/source/jade
project/source/jade/index.jade <--- this files is missing in Codekit
project/source/sass
project/source/sass/main.scss <---- missing
project/public
```

**Comment by bdkjones** [comment]
You’ve likely got a corrupt data file. Try resetting the app by quitting it and then relaunching while holding down the shift key.

**Comment by minimalart** [comment]
No, still doesn´t show any file inside the project folder.

**Comment by bdkjones** [comment]
Have you added anything to the Skipped Items list in the preferences window?

**Comment by minimalart** [comment]
I'm an IDIOT. I don't remember when or why, but "source" was there.
Thanks so much and I'm very sorry for wasting your time.
