### ISSUE TITLE
Mavericks Issues

### ISSUE THREAD

**Issue by jakeboyles** [bdkjones/CodeKit-1-Old#694]
Hello I just bought the app and am trying to open it using mavericks and keep getting this error:

The recorded license information is not valid so CodeKit will now quit. This may be caused by a corrupt preferences file. Try deleting ~/Library/Preferences/com.incident57.codeKit.plist. Sorry for the trouble.

I have removed the plist file and have restarted, cleared pram and all that and it still wont work. Any ideas?

**Comment by bdkjones** [comment]
If you get this message, you need to do this:

1) go to the terminal and type `defaults delete com.incident57.CodeKit'

2) restart your Mac. (Mavericks does some more robust caching of preferences, so just deleting the plist does not guarantee that the system has "forgotten" the old preferences.)

3) Launch CodeKit. You should receive a message about an expired trial. At that point, enter your license information and you'll be all set.
