### ISSUE TITLE
CodeKit 1.9.2: kernel_require.rb: cannot load such file -- sass-css-importer

### ISSUE THREAD

**Issue by moneal** [bdkjones/CodeKit-1-Old#696]
I just upgraded to 1.9.2 and I'm getting this error when running CodeKit on my compass project "LoadError on line ["45"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- sass-css-importer"

But everything works fine if I run from the command line and worked fine before the update. I'm using all the internal compilers. 

Running on Mavericks.

**Comment by bdkjones** [comment]
It sounds like you've altered the default Ruby configuration on your Mac using RVM or some other Ruby version manager. Is that the case? What is the output when you open the terminal and type: `ruby -v`

**Comment by moneal** [comment]
I am using rvm but its running system ruby. 

```
[~] ➔ which ruby
/usr/bin/ruby
[~] ➔ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13
```

**Comment by bdkjones** [comment]
I can't find a file named "sass-css-importer" in either Sass or Compass. 

Are you using Compass on this project, and is that file a Compass plugin?

**Comment by moneal** [comment]
Oh wow! I'm sorry, I feel stupid. I forgot that I manually added that to the CodeKit engines last version. Yeah its a compass project and I have it required in my default config.rb. Removing the require totally fixed the problem...
