### ISSUE TITLE
Running out of watched files limit

### ISSUE THREAD

**Issue by lmazurek** [bdkjones/CodeKit-1-Old#698]
Hi,

I'm working on several web projects and I'm getting "Maximum Item Limit Exceeded" when trying to add one more project. The funny thing is that I have only one project active (checkbox checked).

I understand that there is a restriction from Apple, but… Could CodeKit only count active projects?

I don't mind having to uncheck some projects (I work on max 3 at a time), but having to remove projects from CodeKit and reading them when I'm working on one is a pain. I get lots of issues then: CSS output paths have to be set from scratch, JS files start to generate ck versions which I don't want, etc.

Please consider changing how the count is done.

Many thanks.

**Comment by bdkjones** [comment]
CodeKit 2.0 will lift the file limit to infinity. Due later this year.

In the meantime, use project-level settings to store the settings for each project so that you can remove it from the app and add it back and get the exact same settings you had previously.

**Comment by lmazurek** [comment]
Thank you for swift response! Will check project settings feature for the time being.

Wow, so many new apps/updates coming this year (Sketch, Macaw, Skala Beta and even CodeKit), we web developers are are sooo getting spoiled… ;)

Cheers
