### ISSUE TITLE
Feature request: Ability to not compile JS files

### ISSUE THREAD

**Issue by lmazurek** [bdkjones/CodeKit-1-Old#699]
I use CodeKit only for parsing LESS files on steroids (with frameworks - awesome feature btw), but every time I create a new project, or add some JS files to a project, they get parsed and CK files pop up.

Could this be somehow disabled (e.g. a checkbox in preferences)? Or maybe I'm missing something obvious? :)

Cheers

**Comment by bdkjones** [comment]
You have two options:

1) add *.js to the Skipped Items list in preferences before adding your project to the app.

2) Change the "then" action on the Javascript files to: "concatenate imported files". As long as your JS files don't import any others (which would require you to manually set that up), nothing will happen when you save them.

Cheers.

**Comment by lmazurek** [comment]
Number 1 works like a charm. Ok, I have to re-add all currently added projects, but if I have to do this only once I can live with that ;)

Thanks mate!
