### ISSUE TITLE
@import chain not fully working

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#7]
In stylesheet.less (the file I'm compiling to stylesheet.css)

```
@import "someFile.less";                   // saving this file compiles stylesheet.css
@import "whatever/someFile.less";          // saving this file doesn't compile stylesheet.css
@import "../../whatever/someFile.less";    // saving this file doesn't compile stylesheet.css
```

All of the above files are hidden. The top one by filename and the other 2 by folder.

**Comment by bdkjones** [comment]
Can you send me the full project with the files in the directory structure that isn't working?

Thanks!

**Comment by paulyoung** [comment]
Unfortunately it's under NDA but I'll try to recreate something with the same structure.

**Comment by paulyoung** [comment]
Not exactly what I've got but something like part of it.

[Example project](http://db.tt/ZolZ9lw)
[Screencast](http://db.tt/mDFTjmp)

**Comment by paulyoung** [comment]
This is working as long as files that are imported are in the project directory and not above it.

Optionally you can add directory of the imported files as a separate project in order for those files to be available to CodeKit.
