### ISSUE TITLE
Update to 1.9.3 - no longer compiles

### ISSUE THREAD

**Issue by SeanTurtle** [bdkjones/CodeKit-1-Old#702]
This happened on my MacBook and iMac at home after updating, so I tried a test compile on my work machine before updating (it was fine), updated to 1.9.3 and this too will no longer compile. 

Tried both internal compiler and standalone. Internal results in this:

"Compass was unable to compile one or more files in the project: 

LoadError on line ["45"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- zurb-foundation
Run with --trace to see the full backtrace"

Standalone results in this:

"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: illegal switch in RUBYOPT: -E (RuntimeError)"

Appreciate any help.

**Comment by SeanTurtle** [comment]
Just an additional note, I've reinstalled Ruby, Compass and Foundation - all to no avail.

**Comment by bdkjones** [comment]
You're using Zurb, so you need to switch CodeKit to an external Compass compiler.

You currently have Compass installed in the Ruby 1.8.x environment that's left over from older versions of OS X. What you need to do is install both Compass and Foundation in the new Ruby 2.0 environment.

You should be able to do this by simply installing them at the command line as normal.
