### ISSUE TITLE
codekit-prepend not working outside Project root

### ISSUE THREAD

**Issue by tobystokes** [bdkjones/CodeKit-1-Old#703]
Javascript files with a 
//@codekit-prepend "../../Shared/[...]"
i.e. where the included file is relative, but happens to be outside/above the root of the CodeKit project, does not show up in the import lists, and does not get included on compile.

**Comment by bdkjones** [comment]
This is expected behavior. If the file is not in the same project or within a CodeKit Framework, the app has no idea it exists and therefore won't link it.
