### ISSUE TITLE
After max limit message, can't add new project

### ISSUE THREAD

**Issue by uzegonemad** [bdkjones/CodeKit-1-Old#705]
After displaying the max limit message, CodeKit got stuck adding new projects until I restarted the app.
1. Attempt to add laravel folder
2. OK through the limit message
3. Attempt to add public folder from laravel install
4. Progress bar gets stuck

**Comment by bdkjones** [comment]
Looks like the app's data file was corrupted. Quit CodeKit and then relaunch it while holding down the shift key to clear everything out and start fresh.
