### ISSUE TITLE
Effects of optimization not shown upon clicking "Optimize"

### ISSUE THREAD

**Issue by ddanielou** [bdkjones/CodeKit-1-Old#71]
After optimizing image x, you must select another one and select x again to see the results of optimization. Not crucial, but thought I'd mention it.

Also, I'd feel so powerful if, after optimizing all image files, CodeKit told me that "Yay, you saved a whopping 14.6kb! You're such an awesome designer!". Or something to that effect.

**Comment by bdkjones** [comment]
Fixed in 3988.

Good catch.
