### ISSUE TITLE
Chrome is not injecting css anymore

### ISSUE THREAD

**Issue by Roywcm** [bdkjones/CodeKit-1-Old#714]
Hi, 

Suddenly Chrome is not injecting the css anymore in my project. 
It is still working In Safari and other projects. 

I tried to clean the cash of Chrome, started Codekit with holding shift and re-added the project in Codekit.

Any idea what's this causing?

**Comment by bdkjones** [comment]
A) Reboot your Mac.

If that does not fix it, then there are two possibilities:
1. You have an error in your page markup. A missing tag, non-standard <link> elements to your stylesheets, etc. 
2. You're running an incompatible JS library on the page, such as prefix-free.js, which is interfering with CodeKit's injection process.

**Comment by Roywcm** [comment]
I tried to restart my mac and removed all javascripts and stylesheets except one test.css so they can't interrupt Codekit. But still no luck...

edit: I'm using MAMP pro for building a magento theme. Maybe the problem is in MAMP?

edit2: I don't know why, but for some reason it is working again. Thnx!
