### ISSUE TITLE
Backblaze reason why Codekit doesn't compile and crashes?

### ISSUE THREAD

**Issue by bartligthart** [bdkjones/CodeKit-1-Old#716]
In another thread I've found this advice why codekit is crashing all the time. I realised I just installed Backblaze. This is a product that backups all my files on my mac. I want my files to keep being backed up. But codekit isn't working at all right now. How can I fix this?

3) Browser plugins / conflicting apps: are you watching a folder in CodeKit that's being managed by a service like SugarSync or Dropbox?

**Comment by bdkjones** [comment]
The first thing to do is reset CodeKit by quitting the app and then relaunching it while holding down the shift key. That will clear everything out and give you a fresh start.

If the issue persists, you'll need to pause BackBlaze while using CodeKit, as the two apps are likely conflicting with file-change notifications.

**Comment by bartligthart** [comment]
This does not fix it. I've tried to restart codekit while holding down the shift key several times. Starting the app takes like 4 minutes and if I save a scss file it also takes a long time. The app also takes a lot of memory.

Backblaze is on pauze and the whole folder is excluded from backing up.

**Comment by bdkjones** [comment]
If the app is still taking 4 minutes to launch, you're not performing the shift-start correctly. You need to quit the app, then press the shift key and launch CodeKit and keep the key held until you see CodeKit's window come up.

**Comment by bartligthart** [comment]
Tried it a few times didn't work. I removed the app with Appcleaner and then installed codekit again. Everything works fine now. Thanks for the help.

http://www.freemacsoft.net/appcleaner/
