### ISSUE TITLE
parser.js throwing an error

### ISSUE THREAD

**Issue by ginghamsburg** [bdkjones/CodeKit-1-Old#72]
Saving a less file suddenly gives me the following error:

/Applications/CodeKit.app/Contents/Resources/engines/less/lib/less/parser.js:263
                 filename: env.filename
                                 ^

[object Object]

Not sure why. It's a file I've been working with a few days now.

**Comment by bdkjones** [comment]
$10 says when you send me the file I'm gonna send it back to you with an email that says, "You forgot a semicolon" or "You mistyped X." ;)

I can't diagnose the issue without the file. Please send it to bryan at incident 57 dot com.

**Comment by ginghamsburg** [comment]
Yep, missing bracket.

**Comment by bdkjones** [comment]
(I get one or thirty of these kinds of emails every week.) Glad you found the typo!
