### ISSUE TITLE
LESS – editing reference imported file doesn't trigger compile

### ISSUE THREAD

**Issue by Zija** [bdkjones/CodeKit-1-Old#723]
Given the following:

``` less
/*
 * main.less
 */

@import (reference) 'file.less';
...
```

I would expect editing 'file.less' would trigger 'main.less' to compile, and for 'file.less' to be listed under _Imports_ for 'main.less'. At the moment it doesn't seem to be working that way.

**Comment by bdkjones** [comment]
Yep, this is fixed in CodeKit 2. Next week.

**Comment by bfricka** [comment]
Any info to leak on CK2? Hey, it's worth a shot.

**Comment by stef-rausch** [comment]
It will be released in Tuesday — check Twitter ;)
