### ISSUE TITLE
CodeKit will not refresh WebKit

### ISSUE THREAD

**Issue by weskoop** [bdkjones/CodeKit-1-Old#76]
CodeKit will not trigger a refresh with the WebKit nightlies.

**Comment by bdkjones** [comment]
Hmm... I'll investigate. The app uses the Cocoa Application Bridge (rather than AppleScript) to communicate with Safari. I'm not sure if the nightlies support the bridge.

**Comment by bdkjones** [comment]
Selecting "Safari" as a browser to refresh will now apply to both the production version of Safari and the nightly build of WebKit. Feature will make it into Beta 3 in a few days.
