### ISSUE TITLE
Permissions warning on launch

### ISSUE THREAD

**Issue by jbuchanan** [bdkjones/CodeKit-1-Old#77]
On launch, stock Lion install:

**MODAL:**

**You don’t have permission to save the file “CodeKit” in the folder “Library”.**
To view or change permissions, select the item in the Finder and choose File > Get Info.

Things I've checked:
- I'm an admin.
- /Library and ~/Library are writeable by me.
- Codekit is running as me.

Any ideas?

Thanks.

**Comment by bdkjones** [comment]
The permissions on your library folder appear to be mucked up. Try repairing permissions with disk utility and see if that fixes it. Never had anyone with this problem before.

**Comment by jbuchanan** [comment]
Ran disk utility -- did have some Library permission errors, but all were repaired.

Still no joy. Same error on launch.

Any particular directories I should be watching?

Console to system.log as follows:

`Nov 13 18:33:04 Quarto CodeKit[1823]: +entityForName: could not locate an NSManagedObjectModel for entity name 'LPGroup'
Nov 13 18:33:04 Quarto CodeKit[1823]: (
        0   CoreFoundation                      0x00007fff8c024286 __exceptionPreprocess + 198
        1   libobjc.A.dylib                     0x00007fff90380d5e objc_exception_throw + 43
        2   CoreData                            0x00007fff914914b9 +[NSEntityDescription entityForName:inManagedObjectContext:] + 153
        3   CodeKit                             0x000000010dffdba6 -[LPModelController initializeModelGroups] + 103
        4   CodeKit                             0x000000010dffd98f -[LPModelController init] + 351
        5   AppKit                              0x00007fff8aef1bcf -[NSCustomObject nibInstantiate] + 418
        6   AppKit                              0x00007fff8aef19ba -[NSIBObjectData instantiateObject:] + 303
        7   AppKit                              0x00007fff8aef0c19 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 347
        8   AppKit                              0x00007fff8aee752f loadNib + 322
        9   AppKit                              0x00007fff8aee6a28 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:withZone:ownerBundle:] + 217
        10  AppKit                              0x00007fff8aee6943 +[NSBundle(NSNibLoading) loadNibFile:externalNameTable:withZone:] + 141
        11  AppKit                              0x00007fff8b0d5bc6 -[NSWindowController loadWindow] + 221
        12  AppKit                              0x00007fff8b0d5981 -[NSWindowController window] + 75
        13  AppKit                              0x00007fff8b0d57ef -[NSWindowController showWindow:] + 40
        14  CodeKit                             0x000000010dff5f13 -[LessPlusAppDelegate applicationWillFinishLaunching:] + 556
        15  Foundation                          0x00007fff8f4fbde2 __-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_1 + 47
        16  CoreFoundation                      0x00007fff8bfcce0a _CFXNotificationPost + 2634
        17  Foundation                          0x00007fff8f4e8097 -[NSNotificationCenter postNotificationName:object:userInfo:] + 65
        18  AppKit                              0x00007fff8aedb922 -[NSApplication finishLaunching] + 333
        19  AppKit                              0x00007fff8aedb4d4 -[NSApplication run] + 125
        20  AppKit                              0x00007fff8b15a80c NSApplicationMain + 867
        21  CodeKit                             0x000000010dff5b9f main + 115
        22  CodeKit                             0x000000010dff5b24 start + 52
        23  ???                                 0x0000000000000002 0x0 + 2
    )`

**Comment by bdkjones** [comment]
The only Library folder CodeKit uses is this one:

~/Library/CodeKit

Which is where the datafile is stored for the app. Check permissions on that folder.

**Comment by jbuchanan** [comment]
OK -- my system. The "Locked" bit had become set but the GUI wasn't displaying. Surprised anything is working :)

Thanks for the help.

Closing this issue.
