### ISSUE TITLE
import scss css3

### ISSUE THREAD

**Issue by jankeesvw** [bdkjones/CodeKit-1-Old#81]
Hi,

I have been using Codekit on one of my projects which worked using the commandline tool of Sass, but in CodeKit i get this error:

Syntax error: File to import not found or unreadable: compass/css3.
              Load path: /
        on line 1 of /FULLPATH/sass/style.scss
  Use --trace for backtrace.

This is what i do on the first line: 

@import "compass/css3";

**Comment by bdkjones** [comment]
CodeKit currently does not support Compass. I'm working on adding it, though!
