### ISSUE TITLE
Compile-Errors make CodeKit take focus

### ISSUE THREAD

**Issue by nocksock** [bdkjones/CodeKit-1-Old#82]
This might be intentional, but I find this behavior quite annoying. Sometimes I just hit :w / ⌘s in the middle of coding – which has become quite a habit – I even had AutoSave on for a while when vim was loosing focus. Nevertheless I even find it annoying when I'm saving "on purpose" and I have some CS-SyntaxError and CK takes window-focus… and I get some "beep beep beep" for every keystroke after saving… 

I'd rather have the first lines of the error message in the growl-notification and keep focus where it is, so I wont get pulled out of the flow.

**Comment by bdkjones** [comment]
If only there were an option in the preferences window to change this behavior!

**Comment by atuttle** [comment]
For anyone who may be wondering...
![](https://www.evernote.com/shard/s240/sh/719fa01f-0a26-4b6d-b7f2-442df4f1e212/6246c3716675b1457938a5e1f8b60f74/deep/0/Screenshot%203/12/13%203:10%20PM.jpg)
