### ISSUE TITLE
Initially tries to save compiled CoffeeScript as folder

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit-1-Old#83]
Using TextMate, I created an `app.coffee` file, which is automatically set to save as `app.js`, but on save, CodeKit fails to save the file but manages to create a folder named `app.js` next to the `app.coffee` file. I can then delete that folder and refresh the CodeKit project - now when I save the `app.coffee` file, the `app.js` file gets created successfully.

Log error message: 

> Although the file compiled successfully, CodeKit could not write it to this location:
> ~/Development/src/XXXXXXX/PPPPPPP/public/scripts/app.js 
> Check folder/file permissions, see the Mac OS X Console for more error information and try again.

**Comment by bdkjones** [comment]
Have you changed the default output path setting for JS files in the "advanced" pane of the preferences window? If so, what settings are you using there?

**Comment by greystate** [comment]
They're set as follows:

**To this path:** `../../public/scripts`
**Relative to:** `The folder that contains the original source file`
**Create this folder if it does not exist** (checked)

**Comment by bdkjones** [comment]
Oy, took me a while to replicate this bug.

Turns out that it only happens if you've got CodeKit set to check the compiled JS with either JSHint or JSLint. Working on a fix.

**Comment by bdkjones** [comment]
Fixed in 4061. 

Thanks for the report!
