### ISSUE TITLE
CSS Animations are triggering syntax errors

### ISSUE THREAD

**Issue by danphilibin** [bdkjones/CodeKit-1-Old#86]
I'm getting a syntax error on the second line of this CSS keyframe animation code, so my LESS file can't be parsed:

`@-webkit-keyframes cloudanimate {
    0%, 100% { margin-left:0; }
    50% { margin-left:50px; } 
}`

**Comment by bdkjones** [comment]
This is not an issue with CodeKit; it's a bug in Less itself.

Less currently does not support the % syntax in keyframe animations; it only works with "from, to". There are several open issues on the Less.js GitHub page documenting this behavior.

As a workaround until a fix is issued, you can place your keyframe animation declaration in an external CSS file and then @import that css file into your LESS file where the keyframe animation should appear.

**Comment by bdkjones** [comment]
Just checked, and it looks like Alexis patched this issue in Less just a couple days ago.

I'll update the LESS components in CodeKit and Less.app to take advantage of the fix.
