### ISSUE TITLE
Interaction with BBEdit-project window

### ISSUE THREAD

**Issue by abrell** [bdkjones/CodeKit-1-Old#87]
I use BBEdit as my primary editor. When I drag a folder that is observed by CodeKit into BBEdit, the resulting project window gets a nervous flicker from time to time. Specifically, the x-button to closed a open file flickers so heavily it becomes very distractive. This is immediately solved when I close CodeKit.

**Comment by bdkjones** [comment]
I don't have BBEdit, but this sounds like a problem on their end. I'd have to get in touch with them to find out more info. Please file a bug with the BBEdit guys and include my email: bryan at incident 57 dot com.

I've worked with them before on another issue, so I'm sure we can get this one resolved.
