### ISSUE TITLE
Remove focus on Files tab on load

### ISSUE THREAD

**Issue by derrickpelletier** [bdkjones/CodeKit-1-Old#90]
When the app is first loaded the Files tab has the glowing focus ring around it. It probably shouldn't.

If you click elsewhere, the focus is gone and won't even reappear on subsequent clicks of the tabs.

Pretty minor issue.

**Comment by bdkjones** [comment]
Huh. I can't replicate this issue. Can you send me a screenshot?

**Comment by derrickpelletier** [comment]
Indeed, should have before.

http://cl.ly/2D3V3o241a1B3c3p413F

**Comment by derrickpelletier** [comment]
I should mention that it looks worse under OS X Graphite (I only switched to Blue to see the difference). In Graphite it just makes the button look really blurry, as the focus ring colour is quite similar to the interface itself.

**Comment by bdkjones** [comment]
Got it. I've disabled all focus rings for that element. (They should never have appeared there anyway and I couldn't get them to do so on my machine; the search field has focus when I start the app up fresh.)

Regardless, this should be fixed in the next beta.
