### ISSUE TITLE
Importing .css in less files

### ISSUE THREAD

**Issue by ockam** [bdkjones/CodeKit-1-Old#92]
Codekit 1.0 4011 doesn’t seem to support importing a plain css file (that doesn’t require processing) into into a less file, even though less do support it.

See http://lesscss.org/#-importing

Ex.: @import "style.css";

**Comment by bdkjones** [comment]
What is the behavior you're seeing?

If your LESS file looks like this:

//
//  various less code
//

@import "../some/other/file.css";

//
//  more less code
//

Then your compiled CSS should look like this:

//
//  css (compiled)
//

@import "../some/other/file.css";

//
//  more css (compiled)
//

In other words, the import statement should simply be carried across, untouched. Are you saying the import statement is disappearing?

**Comment by ockam** [comment]
I insert the import statement manually in the less file.

The import statement disappear when processed and the content of the plain css file isn’t inserted. 

And you don’t see the file in CodeKit import pane either.

**Comment by ockam** [comment]
Just realized less won’t insert the plain file code, but carry through the import rule.

Since I placed my import after other styles, the processor removed it because you can’t have import call after style rules.
