### ISSUE TITLE
"Pages" icons not very helpful

### ISSUE THREAD

**Issue by ddanielou** [bdkjones/CodeKit-1-Old#93]
This has been bugging me for a while.
I don't get it: why a macbook icon for pages? Wouldn't it be more useful if you displayed a generic file icon, plus maybe something related to the file type (, plus maybe a codekit logo)?

Also, feel free to ignore this completely and put a disgusted look on your face but: is that «Bliss» on the image icons?! Was thinking that maybe a preview would be doable…

Btw, so that I don't seem to dis the job you did on icons completely: JS, less etc icons are gorgeous. The other two are really pale in comparison, I think…

**Comment by sunnywalker** [comment]
I get an iMac icon for pages instead of a macbook icon--probably because I'm using it on an iMac. I agree that it's an odd choice, but it never personally bothered me.

**Comment by bdkjones** [comment]
Feel free to email me a replacement. I've spent hours trying to create a good one.

**Comment by bdkjones** [comment]
Changed in 4096. Still not 100% happy with it.
