### ISSUE TITLE
Adding Frameworks - missing css

### ISSUE THREAD

**Issue by simoncox** [bdkjones/CodeKit-1-Old#95]
What a great project this is - am really enjoying using it.

When i add a directory with subdirectories for file types (css, js etc) as a framework, CodeKit is showing js files but not any of the css files. A quick test shows that it is pulling in .less files though. 

Is there a reason for not including framework css files?

**Comment by bdkjones** [comment]
Yep. CodeKit does not watch, manage or deal with CSS files. It _creates_ CSS files by compiling other languages. If you have code that you want to use in a framework, you should put that code in a LESS, SASS, SCSS or Stylus file --- all of which will show up in frameworks.
