### ISSUE TITLE
Failed to compile less file when using "filter" gradient effect for IE browsers

### ISSUE THREAD

**Issue by Surbma** [bdkjones/CodeKit-1-Old#96]
It is not possible to compile, if I use the "filter" method to have a gradient background for IE browsers, like this:

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00adee', endColorstr='#0078a5');

**Comment by Surbma** [comment]
I've found the solution: missing opening and closing "", so the right code is:

filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#00adee', endColorstr='#0078a5')";

**Comment by bdkjones** [comment]
Awww, I got all excited about this when I saw it on my iPhone this morning. Couldn't wait to get to my laptop to make a snarky comment about reading the docs, and then you go and take all the wind out of my sails by figuring it out before I got to my laptop.

Angry midgets on the way.
