### ISSUE TITLE
Undefined variables in imported LESS stylesheets

### ISSUE THREAD

**Issue by bluestrike2** [bdkjones/CodeKit-1-Old#97]
When working with imported LESS stylesheets and I save one of the imported stylesheets, I get variable undefined errors from variables that are defined in other imported sheets. The variables are rendered correctly in the output, it's just that the errors are logged just the same.

**Comment by bdkjones** [comment]
I'm going to need a more thorough explanation. 

If Less is telling you that it can't find a given variable, there should not be any output. Try deleting the CSS files and verify that new ones are _actually_ created (you may simply be looking at the old ones.)

Additionally, when using variables across multiple files, you should create a single "main" file that @imports all others. It would look like this:

---

@import "variables.less";
@import "file1.less";
@import "file2.less";

## @import "file3.less";

You should never @import "variables.less" into each of the 3 files --- doing so will generate duplicated CSS. See the Twitter Boostrap framework for the perfect example of how to use variables across files correctly.

**Comment by bdkjones** [comment]
Wow. Github completely borked the formatting of that last comment.

The giant @import file3 should be inside the lines, etc.

**Comment by bdkjones** [comment]
Haven't heard back, so closing this until I can get a set of files that allow me to test on my end.

**Comment by bluestrike2** [comment]
Just wanted to let you know that the issue seems to be resolved at this point. For what it's worth, they were all being imported by the master file (and not individual ones). Thanks again!

Just wish I knew exactly what was the issue so I could give you more info; unfortunately, it was a number of commits in the past and I didn't mark it. Sorry!
