### ISSUE TITLE
Tab inside @import declaration (LESS)

### ISSUE THREAD

**Issue by bluestrike2** [bdkjones/CodeKit-1-Old#99]
Just wanted to file the bug report you wanted about the tab in an @import declaration breaking the LESS parser. Actually, I had a similar issue with the LESS app if that helps you any as well.

**Comment by bdkjones** [comment]
Yep. Turns out that this seems to be an issue with Less itself rather than the app. 

CodeKit correctly eliminates the tabs when it parses the @import statement. It appears that the Less Compiler, however, does not.
